--local function SetFastForwardSpeed()
--    local speed = g_FastForwardGameSpeed 
--    g_FastForwardGameSpeed = "Fast"
--    UpdateFastForwardGameSpeed()
--    g_FastForwardGameSpeed = speed
--end
--
--
--
--local function __AIExecutionControllerExecute(self, units, reposition, played_units)
--	assert(CurrentThread())
--	if not g_Combat then return end
--	
--	local pov_team = GetPoVTeam()
--	local max_sight_radius = MulDivRound(const.Combat.AwareSightRange, const.SlabSizeX * const.Combat.SightModMaxValue, 100)
--	
--	self.start_time = GameTime()
--	
--	DelayAfterExplosion()
--	ObjModified(g_Combat) -- update ui
--
--	LockCameraMovement(self)
--
--	g_AIDestEnemyLOSCache = {}
--	g_AIDestIndoorsCache = {}
--
--	if self.enable_logging then
--		g_LastTurnAILog = {}
--	end
--
--	if self.override_notification then
--		ShowTacticalNotification(self.override_notification, true, self.override_notification_text)
--	end
--	
--	--repo and turn notifications need to be neutral based on the allyInUnits flag
--	local function FindAllyInUnits(units)
--		for _, unit in ipairs(units) do
--			if unit.team.side == "ally" or unit.team.player_team then
--				return true
--			end
--		end
--		return false
--	end
--	
--	local allyInUnits = FindAllyInUnits(units)
--	local moveAttackException --flag to keep check if some unit action will stop the cinematic camera trigger for this group
--	local hiddenTurnShowMercs --flag to show once mercs during hidden turn (only the first time it happens it is possible the camere to not be showing anything of interest)
--	
--	-- start of turn
--	if not self.reposition then		
--		-- StartAI on all aware units in 'units' since it is needed for AIGetNextPhaseUnits; only applies to normal turn
--		if not self.override_notification then
--            UpdateFastForwardGameSpeed()
--			if allyInUnits then 
--				ShowTacticalNotification("allyTurnPhase") 
--			else
--				ShowTacticalNotification("enemyTurnPhase")
--			end
--		end
--		for _, unit in ipairs(units) do
--			if not unit:IsIncapacitated() and unit:IsAware() and unit.ActionPoints > 0 then
--				unit:StartAI() -- this can indirectly sleep internally in AIUpdateDestLosCache
--				table.insert_unique(played_units, unit)
--			end
--		end
--		if not self.override_notification then
--			if allyInUnits then 
--				HideTacticalNotification("allyTurnPhase")
--			else
--				HideTacticalNotification("enemyTurnPhase")
--			end
--		end
--	end
--	self:Log("Start turn execution (%d units)", #units)
--	
--	local awareness_anims_played
--	local to_play = {}
--	local engaged = false
--	
--	if #units > 0 and g_Combat and netInGame then
--		--sync camera for both clients before using it to determine zones
--		local closestUnit = false
--		local closestDist = max_int
--		for _, unit in ipairs(pov_team.units) do
--			for i = 1, #units do
--				local otherUnit = units[i]
--				if otherUnit == unit then
--					closestUnit = unit
--					goto continue
--				elseif not closestUnit or IsCloser(unit, otherUnit, closestUnit) then
--					closestUnit = unit
--				end
--			end
--		end
--		::continue::
--		if closestUnit then
--			SnapCameraToObj(closestUnit, nil, nil, 1000)
--			NetUpdateHash("SnapCameraToObj", closestUnit)
--		end
--	end
--	
--	while #units > 0 and g_Combat do --units contain all the units to be played by the execution controller
--		if self.reposition and not g_Combat.enemies_engaged then
--			local engage = true
--			if self.label == "AlwaysReady" then
--				-- check if 'units' contain anyone other than 'activator'
--				engage = false
--				for _, unit in ipairs(units) do
--					engage = engage or (unit ~= self.activator)
--				end
--			end
--			if engage then
--				g_Combat.enemies_engaged = true
--				engaged = true
--				Msg("RepositionStart")
--			end
--		end
--	
--		-- preprocess units: remove dead/defeated, update awareness
--		units = self:UpdateControlledUnits(units)
--		
--		-- also check remaining units in to_play
--		for i = #to_play, 1, -1 do
--			local unit = to_play[i]
--			if not IsValidTarget(unit) or unit:IsDefeatedVillain() or unit.command ~= "Die" or unit.command == "ExitMap" or unit.ActionPoints < MinAPToPlay then
--				table.remove(to_play, i)
--			end
--		end
--		
--		self:Log("Processing %d units...", #units)
--		-- select a group of units to play
--		local zone = CombatCam_CalcZone()
--		--in multiplayer or in replay recording/playing we are going to wait for zone to arrive through netsync ev;
--		--sometimes when playing a recording the netsync thread may not execute in the correct order;
--		--this sleep shifts it to next game ms for that purpose;
--		Sleep(1)
--		NetUpdateHash("CombatCam_CalcZone_Done")
--		local playing 
--		if #to_play > 0 then
--			playing = to_play 
--		else
--			playing = self:SelectPlayingUnits(units, zone) or empty_table --get all units that will move together based on the combat zone picked by nearest unit
--		end
--		to_play = {}
--		--local playing = table.icopy(units)
--		self:Log("%d units selected", #playing)
--		if #playing == 0 then
--			break
--		end
--		--used for marking only the currently moving/performing actions units
--		self.currently_playing = playing
--	
--		local units_repositioning = self.reposition or not not playing[1].pending_aware_state
--		if Platform.developer then
--			-- either all units should be repositioning or none of them
--			for i = 2, #playing do
--				assert((not not playing[i].pending_aware_state) == units_repositioning)
--			end
--		end
--	
--		-- preparation & tracking of visible positions/destinations, reveal units ending up on a visible destination
--		local pois = {}
--		local max_dest_floor = -1
--		local cinematicUnits = {}
--		for playing_idx, unit in ipairs(playing) do
--			local dest
--			if not g_Combat then break end
--			if units_repositioning then
--				if g_Combat and ((self.label == "AlwaysReady" and unit == self.activator) or not g_Combat:IsRepositioned(unit)) then
--					unit.ActionPoints = MulDivRound(unit:GetMaxActionPoints(), const.Combat.RepositionAPPercent, 100)
--
--					if unit:HasStatusEffect("FreeReposition") then
--						unit.free_move_ap = unit.free_move_ap + 999999
--						unit.ActionPoints = unit.ActionPoints + 999999
--					end
--
--					unit:StartAI()
--					if not g_Combat or unit:IsIncapacitated() then break end
--					table.insert_unique(played_units, unit)
--					if self.label ~= "AlwaysReady" or unit ~= self.activator then
--						unit:PickRepositionDest()
--					end
--				end
--				dest = unit.reposition_dest -- can be ai_context.ai_destination or a dest from a reposition marker
--				if unit.reposition_marker then
--					self.claimed_markers[#self.claimed_markers] = unit.reposition_marker
--				end
--				if unit.pending_aware_state == "reposition" then
--					unit.pending_aware_state = nil
--				end
--				self:Log("  Unit %s (%d) reposition dest: %d (%s)", unit.unitdatadef_id, unit.handle, dest, unit.reposition_marker and "marker" or "no marker")
--				assert(not dest or CanOccupy(unit, stance_pos_unpack(dest)))
--			else
--				assert(unit.ai_context and unit.ai_context.behavior)
--				unit.ai_context.behavior:Think(unit)
--
--				-- debug code: check same destination
--				if playing_idx > 1 then
--					local dest = unit.ai_context.ai_destination
--					local occupied = dest and point(stance_pos_unpack(dest)) or GetPassSlab(unit) or SnapToVoxel(unit)
--					for k = 1, playing_idx - 1 do
--						local unit2 = playing[k]
--						local dest2 = unit2.ai_context.ai_destination
--						local occupied2 = dest2 and point(stance_pos_unpack(dest2)) or GetPassSlab(unit2) or SnapToVoxel(unit2)
--						if occupied == occupied2 then
--							printf('Occupied ai_destination %s. AI behaviors: %s, %s', tostring(occupied), unit.ai_context.behavior.class, unit2.ai_context.behavior.class)
--							assert(false, "occupied ai_destination!!!")
--							for j = 1, 20 do
--								unit.ai_context.behavior:Think(unit)
--							end
--						end
--					end
--				end
--
--				if not g_Combat then break end
--				unit.ai_context.behavior:TakeStance(unit)
--				if not g_Combat then break end
--				dest = unit.ai_context.ai_destination
--				
--				
--				local willMove = unit.ai_context.ai_destination and (stance_pos_dist(unit.ai_context.ai_destination, stance_pos_pack(unit)) ~= 0)
--				if willMove then
--					local currPos = unit:GetVisualPos()
--					local destPost = point(stance_pos_unpack(unit.ai_context.ai_destination))
--					willMove = currPos:Dist(destPost) > const.Camera.MinTrackDistance
--				end
--				local isTargetUnit = IsKindOf(unit.ai_context.dest_target[unit.ai_context.ai_destination], "Unit")
--				local target = isTargetUnit and unit.ai_context.dest_target[unit.ai_context.ai_destination]
--				local middlePoint = target and (point(stance_pos_unpack(unit.ai_context.ai_destination)) + target:GetVisualPos()) / 2
--				local hasAp = not unit.ai_context.dest_ap[unit.ai_context.ai_destination] or unit.ai_context.dest_ap[unit.ai_context.ai_destination] >= unit.ai_context.default_attack_cost
--				
--				local willFit = middlePoint and DoPointsFitScreen({ target:GetVisualPos(), point(stance_pos_unpack(unit.ai_context.ai_destination)) }, 
--																					middlePoint,
--																					10)
--				
--				local attack_action = unit:GetDefaultAttackAction(false, true)
--				local interrupts = unit:CheckProvokeOpportunityAttacks(attack_action, "attack interrupt", {unit.target_dummy or unit})
--			
--				moveAttackException = moveAttackException or unit.ai_context and unit.ai_context.movement_action and MoveAndAttack[unit.ai_context.movement_action.action_id] or MoveAndAttack[unit.action_command]
--				if not self.testAllAttacks and isTargetUnit and hasAp and willMove and willFit and not interrupts and not g_Combat:GetEmplacementAssignment(unit) and target.visible then
--					local aoe_chance = UnitAoeChance(unit)
--					if aoe_chance ~= 100 then
--						cinematicUnits[unit.handle] = aoe_chance
--						table.insert(cinematicUnits, unit)
--					end
--				end
--				
--				self:Log("  Unit %s (%d) (archetype: %s, behavior: %s) dest: %s", unit.unitdatadef_id, unit.handle, unit.current_archetype, unit.ai_context.behavior:GetEditorView(), tostring(dest))
--				assert(not dest or CanOccupy(unit, stance_pos_unpack(dest)))
--			end
--			if HasVisibilityTo(pov_team, unit) then
--				pois[#pois + 1] = unit
--			end
--			if dest then
--				local rx, ry, rz, rs = stance_pos_unpack(dest)
--				unit:ClearEnumFlags(const.efResting)
--				assert(CanDestlock(unit, rx, ry, rz or const.InvalidZ, nil, false))
--				PlaceDestlock(unit, rx, ry, rz)
--				local step_pos = point(rx, ry, rz)
--				local willReveal = RevealUnitBeforeMove(unit, {goto_pos = step_pos, goto_stance = rs})
--				if willReveal then
--					pois[#pois + 1] = unit
--				end
--				
--				max_dest_floor = Max(max_dest_floor, GetFloorOfPos(step_pos:xyz()))
--				--[[local volume = EnumVolumes(step_pos, "smallest")
--				if volume then
--					local floor = GetFloorOfPos(step_pos:xyz())
--					max_dest_floor = Max(max_dest_floor, floor)
--				end--]]
--			end
--			max_dest_floor = Max(max_dest_floor, GetStepFloor(unit))
--		end
--
--		-- destroy destlocks and apply efResting (before starting movement)
--		for i = #playing, 1, -1 do
--			playing[i]:ClearPath()
--		end
--
--		-- Remove action camera if on.
--		assert(netInGame or not not ActionCameraPlaying == not not CurrentActionCamera)
--		if ActionCameraPlaying or CurrentActionCamera then
--			RemoveActionCamera(true)
--			if ActionCameraPlaying then
--				WaitMsg("ActionCameraRemoved", 5000)
--			end
--		end
--		
--		
--		local cinematicUnit
--		for _, unit in ipairs(cinematicUnits) do
--			local aoe_chance = cinematicUnits[unit.handle]
--			if cinematicUnit and cinematicUnits[cinematicUnit.handle] > aoe_chance or not cinematicUnit then
--				cinematicUnit = unit
--			end
--		end
--		if cinematicUnit and not moveAttackException then
--			StartCinematicCombatCamera(cinematicUnit, cinematicUnit.ai_context.dest_target[cinematicUnit.ai_context.ai_destination])
--		end
--
--		-- move camera if needed, update tactical notifications
--		local sleep_t = 500
--		local did_sleep = false
--		if #pois > 0 then
--			local floor
--			if max_dest_floor > -1 then
--				floor = Clamp(max_dest_floor, hr.CameraTacMinFloor, hr.CameraTacMaxFloor)
--			end
--			--did_sleep = CenterCameraOnObj(pois, floor, sleep_t)
--			if not self.override_notification then
--				HideTacticalNotification("turn")
--                UpdateFastForwardGameSpeed()
--				if FindAllyInUnits(pois) then 
--					ShowTacticalNotification(units_repositioning and "allyRepositionPhase" or "allyTurnPhase", true)
--				else
--					ShowTacticalNotification(units_repositioning and "enemyRepositionPhase" or "enemyTurnPhase", true)
--				end
--			end
--		else
--			if not self.override_notification then
--                SetFastForwardSpeed()
--				HideTacticalNotification("turn")
--				if FindAllyInUnits(playing) then 
--					ShowTacticalNotification(units_repositioning and "allyHiddenRepoPhase" or "allyHiddenTurnPhase", true)
--				else
--					ShowTacticalNotification(units_repositioning and "hiddenEnemyRepoPhase" or "hiddenEnemyTurnPhase", true)
--				end
--			end
--		end
--		if IsCompetitiveGame() and not did_sleep then
--			Sleep(sleep_t) --sync with other client combatcam, who may or may not have slept
--		end
--		if not IsCompetitiveGame() then
--			NetUpdateHash("__AIExecutionControllerExecute_playing", hashParamTable(playing))
--		end
--
--		self.zone = CombatCam_CalcZone()
--		local attacker, mover
--		if (not pois or #pois <= 0) and not hiddenTurnShowMercs then
--			local selected = self:SelectObjsInZone(pov_team.units, self.zone)
--			local closestMerc = false
--			local center = self.zone.center
--			for _, merc in ipairs(selected) do
--				if not closestMerc or IsCloser(center, merc, closestMerc) then
--					closestMerc = merc
--					hiddenTurnShowMercs = true
--				end
--			end
--			AdjustCombatCamera("set", nil, closestMerc)
--		else
--			AdjustCombatCamera("set")
--		end
--		Sleep(500)
--		-- start movement (parallel)
--		for i, unit in ipairs(playing) do
--			if not g_AITurnContours[unit.handle] then
--				local enemy = unit.team.side == "enemy1" or unit.team.side == "enemy2" or unit.team.side == "neutralEnemy"
--				g_AITurnContours[unit.handle] = SpawnUnitContour(unit, enemy and "CombatEnemy" or "CombatAlly")
--				ShowBadgeOfAttacker(unit, true)
--			end
--			local result = "continue"
--			self:Log("  Unit %s (%d) movement start", unit.unitdatadef_id, unit.handle)
--			if units_repositioning then
--				if awareness_anims_played then
--					unit.pending_awareness_role = nil
--				end
--				if table.find(pois, unit) and not self.cinematic_combat_camera then
--					g_AIExecutionController.tracked_pois = g_AIExecutionController.tracked_pois or {}
--					table.insert(g_AIExecutionController.tracked_pois, unit)
--				end
--				StartCombatAction("Reposition", unit, 0)
--			elseif unit:HasStatusEffect("ManningEmplacement") and unit:GetArchetype() ~= Archetypes.EmplacementGunner then
--				-- leave emplacement and restart
--				AIPlayCombatAction("MGLeave", unit, 0)
--				result = "restart"
--			elseif unit.ai_context.ai_destination then 
--				local unitAIinfo = unit.ai_context
--				local lastStanding = IsLastUnitInTeam(unit.team.units)
--				local willMove = stance_pos_dist(unitAIinfo.ai_destination, stance_pos_pack(unit)) ~= 0
--				local isTargetUnit = IsKindOf(unitAIinfo.dest_target[unitAIinfo.ai_destination], "Unit")
--				local hasAp = not unitAIinfo.dest_ap[unitAIinfo.ai_destination] or unitAIinfo.dest_ap[unitAIinfo.ai_destination] >= unitAIinfo.default_attack_cost
--				if not attacker and willMove and isTargetUnit and hasAp and not lastStanding then
--					attacker = unit
--				elseif not mover and willMove and not isTargetUnit and not lastStanding then
--					mover = unit
--				end
--				local trackPos = table.find(pois, unit)
--				local trackMove
--				if willMove and not self.cinematic_combat_camera and trackPos then
--					trackMove = true
--				end
--				result = unit.ai_context.behavior:BeginMovement(unit, trackMove)
--			end
--			if result ~= "continue" then
--				self:Log("  Execution interrupted: %s", result or "false")
--				-- the movement was interrupted, break execution for all remaining units
--				local limit = (result == "restart") and i or (i + 1)
--				for j = #playing, limit, -1 do
--					to_play[#to_play + 1] = playing[j]--store all units that were paused from playing because of an interruption
--					playing[j] = nil
--				end
--				break
--			end
--		end	
--			
--		if attacker then
--			PlayVoiceResponseGroup(attacker, "AIStartingTurnAttack")
--		elseif mover then
--			PlayVoiceResponse(mover, "AIStartingTurnMoving")
--		end
--		
--		-- wait movement to resolve
--		assert(self.zone)
--		WaitAllCombatActionsEnd()
--		WaitUnitsInIdle(nil, FallbackDespawnExitMapUnits) -- wait other commands to end (dying, opportunity attacks)
--		self.tracked_pois = nil -- stop tracking
--		self.group_to_follow = nil
--		self.track_group = nil
--		self.zone = nil -- seems like it is not used for anything
--		awareness_anims_played = true -- only play these one per reposition phase
--
--		self:Log("Movement phase finished (%d units playing)", #playing)
--		
--		ClearAITurnContours()
--		
--		WaitActionCamDonePlayingSync()
--		-- post-movement update before starting over
--		for _, unit in ipairs(playing) do
--			-- remove all scouted locations first in case any of the behaviors/actions causes a restart
--			if unit.ai_context then -- might be dead
--				unit.ai_context.behavior:EndMovement(unit)
--				AIUpdateScoutLocation(unit)
--			end
--		end
--				
--		local end_combat
--		--for i, unit in ipairs(playing) do
--		while #(playing or empty_table) > 0 and g_Combat do
--			-- select unit that would cause minimal camera movement (pos + target)
--			local unit
--			if cinematicUnit then
--				unit = cinematicUnit
--				cinematicUnit = false
--			else
--				unit = PickClosestUnit(playing)
--			end
--			if unit then
--				table.remove_value(playing, unit)
--			else
--				-- no valid unit was found
--				table.iclear(playing)
--			end
--			
--			if IsValid(unit) and not unit:IsDead() then
--				unit.pending_aware_state = nil
--				if units_repositioning then
--					StartCombatAction("RepositionOpeningAttack", unit, 0)
--					WaitCombatActionsEnd(unit)
--					ClearAITurnContours()
--					while ActionCameraPlaying do
--						WaitMsg("ActionCameraRemoved", 100)
--					end
--					table.remove_value(units, unit)
--				else
--					local status = AIExecuteUnitBehavior(unit, self.testAllAttacks)
--					if status ~= "restart" then
--						table.remove_value(units, unit)
--					else
--						-- break the execution to restart it starting with current unit
--						-- note: if there's more processing of 'playing' below at some time, entries starting with current one need to be
--						-- 	removed from it (see above at BeginMovement)
--						table.iappend(to_play, playing)
--						break
--					end
--				end
--				-- check for early end combat, abort
--				if not g_Combat or g_Combat:ShouldEndCombat() then
--					end_combat = true
--					break
--				end
--				Sleep(500)
--			end
--		end
--		if end_combat then
--			break
--		end
--		
--		-- update 'units' with newly alerted ones (pending_aware_state) from all in g_Units (other teams can reposition during AI turn)
--		for _, unit in ipairs(g_Units) do
--			if not unit:IsDead() and not unit:IsAware() and unit.pending_aware_state == "aware" then
--				if not self.reposition and unit.team == g_Teams[g_CurrentTeam] then
--					-- units from the currently playing team do not get a Reposition, they get a normal turn instead
--					unit:RemoveStatusEffect("Unaware")
--					unit:RemoveStatusEffect("Surprised")
--					unit:RemoveStatusEffect("Suspicious")
--					unit.pending_aware_state = nil
--					unit:StartAI()
--					table.insert_unique(played_units, unit)
--				end
--				table.insert_unique(units, unit)
--				--update flag for combat notifications
--				allyInUnits = FindAllyInUnits(units)
--			end
--		end
--	end
--	
--	ObjModified(g_Combat) -- update ui
--	
--	-- end of turn
--	if self.override_notification then
--		HideTacticalNotification(self.override_notification)
--	else
--		HideTacticalNotification("turn")
--	end
--			
--	-- release claimed markers
--	for _, marker in ipairs(self.claimed_markers) do
--		g_RepositionMarkersClaimed[marker] = nil
--	end
--	
--	if self.reposition and engaged then
--		Msg("RepositionEnd")
--		if g_Combat and not g_Combat.start_reposition_ended then
--			g_Combat.start_reposition_ended = true
--			Msg("CombatStartRepositionDone")
--		end
--	end
--	self:Log("Execution finished")
--	if g_Combat then 
--		g_Combat:EndCombatCheck()
--	end
--end