-- R.I.S. Phase B content banks (generated by docs/tools/_apply_ris_phase_b.py).
-- GENERATED_FILE / ownership boundary (JAZZ-REF-002-REQ-008):
--   Do not hand-edit numeric T(...) IDs or dossier/AAR payload tables.
--   Re-run docs/tools/_apply_ris_phase_b.py (and related RIS apply scripts) to refresh.
--   Runtime code may read these globals; treat this file as data-only.

JAZZ_RIS_KILL_THRESHOLD = 3
JAZZ_RIS_BATTLE_CAP = 20

JAZZ_RIS_UI = {
	site_title = T(890000000011000, "Recon Intelligence Services"),
	tab_bulletin = T(890000000011001, "Field bulletin"),
	tab_dossiers = T(890000000011002, "Dossiers"),
	tab_reports = T(890000000011003, "After-action reports"),
	empty_bulletin = T(890000000011004, "No supply assessment yet. Once R.I.S. sends one, it will appear here."),
	empty_dossiers = T(890000000011005, "No Legion units identified yet. We will add them as contact reports come in."),
	empty_reports = T(890000000011006, "No after-action reports yet. Finish a battle and R.I.S. will add a summary here."),
	kills_progress = T(890000000011007, "Confirmed kills: <count>/3"),
	dossier_locked = T(890000000011008, "(classified — requires 3 confirmed kills)"),
	section_quest = T(890000000011009, "Key figures"),
	section_legion = T(890000000011010, "Legion units"),
	supply_header = T(890000000011011, "Latest supply assessment"),
	mail_archive = T(890000000011012, "R.I.S. mail archive"),
}

JAZZ_RIS_DOSSIERS = {
	["JAZZ_Legion_Recruit"] = { title = T(890000000011013, "Recruit"), body = T(890000000011014, "Legion recruiters sweep up villagers and send them out after only a few days of drill. They rush forward with whatever weapon they are handed, but lack the training and staying power of regular troops. Keep them at range and break up the group before they crowd a doorway or surround a lone merc.") },
	["JAZZ_Legion_AssaultT1_Crusher"] = { title = T(890000000011015, "Crusher"), body = T(890000000011016, "The Legion picks its strongest bruisers for Crusher duty and teaches them one job: close the distance. A shotgun, solid armor, and sheer toughness make them dangerous inside rooms and narrow alleys. Do not meet them in a doorway; open the range and concentrate fire before the shotgun takes over.") },
	["JAZZ_Legion_AssaultT1_Grenadier"] = { title = T(890000000011017, "Grenadier"), body = T(890000000011018, "New Grenadiers receive a short course in assault explosives before the Legion sends them forward. They carry several grenades beside a pistol or submachine gun, and some add a bottle of burning fuel. Spread out, keep an escape route from cover, and shoot them before they settle behind a corner.") },
	["JAZZ_Legion_AssaultT1_Roughneck"] = { title = T(890000000011019, "Roughneck"), body = T(890000000011020, "Roughnecks receive little formal training; the Legion expects speed and aggression to make up the difference. They fire pistols or automatic weapons on the move and often carry a knife for the last few steps. Make them cross open ground under overlapping fire, and do not let them turn a cramped room into a brawl.") },
	["JAZZ_Legion_AssaultT2_Pillager"] = { title = T(890000000011021, "Pillager"), body = T(890000000011022, "The Legion forms Pillager teams from raiders who survived their first street fights and learned to keep moving. Light armor keeps them quick as they press close with an automatic weapon and, more often than not, a knife. Hold a long line of fire and do not chase them around a blind corner.") },
	["JAZZ_Legion_AssaultT2_Pyro"] = { title = T(890000000011023, "Pyro"), body = T(890000000011024, "Pyros are assault troops singled out for incendiary work rather than careful demolition. They wear heavy armor, carry several firebombs, and follow the flames with a submachine gun or short rifle. Spread out, stay clear of dead-end cover, and bring them down before they get within throwing distance.") },
	["JAZZ_Legion_AssaultT2_ShockTrooper"] = { title = T(890000000011025, "Shock Trooper"), body = T(890000000011026, "Shock Troopers are survivors of the early assault ranks, retrained to keep an attack moving through resistance. They open the assault with several grenades, then close in with an automatic weapon; some also carry smoke or concussion charges. Do not bunch behind one wall—pin them in the open before a grenade clears their route.") },
	["JAZZ_Legion_AssaultT3_Punisher"] = { title = T(890000000011027, "Punisher"), body = T(890000000011028, "Punishers are drawn from assault veterans and trained to keep an attack moving after the first breach. Heavy armor, automatic rifles, and a full load of grenades let them press forward even when the defense holds. Engage from more than one angle, keep a second position ready, and finish one before switching targets.") },
	["JAZZ_Legion_AssaultT3_SkullCrusher"] = { title = T(890000000011029, "Skull Crusher"), body = T(890000000011030, "Skull Crushers are veteran brawlers trained to force a close fight through smoke and confusion. Heavy armor carries them into shotgun or submachine-gun range, where most of them also have a machete and some bring smoke or firebombs. Keep a clear way out of tight interiors and wear them down before they can rush.") },
	["JAZZ_Legion_AssaultT4_Headsman"] = { title = T(890000000011031, "Headsman"), body = T(890000000011032, "Only the Legion's best assault veterans are promoted to Headsman duty and equipped as elite professionals. Heavy armor, upgraded automatic weapons, and plenty of grenades let them cross ground quickly and keep attacking at close range. Make them the first target, cover more than one approach, and never leave a lone merc on their flank.") },
	["JAZZ_Legion_FlankerT1_Warden"] = { title = T(890000000011033, "Warden"), body = T(890000000011034, "Wardens are ordinary riflemen given basic scouting instruction and posted away from the main line. Their light gear helps them reach a side position, where they hold cover and punish movement with steady rifle fire. Check both flanks before advancing, and use smoke or a second angle to dislodge them.") },
	["JAZZ_Legion_FlankerT2_Scout"] = { title = T(890000000011035, "Scout"), body = T(890000000011036, "Scouts are survivors of Warden patrols who have learned to move quietly and choose their approach. They slip around the line with automatic weapons, and may use a knife or smoke once they reach the rear. Keep the flanks paired, watch covered routes, and do not chase a Scout into ground you have not cleared.") },
	["JAZZ_Legion_FlankerT2_Skirmisher"] = { title = T(890000000011037, "Skirmisher"), body = T(890000000011038, "Skirmishers are picked for marksmanship and trained to fight away from the main line. They carry light armor and battle rifles, shifting between flanking positions to fire on exposed targets. Do not follow them across open ground; move under cover or smoke and pin their position before advancing.") },
	["JAZZ_Legion_FlankerT3_Pathfinder"] = { title = T(890000000011039, "Pathfinder"), body = T(890000000011040, "Pathfinders are seasoned scouts trained to choose a concealed firing lane and hold it. Their light gear lets them reach a flank with a carbine or submachine gun, and many also carry smoke or a knife. Sweep nearby cover before moving the main group, then block their escape instead of trading shots from one position.") },
	["JAZZ_Legion_FlankerT3_Recon"] = { title = T(890000000011041, "Recon"), body = T(890000000011042, "Recon troops are veteran scouts trained for quiet approaches and night fighting. They use light gear and compact automatic weapons to close from an unseen angle, sometimes covering the move with smoke. Keep overlapping fields of fire, illuminate dark approaches, and finish them as soon as they reveal themselves.") },
	["JAZZ_Legion_FlankerT4_Ranger"] = { title = T(890000000011043, "Ranger"), body = T(890000000011044, "Rangers are elite scouts selected from the Legion's best flankers and given its finest field training. They move quickly and quietly with upgraded carbines or submachine guns, striking from the side before slipping away. Treat a Ranger as a priority target, overlap your fields of fire, and never leave one merc isolated.") },
	["JAZZ_Legion_FrontT1_Bonemaker"] = { title = T(890000000011045, "Bonemaker"), body = T(890000000011046, "A recruit who breaks from the line to reach a wounded Legionnaire is probably a Bonemaker. The Major chooses people who stay calm around blood, gives them a compact firearm, and hurries them through battlefield medicine. They break off to stop bleeding or treat other wounds. Remove the medic before pressing forward, or fighters you have already hurt will stay in the battle far longer than expected.") },
	["JAZZ_Legion_FrontT1_Marauder"] = { title = T(890000000011047, "Marauder"), body = T(890000000011048, "Looters and local toughs fill the Marauder ranks. They start with pistols and submachine guns; assault rifles appear once better supplies reach the Legion. They plug gaps in the line and rake exposed ground with fire, but pressure can pin them down before they accomplish much. Their short-range weapons punish careless movement, so return fire quickly, keep your distance, and force them to keep their heads down.") },
	["JAZZ_Legion_FrontT1_Rifleman"] = { title = T(890000000011049, "Rifleman"), body = T(890000000011050, "Most Riflemen are conscripts with a few marksmanship lessons, posted to guard roads, doorways, and village approaches. From cover, they use their rifles to watch the ground ahead and wait for a clear shot. A patient Rifleman can punish careless movement, so block his view with smoke or approach from a direction his firing position does not cover.") },
	["JAZZ_Legion_FrontT2_Ambusher"] = { title = T(890000000011051, "Ambusher"), body = T(890000000011052, "Ambushers are patient shooters taught to prepare concealed firing positions along likely approaches. From a prepared position, they wait for an exposed target and punish the first careless move with accurate rifle fire. Do not walk into ground they have chosen; scout ahead, use smoke, and force them to reveal themselves early.") },
	["JAZZ_Legion_FrontT2_Marksman"] = { title = T(890000000011053, "Marksman"), body = T(890000000011054, "The best shots in regular squads are given accurate rifles and taught to wait for a clean shot. They work behind the front, hold useful ground, and let the enemy come to them rather than rushing forward. Their accuracy makes repeated peeking dangerous, so change firing points often and deny them a clear view with smoke.") },
	["JAZZ_Legion_FrontT2_Raider"] = { title = T(890000000011055, "Raider"), body = T(890000000011056, "Raiders are adaptable front-line fighters drilled with automatic weapons; every one also receives hand grenades. They move with the line, use rapid fire to cover short advances, and throw grenades when defenders settle behind cover. Rapid fire and grenades make them dangerous at close and middle range, so spread out, deny them an easy approach, and press them before they can choose where to throw.") },
	["JAZZ_Legion_FrontT3_Sniper"] = { title = T(890000000011057, "Sniper"), body = T(890000000011058, "Only the Legion's finest riflemen receive sniper training: patience, target selection, and careful use of scoped rifles. They watch open approaches from distance and begin an engagement by pinning one exposed target under accurate fire. Crossing open ground gives them an easy shot, so screen movement with smoke and hunt the Sniper before beginning a direct assault.") },
	["JAZZ_Legion_FrontT3_Veteran"] = { title = T(890000000011059, "Veteran"), body = T(890000000011060, "Veterans have survived several campaigns and stayed steady under fire. They advance stubbornly with automatic fire and grenades; a few also bring a launcher, and all keep fighting through punishment that would stop less experienced troops. Their durability and explosives punish a packed formation, so spread out, deny them a clean approach, and concentrate fire before closing in.") },
	["JAZZ_Legion_FrontT4_Mercenary"] = { title = T(890000000011061, "Mercenary"), body = T(890000000011062, "The Legion hires experienced Mercenaries to hold important positions and sends them out with good weapons. They move with the front and combine accurate rifle fire with grenades; a few also carry a launcher, and all keep fighting under pressure. They are dangerous at several ranges, so avoid a fair exchange: split their attention, deny clear shots, and overwhelm one position at a time.") },
	["JAZZ_Legion_FrontT4_MercenarySniper"] = { title = T(890000000011063, "Mercenary Sniper"), body = T(890000000011064, "Mercenary Snipers are proven specialists hired for operations where accurate long-range fire can decide the opening exchange. They begin by pinning an exposed target and use powerful scoped rifles to control open approaches from a distance. Once one is reported, do not expose yourself twice from the same place. Cover movement with smoke and pressure the shooter before committing the squad.") },
	["JAZZ_Legion_GunnerT1_Gunner"] = { title = T(890000000011065, "Gunner"), body = T(890000000011066, "The Legion hands its strongest new recruits old machine guns and gives them a hurried lesson in using them. They set up across roads and courtyards and spray enough fire to pin anyone caught away from cover, but remain vulnerable while moving. Do not cross their sights in the open; use smoke, buildings, or a side approach to reach them safely.") },
	["JAZZ_Legion_GunnerT2_AssaultGunner"] = { title = T(890000000011067, "Assault Gunner"), body = T(890000000011068, "Surviving Gunners are promoted to Assault Gunner duty and taught to carry their light machine guns forward instead of guarding one position. They close the distance, set up near the fight, and pin defenders from positions that ordinary gunners would consider too exposed. If they reach useful firing ground the attack becomes hard to stop, so break their approach with explosives or catch them while they are moving.") },
	["JAZZ_Legion_GunnerT2_GMPG"] = { title = T(890000000011069, "GPMG"), body = T(890000000011070, "Reliable machine gunners are assigned to GPMG duty and taught to keep their fire steady without wasting ammunition. They settle into prepared positions and use a general-purpose machine gun to cover roads, courtyards, and wide approaches. A frontal charge feeds their advantage; block their view with smoke, force them to move, or attack from a direction their position cannot cover.") },
	["JAZZ_Legion_GunnerT3_VeteranGunner"] = { title = T(890000000011071, "Veteran Gunner"), body = T(890000000011072, "Veteran Gunners have survived repeated engagements and are trusted with stronger machine guns. They use disciplined bursts and expert prepared fire to lock down movement, while tougher defenses let them stay effective under pressure. Their fire can stall an attack, so keep them occupied from one direction and strike quickly from another, or destroy the position with explosives.") },
	["JAZZ_Legion_GunnerT4_MercGunner"] = { title = T(890000000011073, "Merc Gunner"), body = T(890000000011074, "Merc Gunners are experienced heavy-weapon specialists hired to use the strongest machine guns available to the Legion. They combine disciplined bursts, prepared fire, and enough resilience to keep a broad approach dangerous under sustained pressure. Leaving them alone can halt an advance, so deny them a clear field of fire and destroy the gunner before committing anyone across open ground.") },
	["JAZZ_Legion_HeavyT1_Rocketeer"] = { title = T(890000000011075, "Rocketeer"), body = T(890000000011076, "Rocketeers are recruits with enough nerve to shoulder a launcher and just enough instruction to avoid hitting their own squad. They fire RPGs or disposable rockets at vehicles, walls, and clustered targets, but the launcher usually leaves them with only one attack before they must recover or reload. Spread out and press them immediately after a launch; one unanswered rocket can turn a defensible position into wreckage.") },
	["JAZZ_Legion_HeavyT2_Grenadier"] = { title = T(890000000011077, "Grenadier"), body = T(890000000011078, "Heavy Grenadiers already understand explosives before they are trained on RPGs and grenade launchers. They send explosive rounds into rooms, courtyards, and covered approaches, forcing anyone who survives the blast to abandon a comfortable position. Remaining in one place invites another round, so move after each shot and pressure the Grenadier before the launcher is ready again.") },
	["JAZZ_Legion_HeavyT3_Mortarman"] = { title = T(890000000011079, "Mortarman"), body = T(890000000011080, "Mortarmen are proven heavy-weapon crews trained to lob shells over walls and other obstacles. They use a portable mortar to strike positions that direct fire cannot easily reach, forcing anyone who remains still to abandon cover. Once the bombardment begins, move immediately and pressure the crew before it fires again. A wall between you and the crew will not keep you safe.") },
	["JAZZ_Legion_LeaderT1_Sergeant"] = { title = T(890000000011081, "Sergeant"), body = T(890000000011082, "When frightened recruits suddenly start moving as one, look for the loudest man among them. The Major turns dependable Legionnaires like that into Sergeants, able to push nearby troops forward, hold them in place, or focus their fire. Remove the leader early and the rest become much easier to disrupt.") },
	["JAZZ_Legion_LeaderT2_Lieutenant"] = { title = T(890000000011083, "Lieutenant"), body = T(890000000011084, "Successful Sergeants become Lieutenants and trade shouting at one group for directing several squads. Their orders reach a wider area, sending troops forward, holding them in place, moving them into cover, or focusing their fire as the situation changes. Their presence keeps a local attack coherent, so remove the officer before the Legion can regroup and turn a confused exchange into an organized assault.") },
	["JAZZ_Legion_LeaderT3_Captain"] = { title = T(890000000011085, "Captain"), body = T(890000000011086, "Captains are officers trusted to control several units at once. They issue orders across the entire Legion force, redirect the attack as conditions change, and support those commands with accurate rifle fire. Every minute a Captain remains active keeps the enemy coordinated, so identify the officer quickly and bring him down before pressing the fight.") },
	["JAZZ_Legion_LeaderT4_MercenaryCaptain"] = { title = T(890000000011087, "Mercenary Captain"), body = T(890000000011088, "Mercenary Captains are experienced officers hired to command mixed troops; they need little more than local intelligence. They issue orders across the entire force, preserve discipline through casualties, and quickly change plans when the first one fails. Assume nearby units are acting with a common purpose while one survives; bring the Captain down before attacking the rest.") },
}

JAZZ_RIS_QUEST_DOSSIERS = {
	["Pierre"] = { title = T(890000000011089, "Pierre Laurent"), body = T(890000000011090, "Luc Laurent's son serves as the Legion's face on Ernie, always in a pressed uniform and with something to prove. He likes being seen as much as being obeyed, which makes him easier to read than most Legion officers. Don't mistake charm for mercy.") },
	["Bastien"] = { title = T(890000000011091, "Bastien"), body = T(890000000011092, "A local fixer with a trader's smile. He knows who controls each road, what passage costs, and whom to pay. A useful contact, but never mistake business for friendship.") },
	["TheMajor"] = { title = T(890000000011093, "The Major"), body = T(890000000011094, "The man behind the Legion built his army with fear, money, and stolen supplies, then spread it across Grand Chien. Every Legion supply report ultimately leads back to him. He is patient, ruthless, and remembers every loss.") },
	["Legion"] = { title = T(890000000011095, "Legion (faction)"), body = T(890000000011096, "The Major's army survives on stolen supplies, forced recruitment, and officers who treat villages as property. Its troops range from frightened locals to trained specialists. Wherever the Legion appears, the Major's reach is close behind.") },
}

JAZZ_RIS_AAR = {
	headlines = {
		["loss|high"] = { T(890000000011112, "Rout — write it honestly"), T(890000000011113, "The desk calls it a disaster"), T(890000000011114, "Smoke and empty stretchers") },
		["loss|low"] = { T(890000000011106, "Forced back, light losses"), T(890000000011107, "Probe failed"), T(890000000011108, "Bad ground, worse timing") },
		["loss|mid"] = { T(890000000011109, "Beaten off the field"), T(890000000011110, "They kept the sector"), T(890000000011111, "Retreat under fire") },
		["retreat|high"] = { T(890000000011121, "Bloody extraction"), T(890000000011122, "Broke through the gauntlet"), T(890000000011123, "Survival first, pride later") },
		["retreat|low"] = { T(890000000011115, "Ordered withdrawal"), T(890000000011116, "You left before it got expensive"), T(890000000011117, "Discretion over medals") },
		["retreat|mid"] = { T(890000000011118, "Forced to pull back"), T(890000000011119, "Falling back to fight another day"), T(890000000011120, "The line wouldn't hold") },
		["win|high"] = { T(890000000011103, "Blood bath — and you walked out"), T(890000000011104, "The Major will hear about this"), T(890000000011105, "Thunder over the sector") },
		["win|low"] = { T(890000000011097, "Quiet clearance"), T(890000000011098, "Sector secured without fireworks"), T(890000000011099, "Low noise, clean finish") },
		["win|mid"] = { T(890000000011100, "Hard fight, held the ground"), T(890000000011101, "They pushed; you pushed back"), T(890000000011102, "Victory with bruised knuckles") },
	},
	weather = {
		clear = T(890000000011124, "The fighting unfolded under clear skies."),
		rain = T(890000000011125, "Rain soaked the ground and frayed everyone's nerves."),
		night = T(890000000011126, "At night, muzzle flashes gave away every shot."),
		fog = T(890000000011127, "Fog cut visibility and kept everyone close to cover."),
		heat = T(890000000011128, "In the heat, exhaustion hit almost as hard as the bullets."),
		dust = T(890000000011129, "The dust storm worked grit into every weapon."),
		default = T(890000000011130, "The weather stayed out of it; the shooting did not."),
	},
	intensity = {
		low = T(890000000011131, "The exchange was brief. It drew little attention beyond the sector."),
		mid = T(890000000011132, "The firefight dragged on as both sides moved under fire. Word of it will spread."),
		high = T(890000000011133, "The fight became a slaughter. The Major's people will hear about it."),
	},
	forces = T(890000000011134, "At first contact, we counted about <player> friendlies and <enemy> hostiles."),
	sector = {
		line = T(890000000011135, "The fighting took place in <sector>."),
		poi = T(890000000011136, "The fighting took place in <sector>, near <poi>."),
	},
	quest = {
		one = T(890000000011137, "This fight was tied to <quest>. One detail may matter: <note>"),
		one_nonote = T(890000000011138, "The evidence ties this fight to <quest>."),
		many = T(890000000011139, "Several active jobs led your team here: <quests>. This was no random skirmish."),
		active = T(890000000011140, "The team was also working on <quest>, though that job was not tied to this sector."),
		none = T(890000000011141, "No active assignment led to this area. This was a fight for the sector itself."),
	},
	character = {
		win = T(890000000011142, "Your team held the field."),
		loss = T(890000000011143, "The enemy kept control of the sector."),
		retreat = T(890000000011144, "Your team withdrew under fire instead of making a last stand."),
		ambush = T(890000000011145, "It looked like an ambush; the opening shots decided the fight."),
		quest_win = T(890000000011146, "The fight was tied to an active job. The objective held, and the sector remained yours."),
		quest_loss = T(890000000011147, "The fight was tied to an active job, and losing the sector will make that job harder."),
		quest_retreat = T(890000000011148, "Your team withdrew from a sector tied to an active job."),
	},
	losses = T(890000000011149, "Our side suffered <pkia> killed and <pwia> wounded; enemy losses were <ekia> killed and <ewia> wounded."),
	elite = {
		killed = T(890000000011150, "<name> went down in the fight — one less elite name on the Major's roster."),
		wounded = T(890000000011151, "<name> left the field bleeding. If they live, they'll remember your faces."),
		escaped = T(890000000011152, "<name> slipped the net. Expect that name again."),
		threat = T(890000000011153, "<name> was still standing when the shooting stopped — unfinished business."),
	},
	closing = {
		quiet = T(890000000011154, "The sector is quiet again, and the fight should draw little attention."),
		noise = T(890000000011155, "Word of this fight will spread. Expect more patrols and more money changing hands."),
		disaster = T(890000000011156, "Mark this one in red. The Major's command will want answers."),
	},
}

-- Key NPC session_ids for R.I.S. obituaries (same desk queue).
JAZZ_RIS_KEY_NPCS = {
	Pierre = true,
	Bastien = true,
	TheMajor = true,
	Spike = true,
	Faucheux = true,
	CorazonSantiago = true,
	Boss = true,
	Emma = true,
	Biff = true,
	FleatownBoss = true,
	Luigi = true,
	Baron = true,
	DiamondRedBoss = true,
}
