-- R.I.S. editorial content banks (generated by docs/tools/_apply_ris_editorial.py).
-- GENERATED_FILE / ownership boundary (JAZZ-UI-RIS-002):
--   Do not hand-edit numeric T(...) IDs or dossier/AAR/strategy payload tables.
--   Re-run docs/tools/_apply_ris_editorial.py --apply to refresh.
--   Runtime code may read these globals; treat this file as data-only.

JAZZ_RIS_KILL_THRESHOLD = 3
JAZZ_RIS_BATTLE_CAP = 20

JAZZ_RIS_UI = {
	site_title = T(890000000011000, "Recon Intelligence Services"),
	tab_bulletin = T(890000000011001, "Field bulletin"),
	tab_dossiers = T(890000000011002, "Dossiers"),
	tab_reports = T(890000000011003, "After-action reports"),
	empty_bulletin = T(890000000011004, "No supply assessment has reached the field desk yet."),
	empty_dossiers = T(890000000011005, "No Legion fighter type has been confirmed yet. The first contact reports will provide enough evidence for short profiles."),
	empty_reports = T(890000000011006, "No completed engagement has been recorded yet."),
	kills_progress = T(890000000011007, "Fighters of this type confirmed killed: <count>/3"),
	dossier_locked = T(890000000011008, "Full assessment after 3 fighters of this type are confirmed killed"),
	section_quest = T(890000000011009, "Key figures"),
	section_legion = T(890000000011010, "Legion units"),
	supply_header = T(890000000011011, "Latest supply assessment"),
	mail_archive = T(890000000011012, "R.I.S. mail archive"),
}

JAZZ_RIS_DOSSIERS = {
	["JAZZ_Legion_Recruit"] = { title = T(890000000011013, "Recruit"), body = T(890000000011014, "Legion recruiters sweep up villagers and send them out after only a few days of drill. They rush forward with whatever weapon they are handed, but lack the training and staying power of regular troops. Keep them at range and break up the group before they crowd a doorway or surround a lone merc.") },
	["JAZZ_Legion_AssaultT1_Crusher"] = { title = T(890000000011015, "Crusher"), body = T(890000000011016, "The Legion picks its strongest bruisers for Crusher duty and teaches them one job: close the distance. A shotgun, solid armor, and sheer toughness make them dangerous inside rooms and narrow alleys. Do not meet them in a doorway; open the range and concentrate fire before the shotgun takes over.") },
	["JAZZ_Legion_AssaultT1_Grenadier"] = { title = T(890000000011017, "Grenadier"), body = T(890000000011018, "New Grenadiers receive a short course in assault explosives before the Legion sends them forward. They carry several grenades beside a pistol or submachine gun, and some add a bottle of burning fuel. Spread out, keep an escape route from cover, and shoot them before they settle behind a corner.") },
	["JAZZ_Legion_AssaultT1_Roughneck"] = { title = T(890000000011019, "Roughneck"), body = T(890000000011020, "Roughnecks receive little formal training; the Legion expects speed and aggression to make up the difference. They fire pistols or automatic weapons on the move and often carry a knife for the last few steps. Make them cross open ground under overlapping fire, and do not let them turn a cramped room into a brawl.") },
	["JAZZ_Legion_AssaultT2_Pillager"] = { title = T(890000000011021, "Pillager"), body = T(890000000011022, "The Legion forms Pillager teams from raiders who survived their first street fights and learned to keep moving. Light armor keeps them quick as they press close with an automatic weapon and, more often than not, a knife. Hold a long line of fire and do not chase them around a blind corner.") },
	["JAZZ_Legion_AssaultT2_Pyro"] = { title = T(890000000011023, "Pyro"), body = T(890000000011024, "Pyros are assault troops singled out for incendiary work rather than careful demolition. They wear heavy armor, carry several firebombs, and follow the flames with a submachine gun or short rifle. Spread out, stay clear of dead-end cover, and bring them down before they get within throwing distance.") },
	["JAZZ_Legion_AssaultT2_ShockTrooper"] = { title = T(890000000011025, "Shock Trooper"), body = T(890000000011026, "Shock Troopers are survivors of the early assault ranks, retrained to keep an attack moving through resistance. They open the assault with several grenades, then close in with an automatic weapon; some also carry smoke grenades or flashbangs. Do not bunch behind one wall—pin them in the open before a grenade clears their route.") },
	["JAZZ_Legion_AssaultT3_Punisher"] = { title = T(890000000011027, "Punisher"), body = T(890000000011028, "Punishers are drawn from assault veterans and trained to keep an attack moving after the first breach. Heavy armor, automatic rifles, and a full load of grenades let them press forward even when the defense holds. Engage from more than one angle, keep a second position ready, and finish one before switching targets.") },
	["JAZZ_Legion_AssaultT3_SkullCrusher"] = { title = T(890000000011029, "Skull Crusher"), body = T(890000000011030, "Skull Crushers are veteran brawlers trained to force a close fight through smoke and confusion. Heavy armor carries them into shotgun or submachine-gun range, where most of them also have a machete and some bring smoke or firebombs. Keep a clear way out of tight interiors and wear them down before they can rush.") },
	["JAZZ_Legion_AssaultT4_Headsman"] = { title = T(890000000011031, "Headsman"), body = T(890000000011032, "Only the Legion's best assault veterans are promoted to Headsman duty and equipped as elite professionals. Heavy armor, upgraded automatic weapons, and plenty of grenades let them cross ground quickly and keep attacking at close range. Make them the first target, cover more than one approach, and never leave a lone merc on their flank.") },
	["JAZZ_Legion_FlankerT1_Warden"] = { title = T(890000000011033, "Warden"), body = T(890000000011034, "Wardens are ordinary riflemen given basic scouting instruction and posted away from the main line. Their light gear helps them reach a side position, where they hold cover and punish movement with steady rifle fire. Check both flanks before advancing, and use smoke or a second angle to dislodge them.") },
	["JAZZ_Legion_FlankerT2_Scout"] = { title = T(890000000011035, "Scout"), body = T(890000000011036, "Scouts are survivors of Warden patrols who have learned to move quietly and choose their approach. They slip around the line with automatic weapons, and may use a knife or smoke once they reach the rear. Keep the flanks paired, watch covered routes, and do not chase a Scout into ground you have not cleared.") },
	["JAZZ_Legion_FlankerT2_Skirmisher"] = { title = T(890000000011037, "Skirmisher"), body = T(890000000011038, "Skirmishers are picked for marksmanship and trained to fight away from the main line. They carry light armor and battle rifles, shifting between flanking positions to fire on exposed targets. Do not follow them across open ground; move under cover or smoke and pin their position before advancing.") },
	["JAZZ_Legion_FlankerT3_Pathfinder"] = { title = T(890000000011039, "Pathfinder"), body = T(890000000011040, "Pathfinders are seasoned scouts trained to choose a concealed firing lane and hold it. Their light gear lets them reach a flank with a carbine or submachine gun, and many also carry smoke or a knife. Sweep nearby cover before moving the main group, then block their escape instead of trading shots from one position.") },
	["JAZZ_Legion_FlankerT3_Recon"] = { title = T(890000000011041, "Recon"), body = T(890000000011042, "Recon troops are veteran scouts trained for quiet approaches and night fighting. They use light gear and compact automatic weapons to close from an unseen angle, sometimes covering the move with smoke. Keep overlapping fields of fire, illuminate dark approaches, and finish them as soon as they reveal themselves.") },
	["JAZZ_Legion_FlankerT4_Ranger"] = { title = T(890000000011043, "Ranger"), body = T(890000000011044, "Rangers are elite scouts selected from the Legion's best flankers and given its finest field training. They move quickly and quietly with upgraded carbines or submachine guns, striking from the side before slipping away. Treat a Ranger as a priority target, overlap your fields of fire, and never leave one merc isolated.") },
	["JAZZ_Legion_FrontT1_Bonemaker"] = { title = T(890000000011045, "Bonemaker"), body = T(890000000011046, "A recruit who breaks from the line to reach a wounded Legionnaire is probably a Bonemaker. The Major chooses people who stay calm around blood, gives them a compact firearm, and hurries them through battlefield medicine. They break off to stop bleeding or treat other wounds. Remove the medic before pressing forward, or fighters you have already hurt will stay in the battle far longer than expected.") },
	["JAZZ_Legion_FrontT1_Marauder"] = { title = T(890000000011047, "Marauder"), body = T(890000000011048, "Looters and local toughs fill the Marauder ranks. They start with pistols and submachine guns; assault rifles appear once better supplies reach the Legion. They plug gaps in the line and rake exposed ground with fire, but pressure can pin them down before they accomplish much. Their short-range weapons punish careless movement, so return fire quickly, keep your distance, and force them to keep their heads down.") },
	["JAZZ_Legion_FrontT1_Rifleman"] = { title = T(890000000011049, "Rifleman"), body = T(890000000011050, "Most Riflemen are conscripts with a few marksmanship lessons, posted to guard roads, doorways, and village approaches. From cover, they use their rifles to watch the ground ahead and wait for a clear shot. A patient Rifleman can punish careless movement, so block his view with smoke or approach from a direction his firing position does not cover.") },
	["JAZZ_Legion_FrontT2_Ambusher"] = { title = T(890000000011051, "Ambusher"), body = T(890000000011052, "Ambushers are patient shooters taught to prepare concealed firing positions along likely approaches. From a prepared position, they wait for an exposed target and punish the first careless move with accurate rifle fire. Do not advance blindly into ground they have chosen; scout ahead, use smoke, and force them to reveal themselves early.") },
	["JAZZ_Legion_FrontT2_Marksman"] = { title = T(890000000011053, "Marksman"), body = T(890000000011054, "The best shots in regular squads are given accurate rifles and taught to wait for a clean shot. They work behind the front, hold useful ground, and let the enemy come to them rather than rushing forward. Their accuracy makes repeated peeking dangerous, so change firing points often and deny them a clear view with smoke.") },
	["JAZZ_Legion_FrontT2_Raider"] = { title = T(890000000011055, "Raider"), body = T(890000000011056, "Raiders are adaptable front-line fighters drilled with automatic weapons; every one also receives hand grenades. They move with the line, use rapid fire to cover short advances, and throw grenades when defenders settle behind cover. Rapid fire and grenades make them dangerous at close and middle range, so spread out, deny them an easy approach, and press them before they can choose where to throw.") },
	["JAZZ_Legion_FrontT3_Sniper"] = { title = T(890000000011057, "Sniper"), body = T(890000000011058, "Only the Legion's finest riflemen receive sniper training: patience, target selection, and careful use of scoped rifles. They watch open approaches from distance and begin an engagement by pinning one exposed target under accurate fire. Crossing open ground gives them an easy shot, so screen movement with smoke and hunt the Sniper before beginning a direct assault.") },
	["JAZZ_Legion_FrontT3_Veteran"] = { title = T(890000000011059, "Veteran"), body = T(890000000011060, "Veterans have survived several campaigns and stayed steady under fire. They advance stubbornly with automatic fire and grenades; a few also bring a launcher, and all keep fighting through punishment that would stop less experienced troops. Their durability and explosives punish a packed formation, so spread out, deny them a clean approach, and concentrate fire before closing in.") },
	["JAZZ_Legion_FrontT4_Mercenary"] = { title = T(890000000011061, "Mercenary"), body = T(890000000011062, "The Legion hires experienced Mercenaries to hold important positions and sends them out with good weapons. They move with the front and combine accurate rifle fire with grenades; a few also carry a launcher, and all keep fighting under pressure. They are dangerous at several ranges, so avoid a fair exchange: split their attention, deny clear shots, and overwhelm one position at a time.") },
	["JAZZ_Legion_FrontT4_MercenarySniper"] = { title = T(890000000011063, "Mercenary Sniper"), body = T(890000000011064, "Mercenary Snipers are proven specialists hired for operations where accurate long-range fire can decide the opening exchange. They begin by pinning an exposed target and use powerful scoped rifles to control open approaches from a distance. Once one is reported, do not expose yourself twice from the same place. Cover movement with smoke and pressure the shooter before committing the squad.") },
	["JAZZ_Legion_GunnerT1_Gunner"] = { title = T(890000000011065, "Gunner"), body = T(890000000011066, "The Legion hands its strongest new recruits old machine guns and gives them a hurried lesson in using them. They set up along roads and in courtyards and spray enough fire to pin anyone caught away from cover, but remain vulnerable while moving. Do not cross their field of fire in the open; use smoke, buildings, or a side approach to reach them safely.") },
	["JAZZ_Legion_GunnerT2_AssaultGunner"] = { title = T(890000000011067, "Assault Gunner"), body = T(890000000011068, "Surviving Gunners are promoted to Assault Gunner duty and taught to carry their light machine guns forward instead of guarding one position. They close the distance, set up near the fight, and pin defenders from positions that ordinary gunners would consider too exposed. Most also bring a machete for the last few steps and a firebomb to flush cover. If they reach useful firing ground the attack becomes hard to stop, so break their approach with explosives or catch them while they are moving.") },
	["JAZZ_Legion_GunnerT2_GMPG"] = { title = T(890000000011069, "GPMG"), body = T(890000000011070, "Reliable machine gunners are assigned to GPMG duty and taught to keep their fire steady without wasting ammunition. From prepared positions, they use machine-gun fire to cover roads, courtyards, and wide approaches. A frontal charge feeds their advantage; block their view with smoke, force them to move, or attack from a direction their position cannot cover.") },
	["JAZZ_Legion_GunnerT3_VeteranGunner"] = { title = T(890000000011071, "Veteran Gunner"), body = T(890000000011072, "Veteran Gunners have survived repeated engagements and are trusted with stronger machine guns. They use disciplined bursts and expert prepared fire to lock down movement, while tougher defenses let them stay effective under pressure. Their fire can stall an attack, so keep them occupied from one direction and strike quickly from another, or destroy the position with explosives.") },
	["JAZZ_Legion_GunnerT4_MercGunner"] = { title = T(890000000011073, "Merc Gunner"), body = T(890000000011074, "Merc Gunners are experienced heavy-weapon specialists hired to use the strongest machine guns available to the Legion. They combine disciplined bursts, prepared fire, and enough resilience to keep a broad approach dangerous under sustained pressure. Leaving them alone can halt an advance, so deny them a clear field of fire and destroy the gunner before committing anyone across open ground.") },
	["JAZZ_Legion_HeavyT1_Rocketeer"] = { title = T(890000000011075, "Rocketeer"), body = T(890000000011076, "Rocketeers are recruits with enough nerve to shoulder a launcher and just enough instruction to avoid hitting their own squad. They fire RPGs or disposable rockets at vehicles, walls, and clustered targets, but after a launch they need time before they can fire again. Spread out and press them immediately after a launch; one unanswered rocket can turn a defensible position into wreckage.") },
	["JAZZ_Legion_HeavyT2_Grenadier"] = { title = T(890000000011077, "Heavy Grenadier"), body = T(890000000011078, "Heavy Grenadiers already understand explosives before they are trained on RPGs and grenade launchers. They send explosive rounds into rooms, courtyards, and covered approaches, forcing anyone who survives the blast to abandon a comfortable position. Remaining in one place invites another round, so move after each shot and pressure the Heavy Grenadier before the launcher is ready again.") },
	["JAZZ_Legion_HeavyT3_Mortarman"] = { title = T(890000000011079, "Mortarman"), body = T(890000000011080, "Mortarmen are proven heavy-weapon crews trained to lob shells over walls and other obstacles. They use a portable mortar to strike positions that direct fire cannot easily reach, forcing anyone who remains still to abandon cover. Once the bombardment begins, move immediately and pressure the crew before it fires again. A wall between you and the crew will not keep you safe.") },
	["JAZZ_Legion_LeaderT1_Sergeant"] = { title = T(890000000011081, "Sergeant"), body = T(890000000011082, "When frightened recruits suddenly start moving as one, look for the loudest man among them. The Major turns dependable Legionnaires like that into Sergeants, able to push nearby troops forward, hold them in place, or focus their fire. Remove the leader early and the rest become much easier to disrupt.") },
	["JAZZ_Legion_LeaderT2_Lieutenant"] = { title = T(890000000011083, "Lieutenant"), body = T(890000000011084, "Successful Sergeants become Lieutenants and trade shouting at one group for directing several squads. Their orders reach a wider area, sending troops forward, holding them in place, moving them into cover, or focusing their fire as the situation changes. Their presence keeps a local attack coherent, so remove the officer before the Legion can regroup and turn a confused exchange into an organized assault.") },
	["JAZZ_Legion_LeaderT3_Captain"] = { title = T(890000000011085, "Captain"), body = T(890000000011086, "Captains are officers trusted to control several units at once. They issue orders across the entire Legion force, redirect the attack as conditions change, and support those commands with accurate rifle fire. Every minute a Captain remains active keeps the enemy coordinated, so identify and remove the officer before pressing the fight.") },
	["JAZZ_Legion_LeaderT4_MercenaryCaptain"] = { title = T(890000000011087, "Mercenary Captain"), body = T(890000000011088, "Mercenary Captains are experienced officers hired to command mixed troops; they need little more than local intelligence. They issue orders across the entire force, preserve discipline through casualties, and quickly change plans when the first one fails. Assume nearby units are acting with a common purpose while one survives; bring the Captain down before attacking the rest.") },
}

JAZZ_RIS_QUEST_DOSSIERS = {
	["Pierre"] = { title = T(890000000011089, "Pierre Laurent"), body = T(890000000011090, "Luc Laurent's son serves as the Legion's face on Ernie, always in a pressed uniform and with something to prove. He likes being seen as much as being obeyed, which makes him easier to read than most Legion officers. Don't mistake charm for mercy.") },
	["Bastien"] = { title = T(890000000011091, "Bastien"), body = T(890000000011092, "A local fixer with a trader's smile. He knows who controls each road, what passage costs, and whom to pay. A useful contact, but never mistake business for friendship.") },
	["TheMajor"] = { title = T(890000000011093, "The Major"), body = T(890000000011094, "The man behind the Legion built his army with fear, money, and stolen supplies, then spread it across Grand Chien. Every Legion supply report ultimately leads back to him. He is patient, ruthless, and remembers every loss.") },
	["Legion"] = { title = T(890000000011095, "Legion"), body = T(890000000011096, "The Major's army survives on stolen supplies, forced recruitment, and officers who treat villages as property. Its troops range from frightened locals to trained specialists. Wherever the Legion appears, the Major's reach is close behind.") },
}

JAZZ_RIS_AAR = {
	headlines = {
		["win|low"] = { T(890000000011097, "Favorable outcome after a brief engagement"), T(890000000011098, "Brief engagement ended in our favor"), T(890000000011099, "Limited resistance overcome") },
		["win|mid"] = { T(890000000011100, "Favorable outcome after sustained fighting"), T(890000000011101, "Sustained engagement ended in our favor"), T(890000000011102, "Resistance broken after a hard fight") },
		["win|high"] = { T(890000000011103, "Favorable outcome at heavy cost"), T(890000000011104, "Severe fighting ended in our favor"), T(890000000011105, "Victory with heavy losses") },
		["loss|low"] = { T(890000000011106, "Adverse outcome after brief resistance"), T(890000000011107, "Brief engagement ended against us"), T(890000000011108, "Limited losses despite the adverse outcome") },
		["loss|mid"] = { T(890000000011109, "Adverse outcome after sustained fighting"), T(890000000011110, "Sustained engagement ended against us"), T(890000000011111, "Enemy pressure decided the engagement") },
		["loss|high"] = { T(890000000011112, "Adverse outcome at heavy cost"), T(890000000011113, "Severe fighting ended against us"), T(890000000011114, "Heavy losses, hostile force prevailed") },
		["retreat|low"] = { T(890000000011115, "Orderly withdrawal after brief contact"), T(890000000011116, "Force withdrew after a brief engagement"), T(890000000011117, "Contact broken with limited losses") },
		["retreat|mid"] = { T(890000000011118, "Withdrawal under sustained pressure"), T(890000000011119, "Force disengaged after a hard fight"), T(890000000011120, "Withdrawal ordered to preserve the force") },
		["retreat|high"] = { T(890000000011121, "Withdrawal under heavy fire"), T(890000000011122, "Costly disengagement completed"), T(890000000011123, "Withdrawal completed after severe fighting") },
	},
	weather = {
		clear = T(890000000011124, "Final field reports indicate clear weather and good visibility."),
		rain = T(890000000011125, "Final field reports indicate rain."),
		night = T(890000000011126, "Visibility was limited by darkness."),
		fog = T(890000000011127, "Final field reports note fog and reduced visibility."),
		heat = T(890000000011128, "Final field reports note extreme heat."),
		dust = T(890000000011129, "Final field reports note a dust storm and reduced visibility."),
		default = T(890000000011130, "Final field reports identify no notable weather condition."),
	},
	intensity = {
		low = T(890000000011131, "The exchange was brief and appears to have drawn little attention outside the area."),
		mid = T(890000000011132, "Sustained fighting is likely to draw wider attention."),
		high = T(890000000011133, "The scale of the fighting will be difficult for hostile commanders to ignore."),
	},
	forces = T(890000000011134, "Across the engagement, field reports placed friendly strength at about <player> and hostile strength at about <enemy>."),
	sector = {
		line = T(890000000011135, "Engagement location: <sector>."),
		poi = T(890000000011136, "Engagement location: <sector>. Nearest reported landmark: <poi>."),
	},
	quest = {
		one = T(890000000011137, "The engagement was connected to this assignment: <quest>. One confirmed detail may matter: <note>"),
		one_nonote = T(890000000011138, "The engagement was connected to this assignment: <quest>."),
		many = T(890000000011139, "Field records connect the engagement to several active assignments: <quests>."),
		active = T(890000000011140, "The team also had this assignment: <quest>. No link to the area was confirmed."),
		none = T(890000000011141, "No active assignment was tied to this area."),
	},
	character = {
		win = T(890000000011142, "The engagement ended in your team's favor."),
		loss = T(890000000011143, "The engagement ended in the hostile force's favor."),
		retreat = T(890000000011144, "Your team broke contact and withdrew under fire."),
		ambush = T(890000000011145, "The opening pattern is consistent with an ambush; the first shots shaped the rest of the engagement."),
		quest_win = T(890000000011146, "The engagement was tied to an active assignment; the favorable outcome may support further work."),
		quest_loss = T(890000000011147, "The engagement was tied to an active assignment. The adverse outcome may complicate further work."),
		quest_retreat = T(890000000011148, "Your team withdrew from an area tied to an active assignment."),
	},
	losses = T(890000000011149, "Friendly losses — killed: <pkia>, wounded: <pwia>. Hostile losses — killed: <ekia>, wounded: <ewia>."),
	elite = {
		killed = T(890000000011150, "Confirmed killed during the engagement: <name>."),
		wounded = T(890000000011151, "Confirmed wounded during the engagement: <name>. Current condition is unknown."),
		escaped = T(890000000011152, "Confirmed withdrawal from the engagement: <name>. Further contact remains possible."),
		threat = T(890000000011153, "Confirmed still combat-capable when the engagement ended: <name>. The threat remains."),
	},
	closing = {
		quiet = T(890000000011154, "The limited scale of the engagement is unlikely to alter enemy activity by itself."),
		noise = T(890000000011155, "Reports of sustained fighting are likely to draw closer attention from hostile forces in the area."),
		disaster = T(890000000011156, "Losses on this scale are likely to draw attention from hostile commanders beyond the immediate area."),
	},
}

JAZZ_RIS_STRATEGY = {
	["RIS_MajorStrategy_Network"] = {
		email_id = "RIS_MajorStrategy_Network",
		design_id = "strategy_network",
		title = T(890000000011322, "The Major's Strategy: a network of strongpoints"),
		body = T(890000000011323, "Recent reports suggest that the Major does not run the Legion as one army. He has divided the country into districts, each centered on a fort. Patrols leave from it, battered units return to it, and money and recruits gathered from nearby settlements pass through its gates.\n\nDestroying a column is a serious loss, but it does not end the system. As long as its strongpoint remains active, the Major's men will eventually return to the roads. If you want an area to stay quiet, watch where the units go home—not only where you meet them.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Roads"] = {
		email_id = "RIS_MajorStrategy_Roads",
		design_id = "strategy_roads",
		title = T(890000000011324, "The Major's Strategy: a new flag does not close the road"),
		body = T(890000000011325, "Our observers confirm that Legion patrols continue to use familiar routes even after the ground has changed hands. They are especially willing to cross stretches where they see no permanent guard.\n\nTo the Major, a road is still his as long as his men can walk it. Taking an area and keeping it quiet are different jobs. If a route matters to you, changing the flag over it will not be enough.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Villages"] = {
		email_id = "RIS_MajorStrategy_Villages",
		design_id = "strategy_villages",
		title = T(890000000011326, "The Major's Strategy: two kinds of tribute"),
		body = T(890000000011327, "The Legion demands more than money from the villages. Collectors make their rounds for cash, while recruiters follow other routes in search of new bodies. Both travel with small escorts: their job is to bring what they gather back to the fort, not to look for a major fight.\n\nAfter each run they return to base, deliver the money or recruits, rest, and leave again. Intercepting one trip will cost the district money or manpower, but the system will continue as long as the fort controls the surrounding settlements.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Recon"] = {
		email_id = "RIS_MajorStrategy_Recon",
		design_id = "strategy_eyes",
		title = T(890000000011328, "The Major's Strategy: first, they look"),
		body = T(890000000011329, "When a district becomes unsettled, the Major does not always answer with force at once. A small party leaves the fort first—to check the roads, pick up a trail, and learn where you have stopped. If it returns empty-handed, the alarm gradually fades. If it sees you, the local commander receives coordinates instead of rumors.\n\nThe danger is not the size of the scouting party. Its real weapon is the report that tells the next unit where to go. If the scouts broke contact and headed home, assume the clock has already started.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Response"] = {
		email_id = "RIS_MajorStrategy_Response",
		design_id = "strategy_answer",
		title = T(890000000011330, "The Major's Strategy: the nearest fort answers"),
		body = T(890000000011331, "The Major leaves most urgent decisions to his local commanders. A lost position or a confirmed report prompts the nearest fort to reinforce its approaches and send men toward the threat.\n\nThis is not an endless reserve or a general offensive. The response is tied to a specific threat, and its size depends on the men and money available in that district. If a separate column is already moving your way, assume that someone has told the fort where to look.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Cargo"] = {
		email_id = "RIS_MajorStrategy_Cargo",
		design_id = "strategy_cargo",
		title = T(890000000011332, "The Major's Strategy: cargo takes the quiet road"),
		body = T(890000000011333, "Combat patrols may cross ground under your control without hesitation. Valuable cargo is handled more carefully. Convoys carrying money, diamonds, or reinforcements will try to avoid your positions whenever another route remains open.\n\nA long detour will not stop them. If every road passes under your guns, however, a new shipment may not leave at all. A patrol is prepared to risk contact; cargo looks for a route where contact never happens.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Recovery"] = {
		email_id = "RIS_MajorStrategy_Recovery",
		design_id = "strategy_wounded",
		title = T(890000000011334, "The Major's Strategy: they come back"),
		body = T(890000000011335, "A depleted Legion unit is not written off after a failed mission. When too many of its men are wounded or dead, it falls back to the nearest fort, waits for replacements, and only then returns to the road.\n\nThe quiet after a successful ambush may therefore be temporary. A familiar patrol has not vanished; it is rebuilding behind the walls. If you want to know whether a district is truly empty, keep watching the roads that lead back to the fort.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Retribution"] = {
		email_id = "RIS_MajorStrategy_Retribution",
		design_id = "strategy_red",
		title = T(890000000011336, "The Major's Strategy: retribution from headquarters"),
		body = T(890000000011337, "The nearest forts handle most threats. When losses and alarm continue to mount, however, the reports eventually reach the Major himself. A heavy column then leaves his headquarters—not to scout or guard a road, but to exact retribution.\n\nSuch deployments are rare, which is precisely why they matter. They mean the local forces were judged insufficient and the Major chose to spend his own reserve. A column this heavy points beyond the nearest fort—to the Major's own reserve.\n\n— R.I.S. Field Desk"),
	},
	["RIS_MajorStrategy_Awakening"] = {
		email_id = "RIS_MajorStrategy_Awakening",
		design_id = "strategy_sleep",
		title = T(890000000011338, "The Major's Strategy: not every district wakes at once"),
		body = T(890000000011339, "The Legion's distant forts do not all move at the same pace. Some survive on what they have for a long time: they rarely send out new units, conserve their men, and make little response to trouble. It can look like weakness or indecision, but the cause is usually simpler—the district has not yet received help from headquarters.\n\nThe first serious delivery changes that. Recruiters and fresh columns appear on the roads, and the local commander begins to act with greater confidence. If a formerly quiet district suddenly comes alive, the Major's supply line has probably reached it.\n\n— R.I.S. Field Desk"),
	},
}

JAZZ_RIS_EXTRA = {
	strategy_heading = T(890000000011340, "The Major's Strategy"),
	auto_resolve = T(890000000011341, "This account is based on remote reports; field detail remains limited."),
	legacy_title = T(890000000011342, "Archived engagement"),
	legacy_body = T(890000000011343, "An older engagement in <sector> survives only as a partial record. The available evidence is not enough to reconstruct the original field account with confidence."),
	hostiles_remain = T(890000000011344, "The immediate objective was achieved, but confirmed hostiles remained in the area when the report closed."),
	legacy_contact = T(890000000011345, "Unidentified fighter"),
	legacy_opponent = T(890000000011346, "Unidentified opponent"),
}

-- Key NPC session_ids for R.I.S. obituaries (same desk queue).
JAZZ_RIS_KEY_NPCS = {
	Pierre = true,
	Bastien = true,
	TheMajor = true,
	Spike = true,
	Faucheux = true,
	CorazonSantiago = true,
	Boss = true,
	Emma = true,
	Biff = true,
	FleatownBoss = true,
	Luigi = true,
	Baron = true,
	DiamondRedBoss = true,
}
