-- R.I.S. Phase B content banks (generated by docs/tools/_apply_ris_phase_b.py).
-- Do not hand-edit ID numbers; re-run the script.

JAZZ_RIS_KILL_THRESHOLD = 3
JAZZ_RIS_BATTLE_CAP = 20

JAZZ_RIS_UI = {
	site_title = T(890000000011000, "Recon Intelligence Services"),
	tab_bulletin = T(890000000011001, "Bulletin"),
	tab_dossiers = T(890000000011002, "Dossiers"),
	tab_reports = T(890000000011003, "Battle reports"),
	empty_bulletin = T(890000000011004, "No supply briefs on file yet. Watch your inbox — R.I.S. mails appear here after you receive them."),
	empty_dossiers = T(890000000011005, "No dossiers unlocked yet. New Legion types appear here when their R.I.S. contact note arrives."),
	empty_reports = T(890000000011006, "No battle reports yet. Finish a fight — the desk will file a summary here (no mail spam)."),
	kills_progress = T(890000000011007, "Observed kills: <count>/3"),
	dossier_locked = T(890000000011008, "(sealed — need 3 confirmed kills)"),
	section_quest = T(890000000011009, "Persons of interest"),
	section_legion = T(890000000011010, "Legion types"),
	supply_header = T(890000000011011, "Latest supply assessment"),
	mail_archive = T(890000000011012, "R.I.S. mail archive"),
}

JAZZ_RIS_DOSSIERS = {
	["JAZZ_Legion_Recruit"] = { title = T(890000000011013, "Recruit"), body = T(890000000011014, "The Major still sweeps villages for warm bodies: cheap boots, a rifle if lucky, and a week of shouted drill. Recruits freeze when the first magazine empties and bunch up like sheep in a doorway. Dangerous only in numbers — and as proof the Legion never runs out of names. Kill three and the desk will keep the file open.") },
	["JAZZ_Legion_AssaultT1_Crusher"] = { title = T(890000000011015, "Crusher"), body = T(890000000011016, "Crusher is the Major's blunt instrument for rooms and alleys: shotgun breath, shoulder through the jamb, no patience for standoffs. Kit is scrap-yard early — loud nerves, thin discipline. In CQB they dump the tube and keep walking; leave them an open door and they own the next five metres. Danger spikes once the gap closes.") },
	["JAZZ_Legion_AssaultT1_Grenadier"] = { title = T(890000000011017, "Grenadier"), body = T(890000000011018, "Assault Grenadiers learn one trick early: toss steel before they see the whites of your eyes. Drill is short; they still fumble pins under fire, but a green throw into a hallway rewrites the breach. Watch corners and stairwells — they breach with bangs, not bravado. Soft kit, hard habit of lobbing first.") },
	["JAZZ_Legion_AssaultT1_Roughneck"] = { title = T(890000000011019, "Roughneck"), body = T(890000000011020, "Roughnecks are the Major's street dogs — SMG spray, boot in the door, no map beyond the next room. Green as wet paint: they bunch, shout, and dump magazines into furniture. Still lethal in a choke point if you give them the first step. Treat them as CQB noise with teeth, not soldiers.") },
	["JAZZ_Legion_AssaultT2_Pillager"] = { title = T(890000000011021, "Pillager"), body = T(890000000011022, "Pillagers have already looted a few towns — they breach for loot and leave scorched rooms behind. Blooded enough to push through smoke instead of freezing in it. Expect aggressive CQB: flash in, take the corner, strip the dead. They still panic in stacked doorways, but they panic forward.") },
	["JAZZ_Legion_AssaultT2_Pyro"] = { title = T(890000000011023, "Pyro"), body = T(890000000011024, "Pyros bring fire into the breach — bottles, charges, anything that turns a room into a kiln. Already blooded; they enjoy the smell more than the Major admits. Deny them fuel lanes and tight interiors or your cover becomes a trap. CQB with a matchbook mentality: if they can't take the room, they burn it.") },
	["JAZZ_Legion_AssaultT2_ShockTrooper"] = { title = T(890000000011025, "Shock Trooper"), body = T(890000000011026, "Shock Troopers are the Legion's practiced breach team: stack, bang, clear. Not militia anymore — they know how to hold a door while the next man enters. Expect coordinated CQB and fewer wasted magazines. If they seize the first room, the rest of the building follows like a falling row of tiles.") },
	["JAZZ_Legion_AssaultT3_Punisher"] = { title = T(890000000011027, "Punisher"), body = T(890000000011028, "Punishers are trained killers on a short leash — breach specialists who finish rooms the Major wants quiet. Drill shows: controlled entries, grenades on timers, no souvenir hunting mid-fight. They turn CQB into a conveyor. High threat once inside; do not gift them the stairwell.") },
	["JAZZ_Legion_AssaultT3_SkullCrusher"] = { title = T(890000000011029, "Skull Crusher"), body = T(890000000011030, "Skull Crushers pair heavy close-in iron with demolition habits — doors, walls, whatever blocks the rush. Trained, not rabble: they time the boom and walk through the dust. In assault lanes they erase cover you thought was permanent. Stop them before the charge, or rewrite your map after it.") },
	["JAZZ_Legion_AssaultT4_Headsman"] = { title = T(890000000011031, "Headsman"), body = T(890000000011032, "Headsmen are paid steel — the Major's favourite breach artists. Top kit, cold timing, no wasted steps into a room. They clear buildings the way butchers clear hooks: methodical, loud only when it helps. Priority targets in any CQB; if one stacks on your door, the dossier already assumes you lose the room.") },
	["JAZZ_Legion_FlankerT1_Warden"] = { title = T(890000000011033, "Warden"), body = T(890000000011034, "Wardens haunt the edges — green scouts with itchy triggers and thin boots. They ambush runners more than they win gunfights. Ignore the map rim and they cut your retreat; watch them and they still waste a magazine into brush. Medium threat until you forget the flanks exist.") },
	["JAZZ_Legion_FlankerT2_Scout"] = { title = T(890000000011035, "Scout"), body = T(890000000011036, "Scouts have blood on the boots already — they probe, mark, and call the ambush before you see the lane. Quieter than Wardens, meaner when you cross their trail. Expect side shots into overwatch and knives for stragglers. Lose sight of the edges and the fight arrives from the wrong compass.") },
	["JAZZ_Legion_FlankerT2_Skirmisher"] = { title = T(890000000011037, "Skirmisher"), body = T(890000000011038, "Skirmishers fight the soft fight on the wing: hit, fade, hit again. Blooded enough to bait a chase into a second team. They do not hold ground — they punish anyone who leaves the centre column. Treat every empty alley as occupied until proven otherwise.") },
	["JAZZ_Legion_FlankerT3_Pathfinder"] = { title = T(890000000011039, "Pathfinder"), body = T(890000000011040, "Pathfinders are trained trail killers — they own goat paths, ditch lines, and the blind spot behind your advance. Not militia: they set lanes and wait. Ambush quality jumps; runners die before they reach the road. Clear the edges before you celebrate the centre.") },
	["JAZZ_Legion_FlankerT3_Recon"] = { title = T(890000000011041, "Recon"), body = T(890000000011042, "Recon teams feed the Major eyes — trained to count, shadow, and only shoot when the ambush is already closed. They vanish after contact and return with friends. If you feel watched on the approach, you probably are. Kill them early or fight their report later.") },
	["JAZZ_Legion_FlankerT4_Ranger"] = { title = T(890000000011043, "Ranger"), body = T(890000000011044, "Rangers are paid ghosts on the Major's favourite payroll — elite flank work with top glass and no wasted noise. They cut logistics, silence sentries, and collapse retreats. If one is on the board, assume every tree line is hostile. Priority kill: force multipliers who never stand in the middle.") },
	["JAZZ_Legion_FrontT1_Bonemaker"] = { title = T(890000000011045, "Bonemaker"), body = T(890000000011046, "Bonemakers are the Legion's field medics with rifles — they hold the line while dragging their own back up. Green kit, shaky aim, but every one you leave alive puts another Legionnaire on his feet. Overwatch around their stretchers; they punish heroic rushes more than they win duels.") },
	["JAZZ_Legion_FrontT1_Marauder"] = { title = T(890000000011047, "Marauder"), body = T(890000000011048, "Marauders fill the firing line with scavenged rifles and bad attitudes. Green, loud, and fond of spraying the lane they think is yours. They hold ground by volume more than craft. Steady threat if you stand in the open; softer if you force them to move.") },
	["JAZZ_Legion_FrontT1_Rifleman"] = { title = T(890000000011049, "Rifleman"), body = T(890000000011050, "Riflemen are the textbook green line — aimed shots when they remember to breathe, panic magazines when they don't. They overwatch doorways with more hope than skill. Still: a patient bullet from cover kills heroes. Punish mistakes harder than they punish courage.") },
	["JAZZ_Legion_FrontT2_Ambusher"] = { title = T(890000000011051, "Ambusher"), body = T(890000000011052, "Ambushers own prepared lanes on the front — blooded shooters who wait for the first man to cross a chalk line. Not runners; hunters with a static kill zone. Expect overwatch that actually bites. Probe with smoke or angles before you commit the column.") },
	["JAZZ_Legion_FrontT2_Marksman"] = { title = T(890000000011053, "Marksman"), body = T(890000000011054, "Marksmen pick officers and MG nests from the second rank — blooded enough to hold fire until the shot matters. They punish silhouettes on ridges and anyone who peeks the same window twice. Steady threat: they do not need to rush you.") },
	["JAZZ_Legion_FrontT2_Raider"] = { title = T(890000000011055, "Raider"), body = T(890000000011056, "Raiders are line troops with a habit of sudden advances — blooded soldiers who push after a volley instead of hugging dirt forever. They hold, then take the next wall. Overwatch plus short assaults: treat them as a moving front, not a static fence.") },
	["JAZZ_Legion_FrontT3_Sniper"] = { title = T(890000000011057, "Sniper"), body = T(890000000011058, "Legion snipers are trained glass — one shot, one changed plan. They pick lanes and wait; heroics across open ground are gifts. Not militia with scopes: they know when to relocate after the first kill. Clear overwatch before you stack for assault.") },
	["JAZZ_Legion_FrontT3_Veteran"] = { title = T(890000000011059, "Veteran"), body = T(890000000011060, "Veterans are the backbone of a trained Legion line — patient fire, smart overwatch, few wasted magazines. They punish mistakes and survive the ones you thought would break them. Expect grenade tricks and disciplined mutual support. Steady, ugly threat.") },
	["JAZZ_Legion_FrontT4_Mercenary"] = { title = T(890000000011061, "Mercenary"), body = T(890000000011062, "Mercenaries on the Major's payroll fight like professionals who bill by the hour — paid steel on the line. Top kit, calm overwatch, no panic dumps. They hold sectors the way contractors hold contracts. Kill them or pay later in reinforcements.") },
	["JAZZ_Legion_FrontT4_MercenarySniper"] = { title = T(890000000011063, "Mercenary Sniper"), body = T(890000000011064, "Mercenary Snipers are the Major's favourite long knives — paid glass that erases leadership and MG before the assault starts. Relocate after every shot; expect no second chance in the same window. Priority over almost everything else on the front.") },
	["JAZZ_Legion_GunnerT1_Gunner"] = { title = T(890000000011065, "Gunner"), body = T(890000000011066, "Green gunners own a lane with belts they barely know how to feed. Loud, inaccurate, still enough to pin anyone who stands tall in the open. Soft in tight rooms; brutal across courtyards. Flank them or eat suppression.") },
	["JAZZ_Legion_GunnerT2_AssaultGunner"] = { title = T(890000000011067, "Assault Gunner"), body = T(890000000011068, "Assault Gunners walk the belt forward — blooded crews who displace with the push instead of camping one sandbag forever. Suppression that moves with the breach. Open ground still favours them; rooms punish slow mounts. Deny the approach or pay in inches.") },
	["JAZZ_Legion_GunnerT2_GMPG"] = { title = T(890000000011069, "GPMG"), body = T(890000000011070, "GPMG teams are the classic blooded nest — sustained belts, interlocking lanes, patience. They deny approaches until something bigger breaks the gun. High threat across plazas; softer if you force a move under fire. Smoke and angles beat heroism.") },
	["JAZZ_Legion_GunnerT3_VeteranGunner"] = { title = T(890000000011071, "Veteran Gunner"), body = T(890000000011072, "Veteran Gunners are trained belt artists — they walk fire, save bursts, and kill the first man who thinks the lane is clear. Not militia with a bipod. Expect disciplined suppression that shapes the whole fight. Flank hard or bring boom.") },
	["JAZZ_Legion_GunnerT4_MercGunner"] = { title = T(890000000011073, "Merc Gunner"), body = T(890000000011074, "Merc Gunners are paid steel behind the best belts the Major can buy. They own open ground like contractors own a clause. Relocate under smoke, reappear on a worse angle. Priority target: one nest can freeze a whole push.") },
	["JAZZ_Legion_HeavyT1_Rocketeer"] = { title = T(890000000011075, "Rocketeer"), body = T(890000000011076, "Green rocketeers still flinch at their own backblast — and still erase a wall if the tube leaves the shoulder. Spike threat: one shot rewrites cover and morale. Soft if you catch them mid-reload; catastrophic if you stack in their sight picture. Area denial by accident and intent.") },
	["JAZZ_Legion_HeavyT2_Grenadier"] = { title = T(890000000011077, "Grenadier"), body = T(890000000011078, "Heavy Grenadiers are blooded boom specialists — tubes and launchers that carve rooms and courtyards. They shape approaches with timed blasts, not hope. Expect area denial that forces you into their gunners' lanes. Kill or displace before the second round lands.") },
	["JAZZ_Legion_HeavyT3_Mortarman"] = { title = T(890000000011079, "Mortarman"), body = T(890000000011080, "Mortarmen are trained to drop steel where you thought the sky was empty. Indirect fire turns cover into a suggestion. Not militia with a tube: they walk rounds onto a grid. Break the team or abandon the square — standing still under trained mortar is a choice, not a plan.") },
	["JAZZ_Legion_LeaderT1_Sergeant"] = { title = T(890000000011081, "Sergeant"), body = T(890000000011082, "Sergeants keep green packs pointed the same way — shouted orders, slapstick rally, enough presence to stop a rout. Soft individually; dangerous as a force multiplier. Kill the voice early and the rabble forgets why it came.") },
	["JAZZ_Legion_LeaderT2_Lieutenant"] = { title = T(890000000011083, "Lieutenant"), body = T(890000000011084, "Lieutenants are blooded mid-tier glue — they rally after the first casualties and push the pack instead of letting it melt. Expect timed advances and fewer freezes under fire. Force multiplier: remove them and the local plan collapses into noise.") },
	["JAZZ_Legion_LeaderT3_Captain"] = { title = T(890000000011085, "Captain"), body = T(890000000011086, "Captains are trained commanders who make rabble fight like a unit — fire control, mutual support, ugly competence. The Major trusts them with sectors that matter. Priority kill: every minute they live, the Legion around them gets smarter.") },
	["JAZZ_Legion_LeaderT4_MercenaryCaptain"] = { title = T(890000000011087, "Mercenary Captain"), body = T(890000000011088, "Mercenary Captains are paid steel with a radio — elite force multipliers on the Major's short list. They hold cohesion under disasters that would scatter militia. If one is present, assume the fight has a brain. Kill first; argue about medals later.") },
}

JAZZ_RIS_QUEST_DOSSIERS = {
	["Pierre"] = { title = T(890000000011089, "Pierre Laurent"), body = T(890000000011090, "Father's boy turned Legion face on Ernie — pride, pressed uniforms, and a chip on the shoulder big enough to hide a rifle behind. Useful as a weather vane for how hard the Major is leaning on the island. Treat charm as cover fire.") },
	["Bastien"] = { title = T(890000000011091, "Bastien"), body = T(890000000011092, "Local muscle with a merchant's smile. When he talks trade, listen for who really owns the road — tolls, tips, and quiet threats travel the same dirt. Desk note: useful contact, never a friend.") },
	["TheMajor"] = { title = T(890000000011093, "The Major"), body = T(890000000011094, "Not a rumor — a commander who builds an army from fear, payroll, and stolen warehouses. Every supply brief on this desk is really about him. Expect patience, cruelty, and a long memory for whoever spoils his inventory.") },
	["Legion"] = { title = T(890000000011095, "Legion (faction)"), body = T(890000000011096, "A private war machine wearing stolen legitimacy. Expect raids, pressed recruits, and officers who treat villages like inventory ledgers. The faction is the Major's shadow cast across every sector you will fight.") },
}

JAZZ_RIS_AAR = {
	headlines = {
		["loss|high"] = { T(890000000011112, "Rout — write it honestly"), T(890000000011113, "The desk calls it a disaster"), T(890000000011114, "Smoke and empty stretchers") },
		["loss|low"] = { T(890000000011106, "Forced back, light losses"), T(890000000011107, "Probe failed"), T(890000000011108, "Bad ground, worse timing") },
		["loss|mid"] = { T(890000000011109, "Beaten off the field"), T(890000000011110, "They kept the sector"), T(890000000011111, "Retreat under fire") },
		["retreat|high"] = { T(890000000011121, "Bloody extraction"), T(890000000011122, "Ran the gauntlet out"), T(890000000011123, "Survival first, pride later") },
		["retreat|low"] = { T(890000000011115, "Ordered withdrawal"), T(890000000011116, "You left before it got expensive"), T(890000000011117, "Discretion over medals") },
		["retreat|mid"] = { T(890000000011118, "Pulled out under pressure"), T(890000000011119, "Falling back to fight another day"), T(890000000011120, "The line wouldn't hold") },
		["win|high"] = { T(890000000011103, "Blood bath — and you walked out"), T(890000000011104, "The Major will hear about this"), T(890000000011105, "Thunder over the sector") },
		["win|low"] = { T(890000000011097, "Quiet clearance"), T(890000000011098, "Sector secured without fireworks"), T(890000000011099, "Low noise, clean finish") },
		["win|mid"] = { T(890000000011100, "Hard fight, held the ground"), T(890000000011101, "They pushed; you pushed back"), T(890000000011102, "Victory with bruised knuckles") },
	},
	weather = {
		clear = T(890000000011124, "Weather: clear skies over the fight."),
		rain = T(890000000011125, "Weather: rain turned powder damp and tempers shorter."),
		night = T(890000000011126, "Weather/time: night fight — muzzle flashes did the talking."),
		fog = T(890000000011127, "Weather: fog cut sightlines; everyone hugged cover."),
		heat = T(890000000011128, "Weather: baking heat — fatigue hit as hard as bullets."),
		dust = T(890000000011129, "Weather: dust storm grit in every weapon."),
		default = T(890000000011130, "Weather: unremarkable — the shooting was the story."),
	},
	intensity = {
		low = T(890000000011131, "Intensity: a sharp exchange, then quiet. Heat on the grid barely stirred."),
		mid = T(890000000011132, "Intensity: sustained fire and movement. Local Heat climbed enough for the desk to notice."),
		high = T(890000000011133, "Intensity: a meat grinder. Expect the Major's network to smell the smoke."),
	},
	forces = T(890000000011134, "Forces: roughly <player> friendlies against <enemy> hostiles at contact."),
	sector = {
		line = T(890000000011135, "Theatre: <sector>."),
		poi = T(890000000011136, "Theatre: <sector> — local label <poi>."),
	},
	quest = {
		one = T(890000000011137, "Operational thread: <quest>. Desk note on this grid: <note>"),
		one_nonote = T(890000000011138, "Operational thread: <quest> — badges pin this fight to that job."),
		many = T(890000000011139, "Operational threads on this sector: <quests>. Treat the shooting as part of those jobs, not random noise."),
		active = T(890000000011140, "Active desk job (not sector-badged): <quest>."),
		none = T(890000000011141, "No live quest badge on this grid — logged as a free-fire sector action."),
	},
	character = {
		win = T(890000000011142, "Character: your side held the field."),
		loss = T(890000000011143, "Character: the enemy kept the sector."),
		retreat = T(890000000011144, "Character: fighting withdrawal — not a stand."),
		ambush = T(890000000011145, "Character: smelled like an ambush — first shots decided the map."),
		quest_win = T(890000000011146, "Character: quest-linked fight — objective pressure held; the sector stayed yours."),
		quest_loss = T(890000000011147, "Character: quest-linked fight — the job on this grid just got harder."),
		quest_retreat = T(890000000011148, "Character: quest-linked withdrawal — you left the badge sector under protest."),
	},
	losses = T(890000000011149, "Losses: friendlies KIA <pkia>, WIA <pwia>; hostiles KIA <ekia>, WIA <ewia>."),
	elite = {
		killed = T(890000000011150, "<name> went down in the fight — one less elite name on the Major's roster."),
		wounded = T(890000000011151, "<name> left the field bleeding. If they live, they'll remember your faces."),
		escaped = T(890000000011152, "<name> slipped the net. Expect that name again."),
		threat = T(890000000011153, "<name> was still standing when the shooting stopped — unfinished business."),
	},
	closing = {
		quiet = T(890000000011154, "Closing: the sector goes quiet; Heat footprint looks manageable."),
		noise = T(890000000011155, "Closing: the noise will travel — patrols and payoffs usually follow."),
		disaster = T(890000000011156, "Closing: write this one in red. Command will ask hard questions."),
	},
}

-- Key NPC session_ids for R.I.S. obituaries (same desk queue).
JAZZ_RIS_KEY_NPCS = {
	Pierre = true,
	Bastien = true,
	TheMajor = true,
	Spike = true,
	Faucheux = true,
	CorazonSantiago = true,
	Boss = true,
	Emma = true,
	Biff = true,
	FleatownBoss = true,
	Luigi = true,
	Baron = true,
	DiamondRedBoss = true,
}
