UndefineClass('Galil_FlagHill')
DefineClass.Galil_FlagHill = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Vanilla unique — The Hired Gun; JAZZ caliber/attacks",
	object_class = "BattleRifle",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/Galil_Flaghill",
	DisplayName = T(167758773926, --[[ModItemInventoryItemCompositeDef Galil_FlagHill DisplayName]] "The Hired Gun"),
	DisplayNamePlural = T(887498877657, --[[ModItemInventoryItemCompositeDef Galil_FlagHill DisplayNamePlural]] "The Hired Guns"),
	Description = T(503430285250, --[[ModItemInventoryItemCompositeDef Galil_FlagHill Description]] "Mercenary contract termination tool."),
	AdditionalHint = T(112848820358, --[[ModItemInventoryItemCompositeDef Galil_FlagHill AdditionalHint]] "<bullet_point> Awesome Crit chance\n<bullet_point> Longer range"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 8000,
	RestockWeight = 0,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 34,
	ObjDamageMod = 80,
	AimAccuracy = 14,
	CritChanceScaled = 50,
	MagazineSize = 25,
	WeaponRange = 58,
	OverwatchAngle = 960,
	Noise = 62,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Galil",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"MuzzleBooster",
				"Galil_Brake_Default",
				"Compensator",
				"Suppressor",
			},
			'DefaultComponent', "MuzzleBooster",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod_Galil",
			},
			'DefaultComponent', "Bipod_Galil",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'Modifiable', false,
			'AvailableComponents', {
				"ReflexSightAdvanced",
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Eotech",
				"JAZZ_CombatScope_ACOG",
			},
			'DefaultComponent', "ReflexSightAdvanced",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_25_40",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_Salvo",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 6000,
	ReloadAP = 7000,
	Recoil = 30,
	AutoShots = 6,
	Handling = -18,
	BulletDropRange = 18,
	Grouping = 58,
	WeaponResource = 9000,
}
