UndefineClass('LionRoar')
DefineClass.LionRoar = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Vanilla unique — The Lion's Roar; JAZZ caliber/attacks",
	object_class = "SubmachineGun",
	ScrapParts = 10,
	RepairCost = 8,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/LionRoar",
	DisplayName = T(755592839679, --[[ModItemInventoryItemCompositeDef LionRoar DisplayName]] "The Lion's Roar"),
	DisplayNamePlural = T(357764743328, --[[ModItemInventoryItemCompositeDef LionRoar DisplayNamePlural]] "The Lion's Roar"),
	Description = T(216467415261, --[[ModItemInventoryItemCompositeDef LionRoar Description]] "Imperialists cower before its voice!"),
	AdditionalHint = T(251066241512, --[[ModItemInventoryItemCompositeDef LionRoar AdditionalHint]] "<bullet_point> OUR weapon\n<bullet_point> Shorter range\n<bullet_point> High Damage\n<bullet_point> Limited ammo capacity\n<bullet_point> Increased bonus from Aiming\n<bullet_point> Very noisy"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 6000,
	RestockWeight = 0,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 28,
	ObjDamageMod = 30,
	AimAccuracy = 10,
	MagazineSize = 20,
	WeaponRange = 22,
	PointBlankBonus = 1,
	OverwatchAngle = 3600,
	Noise = 45,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Uzi_LionsRoar",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_Compensator_cosmetic",
				"Compensator",
				"PistolSuppressor",
			},
			'DefaultComponent', "JAZZ_Compensator_cosmetic",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"DualShot",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	WeaponMass = 32,
	CyclicRPM = 900,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	BurstShots = 4,
	Recoil = 18,
	AutoShots = 9,
	BulletDropRange = 9,
	Grouping = 45,
	WeaponResource = 5000,
}
