UndefineClass('Winchester_Quest')
DefineClass.Winchester_Quest = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Vanilla unique — Confidante; JAZZ caliber/attacks",
	object_class = "Carbine",
	ScrapParts = 8,
	RepairCost = 5,
	Reliability = 95,
	Icon = "UI/Icons/Weapons/Winchester",
	DisplayName = T(296944207700, --[[ModItemInventoryItemCompositeDef Winchester_Quest DisplayName]] "Confidante"),
	DisplayNamePlural = T(811919268698, --[[ModItemInventoryItemCompositeDef Winchester_Quest DisplayNamePlural]] "Confidante"),
	Description = T(784492395256, --[[ModItemInventoryItemCompositeDef Winchester_Quest Description]] "Reward for keeping a secret that is used for secret keeping."),
	AdditionalHint = T(111789233685, --[[ModItemInventoryItemCompositeDef Winchester_Quest AdditionalHint]] "<bullet_point> Backstabby and Silent\n<bullet_point> High Crit chance\n<bullet_point> Very low attack costs\n<bullet_point> Short range\n<bullet_point> Limited ammo capacity"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 4000,
	RestockWeight = 0,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_44CAL",
	Damage = 44,
	ObjDamageMod = 50,
	AimAccuracy = 14,
	CritChanceScaled = 45,
	MagazineSize = 4,
	WeaponRange = 24,
	OverwatchAngle = 900,
	Noise = 0,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Winchester",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"ImprovedIronsight",
				"JAZZ_Reflex_Closed",
				"JAZZ_CombatScope_2x",
			},
			'DefaultComponent', "ImprovedIronsight",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
		"JAZZ_Bullseye",
	},
	ShootAP = 4000,
	ReloadAP = 6000,
	BurstShots = 0,
	ReloadStyle = "Tube",
	WeaponMass = 35,
	CyclicRPM = 0,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 12,
	AutoShots = 0,
	BulletDropRange = 9,
	Grouping = 88,
	BaseJamChance = -100,
	WeaponResource = 4500,
}
