UndefineClass('AA12')
DefineClass.AA12 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T3+",
	object_class = "Shotgun",
	ScrapParts = 12,
	RepairCost = 50,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/AA12.png",
	DisplayName = T(656100217021, --[[ModItemInventoryItemCompositeDef AA12 DisplayName]] "AA12"),
	DisplayNamePlural = T(574054810515, --[[ModItemInventoryItemCompositeDef AA12 DisplayNamePlural]] "AA12"),
	Description = T(690637430437, --[[ModItemInventoryItemCompositeDef AA12 Description]] "АА12 со своим свободным затвором больше похож на пистолет-пулемет, чем на классический дробовик. Ценится за способность вести продолжительную стрельбу благодаря довольно низкой для 12-го калибра отдаче."),
	AdditionalHint = T(533009920041, --[[ModItemInventoryItemCompositeDef AA12 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Автоматический - низкие затраты од на выстрел"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 75000,
	CanAppearInShop = true,
	Tier = 3,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 504,
	AimAccuracy = 13,
	MagazineSize = 15,
	WeaponRange = 23,
	PointBlankBonus = 1,
	OverwatchAngle = 960,
	BuckshotConeAngle = 240,
	BuckshotFalloffDamage = 5,
	HandSlot = "TwoHanded",
	Entity = "Weapon_AA12",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelLongShotgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight_aa12",
				"LaserDot_aa12",
				"FlashlightDot_aa12",
				"UVDot_aa12",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
				"Compensator",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"Buckshot",
		"CancelShot",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 73,
	BulletDropRange = 8,
	Grouping = 150,
	CanAppearUsed = false,
}

