UndefineClass('AA12')
DefineClass.AA12 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-3",
	object_class = "Shotgun",
	ScrapParts = 12,
	RepairCost = 20,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/AA12.png",
	DisplayName = T(845020864842, --[[ModItemInventoryItemCompositeDef AA12 DisplayName]] "AA12"),
	DisplayNamePlural = T(738216506503, --[[ModItemInventoryItemCompositeDef AA12 DisplayNamePlural]] "AA12s"),
	Description = T(553979887379, --[[ModItemInventoryItemCompositeDef AA12 Description]] "Firing from an open bolt, the AA12 has more similarity with some machine guns than with other shotguns. Boasting reduced recoil for a 12-gauge round, it is made for sustained fire."),
	AdditionalHint = T(533009920041, --[[ModItemInventoryItemCompositeDef AA12 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дробовик \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Большой магазин \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный бой \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстро стреляет"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 75000,
	CanAppearInShop = true,
	Tier = 3,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 504,
	AimAccuracy = 10,
	MagazineSize = 15,
	WeaponRange = 23,
	PointBlankBonus = 1,
	OverwatchAngle = 960,
	BuckshotConeAngle = 240,
	BuckshotProjectiles = 1,
	BuckshotFalloffDamage = 5,
	Noise = 29,
	HandSlot = "TwoHanded",
	Entity = "Weapon_AA12",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelLongShotgun",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_25_AA12",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight_aa12",
				"JAZZ_LaserDot_aa12",
				"JAZZ_FlashlightDot_aa12",
				"JAZZ_UVDot_aa12",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Suppressor",
				"JAZZ_Compensator",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"Buckshot",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 4000,
	ReloadAP = 6000,
	BurstShots = 0,
	WeaponMass = 36,
	CyclicRPM = 0,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 25,
	AutoShots = 0,

	CloseRange = 4,

	CloseRangeFactor = 90,
	BulletDropRange = 8,
	Grouping = 150,
	WeaponResource = 2200,
	CanAppearUsed = false,
}

