UndefineClass('AA52')
DefineClass.AA52 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "MachineGun",
	ScrapParts = 12,
	RepairCost = 2,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/AA52.png",
	DisplayName = T(973194681593, --[[ModItemInventoryItemCompositeDef AA52 DisplayName]] "AA-52"),
	DisplayNamePlural = T(457155447326, --[[ModItemInventoryItemCompositeDef AA52 DisplayNamePlural]] "AA-52"),
	Description = T(968512989346, --[[ModItemInventoryItemCompositeDef AA52 Description]] "Французы - люди с выдумкой. Вот есть Мг34/42 - замечательный пулемет, тоже с полусвободным затвором. Ну возьми. Вы же тоже победили, возьми. Не, придумаем свой полусвободный затвор, с преферансом и куртизанками. В итоге получилось... ну такое. В приличном обществе такого единого пулемета бы не поняли."),
	AdditionalHint = T(881416264419, --[[ModItemInventoryItemCompositeDef AA52 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ручной пулемет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Скорострельный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 3000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_75French",
	Damage = 32,
	ObjDamageMod = 90,
	AimAccuracy = 12,
	MagazineSize = 50,
	WeaponRange = 52,
	OverwatchAngle = 600,
	Noise = 68,
	HandSlot = "TwoHanded",
	Entity = "AA52",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
		"JAZZ_MGSuppressionFire",
	},
	ShootAP = 9000,
	ReloadAP = 9000,
	Recoil = 21,
	BurstShots = 6,
	AutoShots = 6,
	Handling = -30,
	BulletDropRange = 21,
	Grouping = 38,
	BaseJamChance = -5,
	WeaponResource = 15000,
}

