UndefineClass('AEK971')
DefineClass.AEK971 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	BurstShots = 5,
	comment = "Tier 3-2",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 10,
	Reliability = 90,
	Icon = "Mod/e6L4ECj/WeaponIcons/AEK971.png",
	DisplayName = T(890000000032101, "АЕК-971"),
	DisplayNamePlural = T(890000000032102, "АЕК-971"),
	Description = T(890000000032103, "Автомат со сбалансированной автоматикой. Комплект АЕК-973С меняет калибр с 5,45×39 на 7,62×39 мм. Штатный магазин на 30 патронов, складной приклад."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 22000,
	CanAppearInShop = true,
	Tier = 4,
	MaxStock = 1,
	RestockWeight = 25,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_545",
	Damage = 26,
	ObjDamageMod = 45,
	AimAccuracy = 12,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 50,
	OverwatchAngle = 1320,
	Noise = 49,
	HandSlot = "TwoHanded",
	Entity = "JAZZ_AEK971",
	fxClass = "AK74",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_AEK_545",
				"JAZZ_AEK_762",
			},
			'DefaultComponent', "JAZZ_AEK_545",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
			PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
			},
		}),
},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 13,
	AutoShots = 9,
	WeaponMass = 33,
	CyclicRPM = 900,
	CloseRange = 8,
	CloseRangeFactor = 85,
	BulletDropRange = 16,
	Grouping = 58,
	BaseJamChance = -50,
	WeaponResource = 8000,
}
