UndefineClass('Agram2000')
DefineClass.Agram2000 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 3,
	Reliability = 30,
	Icon = "Mod/e6L4ECj/WeaponIcons/Agram2.png",
	DisplayName = T(137299864819, --[[ModItemInventoryItemCompositeDef Agram2000 DisplayName]] "Аграм 2000"),
	DisplayNamePlural = T(725666862361, --[[ModItemInventoryItemCompositeDef Agram2000 DisplayNamePlural]] "Аграмы 2000"),
	Description = T(374432194142, --[[ModItemInventoryItemCompositeDef Agram2000 Description]] 'Хорватский автомат Аграм 2000 был разработан в 1990-х годах и активно применялся при дроблении на части Югославии. О "нечестной" направленности автомата говорит отсутствие приклада и заложенная в конструкцию интеграция съемного глушителя. Несколько этих автоматов без номеров и регистрационных документов расползлось по миру и до сих пор активно используются криминальными элементами.'),
	AdditionalHint = T(259441942196, --[[ModItemInventoryItemCompositeDef Agram2000 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный вблизи \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Без приклада \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Скорострельный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ненадежный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2800,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 5,
	RestockWeight = 85,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 22,
	ObjDamageMod = 20,
	CritChanceScaled = 20,
	AimAccuracy = 8,
	MagazineSize = 32,
	WeaponRange = 20,
	OverwatchAngle = 4680,
	Noise = 28,
	Entity = "Agram2000",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_PistolSuppressor",
			},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	WeaponMass = 22,
	CyclicRPM = 800,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	MaxAimActions = 2,
	Recoil = 16,
	BurstShots = 4,
	AutoShots = 8,

	CloseRange = 0,

	CloseRangeFactor = 115,
	BulletDropRange = 9,
	Grouping = 82,
	BaseJamChance = -10,
	WeaponResource = 1500,
}

