UndefineClass('AK103')
DefineClass.AK103 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 7,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/AK103.png",
	DisplayName = T(761915304101, --[[ModItemInventoryItemCompositeDef AK103 DisplayName]] "АК-103"),
	DisplayNamePlural = T(761915304102, --[[ModItemInventoryItemCompositeDef AK103 DisplayNamePlural]] "АК-103"),
	Description = T(761915304103, --[[ModItemInventoryItemCompositeDef AK103 Description]] "Автомат сотой серии под патрон 7,62x39 мм с полимерным складным прикладом. Использует общие магазины АКМ на 30, 40 и 75 патронов."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 15000,
	CanAppearInShop = true,
	Tier = 4,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x39",
	Damage = 29,
	ObjDamageMod = 50,
	AimAccuracy = 11,
	MagazineSize = 30,
	WeaponRange = 42,
	OverwatchAngle = 1320,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "AKR_AK103",
	fxClass = "AKM",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GP25",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_30_40",
				"JAZZ_MagDrum_30_75",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_Handguard",
			},
			'DefaultComponent', "JAZZ_Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_PKAS",
				"JAZZ_Reflex_Cobra",
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_1P29",
				"JAZZ_Scope_PSO",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_Scout",
				"JAZZ_NightScope",
				"JAZZ_NightScope_NSPU",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_DefMuzzle",
				"JAZZ_Compensator",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
			'DefaultComponent', "JAZZ_DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 24,
	AutoShots = 6,
	WeaponMass = 34,
	CyclicRPM = 600,
	CloseRange = 8,
	CloseRangeFactor = 85,
	BulletDropRange = 15,
	Grouping = 64,
	BaseJamChance = -50,
	WeaponResource = 10000,
}

