UndefineClass('AK74M')
DefineClass.AK74M = {
	MaxStock = 1,
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 10,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/AK74M.png",
	DisplayName = T(761915303101, "АК-74М"),
	DisplayNamePlural = T(761915303102, "АК-74М"),
	Description = T(761915303103, "Автомат под патрон 5,45x39 мм с полимерным складным прикладом и общими магазинами семейства АК на 30 и 45 патронов."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 16000,
	CanAppearInShop = true,
	Tier = 4,
	RestockWeight = 45,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_545",
	Damage = 26,
	ObjDamageMod = 45,
	AimAccuracy = 12,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 50,
	OverwatchAngle = 1320,
	Noise = 49,
	HandSlot = "TwoHanded",
	Entity = "AKR_AK74M",
	fxClass = "AK74",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', { 'SlotType', "Stock", 'AvailableComponents', { "JAZZ_StockLightUnFolded", "JAZZ_StockLightFolded" }, 'DefaultComponent', "JAZZ_StockLightUnFolded" }),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_Handguard",
			},
			'DefaultComponent', "JAZZ_Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagQuick_AK",
				"JAZZ_MagLarge_30_45",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GP25",
			},
		}),
		PlaceObj('WeaponComponentSlot', { 'SlotType', "Muzzle", 'AvailableComponents', { "JAZZ_DefMuzzle", "JAZZ_Compensator", "JAZZ_Suppressor" }, 'DefaultComponent', "JAZZ_DefMuzzle" }),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Scope_PSO",
				"JAZZ_Reflex_Cobra",
				"JAZZ_Reflex_PKAS",
				"JAZZ_CombatScope_1P29",
				"JAZZ_NightScope_NSPU",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	WeaponMass = 36,
	CyclicRPM = 600,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	BurstShots = 3,
	Recoil = 15,
	AutoShots = 6,

	CloseRange = 8,

	CloseRangeFactor = 85,
	BulletDropRange = 16,
	Grouping = 58,
	BaseJamChance = -50,
	WeaponResource = 10000,
}

