UndefineClass('AKM')
DefineClass.AKM = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 7,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/AKM.png",
	DisplayName = T(257808768357, "AKM"),
	DisplayNamePlural = T(722956910106, "AKM"),
	Description = T(608879436685, "Второе поколение автоматов Калашникова с максимально обкатанной и оптимизированной технологией производства. Именно этот автомат стал символом освобождения мирового пролетариата от мирового империализма."),
	AdditionalHint = T(350741631140, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая надежность\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможности модификаций"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5200,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x39",
	Damage = 27,
	ObjDamageMod = 50,
	AimAccuracy = 22,
	CritChance = 5,
	MagazineSize = 30,
	WeaponRange = 39,
	OverwatchAngle = 1320,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "AKM",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GP25",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_30_40",
				"MagDrum_30-75",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"Handguard",
			},
			'DefaultComponent', "Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_PKAS",
				"JAZZ_Reflex_Cobra",
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_1P29",
				"JAZZ_Scope_PSO",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_Scout",
				"JAZZ_NightScope",
				"JAZZ_NightScope_NSPU",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	Recoil = 15,
	AutoShots = 6,
	Handling = 61,
	BulletDropRange = 14,
	Grouping = 250,
	BaseJamChance = -50,
	WeaponResource = 10000,
}

