UndefineClass('AN94')
DefineClass.AN94 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-UNIQ",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 20,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/AN94.png",
	DisplayName = T(984198719423, --[[ModItemInventoryItemCompositeDef AN94 DisplayName]] "АН-94"),
	DisplayNamePlural = T(109738952074, --[[ModItemInventoryItemCompositeDef AN94 DisplayNamePlural]] "АН-94"),
	Description = T(771749268124, --[[ModItemInventoryItemCompositeDef AN94 Description]] 'При помощи лафетной системы или системы "смещенного по времени импульса отдачи" достигается максимальная кучность стрельбы из автомата Никонова очередью в два патрона с темпом 1800 выстрелов/мин, при стрельбе из неустойчивых положений. В голове не укладывается, что Никонов по-настоящему прошел начатый еще в СССР конкурс и был принят на вооружение, чего, прямо скажем, не способен сделать ни один из автоматов НАТО.'),
	AdditionalHint = T(474207434755, --[[ModItemInventoryItemCompositeDef AN94 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Лупит двойками в одну точку \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Прошел советский оружейный конкурс \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Шедевр оружейной мысли"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 300000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_545",
	Damage = 27,
	ObjDamageMod = 45,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 30,
	WeaponRange = 49,
	OverwatchAngle = 1200,
	Noise = 49,
	HandSlot = "TwoHanded",
	Entity = "AN94",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_30_45",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Scope_PSO",
				"JAZZ_Reflex_Cobra",
				"JAZZ_Reflex_PKAS",
				"JAZZ_CombatScope_1P29",
				"JAZZ_NightScope_NSPU",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"Compensator",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"AbakanBurst",
		"AbakanAutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 5,
	BurstShots = 2,
	AutoShots = 6,
	Handling = -5,
	BulletDropRange = 18,
	Grouping = 56,
	BaseJamChance = -20,
	WeaponResource = 8800,
}

