UndefineClass('AR10')
DefineClass.AR10 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 10,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/AR10.png",
	DisplayName = T(114038317284, "AR-10"),
	DisplayNamePlural = T(493280640968, "AR-10"),
	Description = T(545373411773, 'AR-10 - Оригинальная разработка Юджина Стоунера, в свое время не успела попасть на "раздачу слонов" и проиграла в конкурсе винтовке М14, но вернулась уже в уменьшенном виде под малоимпульсный патрон как М16. В наше время же активно выпускается разными фирмами для полиции и граждан.'),
	AdditionalHint = T(916714653024, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность при стрельбе навскидку\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ужасная точность при стрельбе очередями"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 6750,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 32,
	ObjDamageMod = 80,
	AimAccuracy = 26,
	MagazineSize = 20,
	WeaponRange = 54,
	OverwatchAngle = 960,
	Noise = 58,
	HandSlot = "TwoHanded",
	Entity = "AR10_Auto",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_3x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 32,
	AutoShots = 7,
	Handling = 50,
	BulletDropRange = 20,
	Grouping = 278,
	BaseJamChance = -10,
	WeaponResource = 6000,
}

