UndefineClass('AR10DMR')
DefineClass.AR10DMR = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "SniperRifle",
	ScrapParts = 10,
	RepairCost = 18,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/AR10DMR.png",
	DisplayName = T(888757996394, --[[ModItemInventoryItemCompositeDef AR10DMR DisplayName]] "AR-10 DMR"),
	DisplayNamePlural = T(115079764307, --[[ModItemInventoryItemCompositeDef AR10DMR DisplayNamePlural]] "AR-10 DMR"),
	Description = T(607249083318, --[[ModItemInventoryItemCompositeDef AR10DMR Description]] 'AR-10 DMR - В принципе, "арка под триста восьмой" неплохо показывает себя в плане точности и пробития на основных боевых дистанциях. УСМ с фулл-авто скорее даже лишнее, она и одиночными гвоздит нормально. Патроны целее будут.'),
	AdditionalHint = T(884046560996, --[[ModItemInventoryItemCompositeDef AR10DMR AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Средней точности \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Среднего удобства \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Средней надежности\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  Арка с прицелом"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 14750,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 32,
	ObjDamageMod = 80,
	AimAccuracy = 15,
	CritChanceScaled = 30,
	MagazineSize = 20,
	WeaponRange = 58,
	OverwatchAngle = 900,
	Noise = 58,
	HandSlot = "TwoHanded",
	Entity = "AR_10_DMR",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"DefaultIronsight_AR15",
			},
			'DefaultComponent', "JAZZ_Scope_6x",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 32,
	BurstShots = 1,
	AutoShots = 1,
	Handling = -18,
	BulletDropRange = 18,
	Grouping = 59,
	BaseJamChance = -10,
	WeaponResource = 5000,
}

