UndefineClass('ArcticWarfare')
DefineClass.ArcticWarfare = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T2+",
	object_class = "SniperRifle",
	ScrapParts = 14,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/AWM.png",
	DisplayName = T(472965483218, --[[ModItemInventoryItemCompositeDef ArcticWarfare DisplayName]] "Arctic Warfare"),
	DisplayNamePlural = T(422903365513, --[[ModItemInventoryItemCompositeDef ArcticWarfare DisplayNamePlural]] "Arctic Warfare"),
	Description = T(117258068384, --[[ModItemInventoryItemCompositeDef ArcticWarfare Description]] "Винтовки Arctic Warware от Accuracy International были разработаны специально для армии Швеции с учетом условий сурового северного климата. Вслед за шведами эти винтовки заслуженно заняли оружейный многих армейских и гражданских силовых структур по всему миру и надолго задали моду на НАСТОЯЩУЮ снайперскую винтовку."),
	AdditionalHint = T(336224477372, --[[ModItemInventoryItemCompositeDef ArcticWarfare AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Продольно-скользящий затвор - высокие затраты ОД на выстрел\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Выскоая дальность и точность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 65000,
	CanAppearInShop = true,
	Tier = 3,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 37,
	ObjDamageMod = 80,
	AimAccuracy = 32,
	CritChanceScaled = 40,
	MagazineSize = 5,
	WeaponRange = 73,
	OverwatchAngle = 360,
	Noise = 80,
	HandSlot = "TwoHanded",
	Entity = "AWM",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_Scope_12x",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	MaxAimActions = 4,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 43,
	BulletDropRange = 24,
	Grouping = 500,
	BaseJamChance = -30,
}

