UndefineClass('ArcticWarfare')
DefineClass.ArcticWarfare = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "SniperRifle",
	ScrapParts = 14,
	RepairCost = 20,
	Reliability = 90,
	Icon = "Mod/e6L4ECj/WeaponIcons/AWM.png",
	DisplayName = T(472965483218, --[[ModItemInventoryItemCompositeDef ArcticWarfare DisplayName]] "Arctic Warfare"),
	DisplayNamePlural = T(422903365513, --[[ModItemInventoryItemCompositeDef ArcticWarfare DisplayNamePlural]] "Arctic Warfare"),
	Description = T(117258068384, --[[ModItemInventoryItemCompositeDef ArcticWarfare Description]] "Винтовки Arctic Warware от Accuracy International были разработаны специально для армии Швеции с учетом условий сурового северного климата. Вслед за шведами эти винтовки заслуженно заняли оружейный многих армейских и гражданских силовых структур по всему миру и надолго задали моду на НАСТОЯЩУЮ снайперскую винтовку."),
	AdditionalHint = T(336224477372, --[[ModItemInventoryItemCompositeDef ArcticWarfare AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Винтовка с ручным перезаряжанием \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Раздача слонов"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 65000,
	CanAppearInShop = true,
	Tier = 3,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 38,
	ObjDamageMod = 80,
	AimAccuracy = 20,
	CritChanceScaled = 50,
	MagazineSize = 5,
	WeaponRange = 95,
	OverwatchAngle = 420,
	Noise = 56,
	HandSlot = "TwoHanded",
	Entity = "AWM",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_Scope_Scout",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 8000,
	ReloadAP = 7000,
	BurstShots = 0,
	WeaponMass = 55,
	CyclicRPM = 0,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	Recoil = 22,
	AutoShots = 0,

	CloseRange = 12,

	CloseRangeFactor = 70,
	BulletDropRange = 21,
	Grouping = 42,
	BaseJamChance = -30,
	WeaponResource = 7000,
}

