UndefineClass('AS_Val')
DefineClass.AS_Val = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-3",
	object_class = "Carbine",
	ScrapParts = 10,
	RepairCost = 30,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/ASVAL.png",
	DisplayName = T(262214168219, --[[ModItemInventoryItemCompositeDef AS_Val DisplayName]] "АС-ВАЛ"),
	DisplayNamePlural = T(590065014153, --[[ModItemInventoryItemCompositeDef AS_Val DisplayNamePlural]] "АС-ВАЛ"),
	Description = T(411194291005, --[[ModItemInventoryItemCompositeDef AS_Val Description]] "Оружие, не имеющее аналогов в мире, или, по крайней мере не имевшее их до распространения патрона .300 Blackout. Да и на сегодняшний день является лучшим специальным автоматом подобного типа."),
	AdditionalHint = T(139973629199, --[[ModItemInventoryItemCompositeDef AS_Val AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Может стрелять очередями \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бесшумный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая убойность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 80000,
	CanAppearInShop = true,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_9x39",
	Damage = 30,
	ObjDamageMod = 50,
	AimAccuracy = 11,
	CritChanceScaled = 30,
	MagazineSize = 10,
	WeaponRange = 32,
	OverwatchAngle = 1500,
	Noise = 5,
	HandSlot = "TwoHanded",
	Entity = "ASVal",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_10_20",
			},
			'DefaultComponent', "MagLarge_10_20",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"SuppressorIntegrated",
			},
			'DefaultComponent', "SuppressorIntegrated",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Reflex_Cobra",
				"JAZZ_Reflex_PKAS",
				"JAZZ_Scope_PSO",
				"JAZZ_CombatScope_1P29",
				"JAZZ_NightScope_NSPU",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
		"RunAndGun",
	},
	ShootAP = 4000,
	ReloadAP = 6000,
	Recoil = 8,
	BurstShots = 4,
	AutoShots = 9,
	Handling = -2,
	BulletDropRange = 12,
	Grouping = 63,
	BaseJamChance = -30,
	WeaponResource = 3000,
}

