UndefineClass('Auto5_quest')
DefineClass.Auto5_quest = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Vanilla unique — Ma Baxter; JAZZ caliber/attacks",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 8,
	Reliability = 55,
	Icon = "UI/Icons/Weapons/Auto5Quest",
	ItemType = "Shotgun",
	DisplayName = T(104957685912, --[[ModItemInventoryItemCompositeDef Auto5_quest DisplayName]] "Ma Baxter's Argument Invalidator"),
	DisplayNamePlural = T(319145443336, --[[ModItemInventoryItemCompositeDef Auto5_quest DisplayNamePlural]] "Ma Baxter's Argument Invalidators"),
	Description = T(918826814712, --[[ModItemInventoryItemCompositeDef Auto5_quest Description]] "The legendary owner of the bar in Port Cacao used this custom Auto-5 shotgun to end bar fights in the most final way possible."),
	AdditionalHint = T(269691251565, --[[ModItemInventoryItemCompositeDef Auto5_quest AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстрое усмирение"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 4500,
	RestockWeight = 0,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 5,
	ObjDamageMod = 150,
	AimAccuracy = 6,
	MagazineSize = 9,
	PointBlankBonus = 1,
	OverwatchAngle = 1600,
	BuckshotConeAngle = 360,
	BuckshotFalloffDamage = 40,
	Noise = 40,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Auto5",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_DuckbillChoke",
				"JAZZ_FullChoke",
				"JAZZ_Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_Auto5_Basic_LMag",
				"JAZZ_Auto5_Basic_NMag",
				"JAZZ_Auto5_Long_LMag",
				"JAZZ_Auto5_Long_NMag",
				"JAZZ_Auto5_Short_NMag",
			},
			'DefaultComponent', "JAZZ_Auto5_Basic_LMag",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"BuckshotBurst",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	MaxAimActions = 2,
	Recoil = 25,
	BurstShots = 0,
	AutoShots = 0,
	WeaponMass = 36,
	CloseRange = 5,
	CloseRangeFactor = 90,
	BulletDropRange = 6,
	Grouping = 90,
	WeaponResource = 2500,
}

