UndefineClass('Auto5')
DefineClass.Auto5 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 4,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/AUTO5.png",
	DisplayName = T(740056065333, --[[ModItemInventoryItemCompositeDef Auto5 DisplayName]] "Auto-5"),
	DisplayNamePlural = T(710804607957, --[[ModItemInventoryItemCompositeDef Auto5 DisplayNamePlural]] "Auto-5s"),
	Description = T(248177034836, --[[ModItemInventoryItemCompositeDef Auto5 Description]] "First mass produced semi-automatic shotgun in the world. Turned out it was one hell of a good gun for jungle close-quarter firefights. "),
	AdditionalHint = T(577644402779, --[[ModItemInventoryItemCompositeDef Auto5 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дробовик \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неточный бой"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1500,
	Tier = 2,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 6,
	MagazineSize = 5,
	PointBlankBonus = 1,
	OverwatchAngle = 1800,
	BuckshotConeAngle = 300,
	BuckshotFalloffDamage = 15,
	Noise = 35,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Auto5",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"DuckbillChoke",
				"FullChoke",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"Auto5_Basic_LMag",
				"Auto5_Basic_NMag",
				"Auto5_Long_LMag",
				"Auto5_Long_NMag",
				"Auto5_Short_NMag",
			},
			'DefaultComponent', "Auto5_Basic_NMag",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	MaxAimActions = 2,
	BurstShots = 1,
	AutoShots = 1,
	Handling = -15,
	BulletDropRange = 6,
	Grouping = 100,
	WeaponResource = 500,
}

