UndefineClass('Auto5')
DefineClass.Auto5 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 4,
	Reliability = 20,
	Icon = "Mod/e6L4ECj/WeaponIcons/AUTO5.png",
	DisplayName = T(657462590283, --[[ModItemInventoryItemCompositeDef Auto5 DisplayName]] "Auto-5"),
	DisplayNamePlural = T(111620956796, --[[ModItemInventoryItemCompositeDef Auto5 DisplayNamePlural]] "Auto-5"),
	Description = T(632170676188, --[[ModItemInventoryItemCompositeDef Auto5 Description]] "Первый самозарядный дробовик массового производства в мире. Кто бы мог подумать, что он станет идеальным оружием для стычек в джунглях на короткой дистанции?"),
	AdditionalHint = T(577644402779, --[[ModItemInventoryItemCompositeDef Auto5 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Самозарядный - низкие затраты од на выстрел"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1500,
	Tier = 2,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 20,
	MagazineSize = 5,
	PointBlankBonus = 1,
	OverwatchAngle = 1800,
	BuckshotConeAngle = 300,
	BuckshotFalloffDamage = 15,
	Noise = 35,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Auto5",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"DuckbillChoke",
				"FullChoke",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"Auto5_Basic_LMag",
				"Auto5_Basic_NMag",
				"Auto5_Long_LMag",
				"Auto5_Long_NMag",
				"Auto5_Short_NMag",
			},
			'DefaultComponent', "Auto5_Basic_NMag",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	MaxAimActions = 2,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 48,
	BulletDropRange = 6,
	Grouping = 100,
	WeaponResource = 500,
}

