UndefineClass('AVT40')
DefineClass.AVT40 = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-UNIQ",
	object_class = "BattleRifle",
	ScrapParts = 8,
	RepairCost = 5,
	Icon = "Mod/e6L4ECj/WeaponIcons/AVT40.png",
	DisplayName = T(915359425469, --[[ModItemInventoryItemCompositeDef AVT40 DisplayName]] "АВТ-40"),
	DisplayNamePlural = T(210255337735, --[[ModItemInventoryItemCompositeDef AVT40 DisplayNamePlural]] "АВТ-40"),
	Description = T(734026650686, --[[ModItemInventoryItemCompositeDef AVT40 Description]] 'Автоматическая версия винтовки Токарева. Отличается, собственно, наличием режима полностью автоматического огня. Эффективность этого огня, правда, чрезвычайно низкая, а сама "Света" оказалась для стрельбы очередями слишком хрупкой. Найти винтовку в хорошем состоянии не так-то просто.'),
	AdditionalHint = T(109475921134, --[[ModItemInventoryItemCompositeDef AVT40 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Стреляет очередями \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сильная отдача \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ненадежный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x54R",
	Damage = 38,
	AimAccuracy = 10,
	CritChanceScaled = 30,
	MagazineSize = 15,
	WeaponRange = 64,
	OverwatchAngle = 900,
	Noise = 70,
	HandSlot = "TwoHanded",
	Entity = "SVT_40",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_Salvo",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 45,
	AutoShots = 7,
	Handling = -20,
	BulletDropRange = 24,
	Grouping = 35,
	BaseJamChance = 5,
}

