UndefineClass('BAR')
DefineClass.BAR = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "BattleRifle",
	ScrapParts = 12,
	RepairCost = 3,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/BAR.png",
	DisplayName = T(265028974011, --[[ModItemInventoryItemCompositeDef BAR DisplayName]] "BAR"),
	DisplayNamePlural = T(414328375447, --[[ModItemInventoryItemCompositeDef BAR DisplayNamePlural]] "BAR"),
	Description = T(588154036612, --[[ModItemInventoryItemCompositeDef BAR Description]] 'Джон Мозес Браунинг конечно гений, и все такой, но вот с разработкой BAR он явно опоздал. Концепция "ружья-пулемета", как в автомате Федорова или пулемете Гочкисса к началу 30-х годов уже безнадежно устарела, и потому BAR выглядит как неуклюжий косплей ручного пулемета, будучи слишком тяжелым для автоматической винтовки. Говорят, с тех пор американцы делать пулеметы так и не научились.'),
	AdditionalHint = T(657931851868, --[[ModItemInventoryItemCompositeDef BAR AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ружье-недопулемет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сильная отдача \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 3000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_3006",
	Damage = 34,
	ObjDamageMod = 80,
	AimAccuracy = 8,
	MagazineSize = 20,
	WeaponRange = 52,
	OverwatchAngle = 960,
	Noise = 66,
	HandSlot = "TwoHanded",
	Entity = "BAR",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"JAZZ_ControllableBurst",
	},
	ShootAP = 7000,
	ReloadAP = 8000,
	Recoil = 35,
	AutoShots = 5,
	Handling = -35,
	BulletDropRange = 24,
	Grouping = 38,
	WeaponResource = 6500,
}

