UndefineClass('BarretM82')
DefineClass.BarretM82 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-3",
	object_class = "SniperRifle",
	ScrapParts = 16,
	RepairCost = 20,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/Barret.png",
	DisplayName = T(869636891023, --[[ModItemInventoryItemCompositeDef BarretM82 DisplayName]] "M82"),
	DisplayNamePlural = T(627822561036, --[[ModItemInventoryItemCompositeDef BarretM82 DisplayNamePlural]] "M82"),
	Description = T(689592057012, --[[ModItemInventoryItemCompositeDef BarretM82 Description]] "Патрон .50 BMG используется в тяжелых пулеметах (отсюда и название). Но что будет, если разработать на его основе самозарядное дальнобойное оружие? Правильно, вы получите прекрасную крупнокалиберную винтовку для поражения бронированных целей. Или «пушку для стрельбы сквозь стены». Впрочем, для компенсации отдачи к стволу этой дуры пришлось прикрутить дульный тормоз размером с саперную лопатку."),
	AdditionalHint = T(236109853304, --[[ModItemInventoryItemCompositeDef BarretM82 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Легкая пятидесятка \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Медленно стреляет\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Огромная убойность \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый - ограничивает свободу движений"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 120000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_50BMG",
	Damage = 70,
	ObjDamageMod = 300,
	AimAccuracy = 15,
	CritChanceScaled = 30,
	MagazineSize = 5,
	WeaponRange = 100,
	OverwatchAngle = 360,
	Noise = 100,
	HandSlot = "TwoHanded",
	Entity = "Weapon_BarrettM82",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"ImprovedIronsight",
			},
			'DefaultComponent', "JAZZ_Scope_6x",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
			},
			'DefaultComponent', "Compensator",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 10000,
	ReloadAP = 9000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = -82,
	BulletDropRange = 30,
	Grouping = 29,
	BaseJamChance = -20,
	WeaponResource = 3000,
}

