UndefineClass('Beretta93r')
DefineClass.Beretta93r = {
	__parents = { "Autopistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "Autopistol",
	ScrapParts = 6,
	RepairCost = 15,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/Beretta93r.png",
	DisplayName = T(890000000001149, --[[ModItemInventoryItemCompositeDef Beretta93r DisplayName]] "Beretta 93r"),
	DisplayNamePlural = T(890000000001289, --[[ModItemInventoryItemCompositeDef Beretta93r DisplayNamePlural]] "Beretta 93r"),
	Description = T(890000000000010, --[[ModItemInventoryItemCompositeDef Beretta93r Description]] "Робкие попытки Беретты стать чем-то большим, чем простой пистолет, были задушены в зародыше появление таких суперкомпактных автоматов, как MP5K, MAC-10 и MicroUZI."),
	AdditionalHint = T(890000000000606, --[[ModItemInventoryItemCompositeDef Beretta93r AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  Точный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  Стреляет короткими очередями"),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 22,
	ObjDamageMod = 20,
	AimAccuracy = 8,
	CritChanceScaled = 35,
	MagazineSize = 16,
	WeaponRange = 18,
	OverwatchAngle = 5400,
	Noise = 19,
	Entity = "Beretta93r",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
			'DefaultComponent', "su",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"DualShot",
		"JAZZ_SmgStorm",
		"JAZZ_RunAndSMGStorm",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 9,
	Handling = 14,
	BulletDropRange = 6,
	Grouping = 65,
	BaseJamChance = -20,
}

