UndefineClass('BerettaM12')
DefineClass.BerettaM12 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-2",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 4,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/BerettaM12.png",
	DisplayName = T(470598723767, --[[ModItemInventoryItemCompositeDef BerettaM12 DisplayName]] "Беретта М12"),
	DisplayNamePlural = T(102731784616, --[[ModItemInventoryItemCompositeDef BerettaM12 DisplayNamePlural]] "Беретты М12"),
	Description = T(374530148771, --[[ModItemInventoryItemCompositeDef BerettaM12 Description]] "Хороший итальянский послевоенный пистолет-пулемет, вобравший в себя весь накопленный в ходе ВМВ опыт. Может похвастаться отличной точностью и надежностью при использовании в широком круге условий."),
	AdditionalHint = T(526790348080, --[[ModItemInventoryItemCompositeDef BerettaM12 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Обычный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Средний \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Нормальный "),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2800,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 25,
	ObjDamageMod = 20,
	AimAccuracy = 13,
	MagazineSize = 32,
	WeaponRange = 29,
	OverwatchAngle = 4200,
	Noise = 29,
	Entity = "BerettaM12",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_PistolSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	WeaponMass = 32,
	CyclicRPM = 600,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	Recoil = 18,
	BurstShots = 3,
	AutoShots = 6,

	CloseRange = 2,

	CloseRangeFactor = 95,
	BulletDropRange = 10,
	Grouping = 65,
	BaseJamChance = -30,
	WeaponResource = 4500,
}

