UndefineClass('Beretta93r')
DefineClass.Beretta93r = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 15,
	Icon = "Mod/e6L4ECj/WeaponIcons/Beretta93r.png",
	DisplayName = T(848119151903, "Beretta 93r"),
	DisplayNamePlural = T(927743133237, "Beretta 93r"),
	Description = T(107106412369, "Баюн не сделал описание этому предмету :("),
	AdditionalHint = T(491343014488, "Баюн не сделал описание этому предмету :("),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 21,
	ObjDamageMod = 20,
	AimAccuracy = 15,
	CritChance = 5,
	CritChanceScaled = 35,
	MagazineSize = 16,
	WeaponRange = 18,
	OverwatchAngle = 5400,
	Noise = 19,
	Entity = "Beretta93r",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
			'DefaultComponent', "su",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 86,
	BulletDropRange = 6,
	Grouping = 94,
	BaseJamChance = -20,
}

