UndefineClass('BrowningM2HMG')
DefineClass.BrowningM2HMG = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "MachineGun",
	ScrapParts = 20,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/M2Browning",
	DisplayName = T(178371122439, --[[ModItemInventoryItemCompositeDef BrowningM2HMG DisplayName]] "M2 Browning"),
	DisplayNamePlural = T(472976044430, --[[ModItemInventoryItemCompositeDef BrowningM2HMG DisplayNamePlural]] "M2 Brownings"),
	Description = T(706172423918, --[[ModItemInventoryItemCompositeDef BrowningM2HMG Description]] "When you're a dime short of buying some tank ordnance but you won't make a compromise with power."),
	AdditionalHint = T(521209521132, --[[ModItemInventoryItemCompositeDef BrowningM2HMG AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Стационарное оружие\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Очень высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Очень шумное"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 55000,
	CanAppearInShop = false,
	Tier = 3,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_50BMG",
	Damage = 60,
	ObjDamageMod = 300,
	AimAccuracy = 13,
	MagazineSize = 100,
	WeaponRange = 95,
	OverwatchAngle = 3900,
	Noise = 60,
	HandSlot = "TwoHanded",
	Entity = "Weapon_M2Browning",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 7000,
	ReloadAP = 8000,
	WeaponMass = 80,
	CyclicRPM = 700,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	Recoil = 18,
	BurstShots = 4,
	AutoShots = 0,
	BulletDropRange = 28,

	CloseRange = 8,

	CloseRangeFactor = 85,
	Grouping = 21,
	WeaponResource = 50000,
}

