UndefineClass('BrowningM2HMG')
DefineClass.BrowningM2HMG = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "MachineGun",
	ScrapParts = 20,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/M2Browning",
	DisplayName = T(651582932441, --[[ModItemInventoryItemCompositeDef BrowningM2HMG DisplayName]] "M2 Browning"),
	DisplayNamePlural = T(827702439674, --[[ModItemInventoryItemCompositeDef BrowningM2HMG DisplayNamePlural]] "M2 Browning"),
	Description = T(527861175160, --[[ModItemInventoryItemCompositeDef BrowningM2HMG Description]] "Когда на покупку танка денег нет, но жертвовать огневой мощью не вариант."),
	AdditionalHint = T(521209521132, --[[ModItemInventoryItemCompositeDef BrowningM2HMG AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Стационарное оружие\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Очень высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Очень шумное"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 4200,
	Tier = 3,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_50BMG",
	Damage = 60,
	ObjDamageMod = 300,
	AimAccuracy = 18,
	CritChance = 10,
	MagazineSize = 100,
	WeaponRange = 95,
	OverwatchAngle = 3600,
	Noise = 60,
	HandSlot = "TwoHanded",
	Entity = "Weapon_M2Browning",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 6000,
	ReloadAP = 7000,
	Recoil = 25,
	BurstShots = 6,
	AutoShots = 6,
	Handling = 28,
	BulletDropRange = 40,
	Grouping = 350,
	WeaponResource = 50000,
}

