UndefineClass('CAR15')
DefineClass.CAR15 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 45,
	Icon = "Mod/e6L4ECj/WeaponIcons/CAR15.png",
	DisplayName = T(472829589737, --[[ModItemInventoryItemCompositeDef CAR15 DisplayName]] "CAR-15"),
	DisplayNamePlural = T(239679390077, --[[ModItemInventoryItemCompositeDef CAR15 DisplayNamePlural]] "CAR-15"),
	Description = T(651620241290, --[[ModItemInventoryItemCompositeDef CAR15 Description]] "Ранний вариант Colt Commando, на базе винтовки М16А1, получившийся путем обрезания половины ствола. Компактный автомат с громким звуком и большой вспышкой. Не для использования в помещениях."),
	AdditionalHint = T(903563519505, --[[ModItemInventoryItemCompositeDef CAR15 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Можно использовать для стрельбы на бегу"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 4000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 19,
	ObjDamageMod = 50,
	AimAccuracy = 15,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 33,
	OverwatchAngle = 2220,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "CAR15",
	fxClass = "CAR15",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagSmall30_20",
			},
			'DefaultComponent', "MagSmall30_20",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'AvailableComponents', {
				"Flashlight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_3x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"StockLightUnFolded",
				"StockLightFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"DefMuzzle",
				"Suppressor",
				"SuppressorImproved",
			},
			'DefaultComponent', "DefMuzzle",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"AutoFire",
		"RunAndGun",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	Recoil = 12,
	BurstShots = 4,
	AutoShots = 8,
	Handling = 79,
	BulletDropRange = 20,
	Grouping = 220,
}

