UndefineClass('China_Lake')
DefineClass.China_Lake = {
	__parents = { "GrenadeLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "GrenadeLauncher",
	ScrapParts = 16,
	RepairCost = 70,
	Reliability = 50,
	MinMishapChance = -3,
	MaxMishapChance = 40,
	MaxMishapRange = 6,
	MinMishapRange = 1,
	Caliber = "JAZZ_Caliber_40mmGrenade",
	BombardRadius = 3,
	ComponentSlots = {},
	Entity = "China_Lake",
	Icon = "Mod/e6L4ECj/WeaponIcons/ChinaLake.png",
	DisplayName = T(942513624664, --[[ModItemInventoryItemCompositeDef China_Lake DisplayName]] "China Lake"),
	DisplayNamePlural = T(272796175499, --[[ModItemInventoryItemCompositeDef China_Lake DisplayNamePlural]] "China Lake"),
	Description = T(583900868161, --[[ModItemInventoryItemCompositeDef China_Lake Description]] "40-мм гранатомет - это хорошо. Но Армия США - она как сварливая жена, всегда хочет большего, чем может получить прямо сейчас. Поэтому к хорошему надежному 40-мм гранатомету она добавит подствольный магазин на 3 гранаты и помповую перезарядку. Ах, тяжело? Ах, не работает? Ну что же, не думайте что Армия США откажется от идеи получить многозарядный гранатомет, нет..."),
	AdditionalHint = T(808649375885, --[[ModItemInventoryItemCompositeDef China_Lake AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> 40-мм гранатомет. \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Шанс промаха увеличивается с расстоянием. \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый - ограничивает свободу движений"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Explosives",
	Valuable = 1,
	Cost = 14000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 22,
	CategoryPair = "HeavyWeapons",
	CritChanceScaled = 0,
	MagazineSize = 3,
	WeaponRange = 40,
	Noise = 30,
	HandSlot = "TwoHanded",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 6000,
	ReloadAP = 9000,
	WeaponResource = 100,
}

