UndefineClass('China_Lake')
DefineClass.China_Lake = {
	__parents = { "GrenadeLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeLauncher",
	ScrapParts = 16,
	Reliability = 50,
	Caliber = "JAZZ_Caliber_40mmGrenade",
	AttackAP = 4000,
	BombardRadius = 3,
	ComponentSlots = {},
	Entity = "China_Lake",
	Icon = "Mod/e6L4ECj/WeaponIcons/ChinaLake.png",
	DisplayName = T(942513624664, --[[ModItemInventoryItemCompositeDef China_Lake DisplayName]] "China Lake"),
	DisplayNamePlural = T(272796175499, --[[ModItemInventoryItemCompositeDef China_Lake DisplayNamePlural]] "China Lake"),
	Description = T(583900868161, --[[ModItemInventoryItemCompositeDef China_Lake Description]] "40-мм гранатомет - это хорошо. Но Армия США - она как сварливая жена, всегда хочет большего, чем может получить прямо сейчас. Поэтому к хорошему надежному 40-мм гранатомету она добавит подствольный магазин на 3 гранаты и помповую перезарядку. Ах, тяжело? Ах, не работает? Ну что же, не думайте что Армия США откажется от идеи получить многозарядный гранатомет, нет..."),
	AdditionalHint = T(808649375885, --[[ModItemInventoryItemCompositeDef China_Lake AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Стреляет дальнобойными 40-мм гранатами\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Вероятность неудачи растет с увеличением расстояния\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Громоздкое (нет бесплатного перемещения)"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Explosives",
	Valuable = 1,
	Cost = 10000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 20,
	CategoryPair = "HeavyWeapons",
	CritChanceScaled = 0,
	MagazineSize = 3,
	PenetrationClass = 4,
	WeaponRange = 45,
	HandSlot = "TwoHanded",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 4000,
	ReloadAP = 6000,
	Handling = 70,
}

