UndefineClass('Colt1911')
DefineClass.Colt1911 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-3",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 6,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/1911.png",
	DisplayName = T(890000000000846, --[[ModItemInventoryItemCompositeDef Colt1911 DisplayName]] "Colt M1911"),
	DisplayNamePlural = T(890000000000680, --[[ModItemInventoryItemCompositeDef Colt1911 DisplayNamePlural]] "Colt M1911"),
	Description = T(890000000000182, --[[ModItemInventoryItemCompositeDef Colt1911 Description]] 'Дедушка недавно отметил 100-летний юбилей, но уходить куда-то вовсе не собирается, пока, дословно "не изобретут эти ваши лазеры-шмазеры и световые мечи".'),
	AdditionalHint = T(890000000000040, --[[ModItemInventoryItemCompositeDef Colt1911 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тысяча\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Девятьсот\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Одиннадцатый."),
	UnitStat = "Marksmanship",
	Cost = 1400,
	CanAppearInShop = true,
	Tier = 1,
	RestockWeight = 110,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_45ACP",
	Damage = 27,
	ObjDamageMod = 25,
	AimAccuracy = 7,
	CritChanceScaled = 30,
	MagazineSize = 7,
	WeaponRange = 14,
	OverwatchAngle = 5400,
	Noise = 28,
	Entity = "Colt1911",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
			},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	MaxAimActions = 2,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 4,
	Grouping = 61,
	BaseJamChance = -10,
	WeaponResource = 1400,
}

