UndefineClass('ColtPeacemaker')
DefineClass.ColtPeacemaker = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-2",
	object_class = "Revolver",
	ReloadStyle = "Revolver",
	ScrapParts = 6,
	RepairCost = 4,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/ColtPeaceMaker.png",
	DisplayName = T(692081024631, --[[ModItemInventoryItemCompositeDef ColtPeacemaker DisplayName]] "Peacemaker"),
	DisplayNamePlural = T(275530346749, --[[ModItemInventoryItemCompositeDef ColtPeacemaker DisplayNamePlural]] "Peacemakers"),
	Description = T(890000000001229, --[[ModItemInventoryItemCompositeDef ColtPeacemaker Description]] "Старый, заслуженный револьвер одинарного действия, разработанный для армии США. Главное, носите c пустой каморой под курком, если не хотите лишиться ноги."),
	AdditionalHint = T(890000000000512, --[[ModItemInventoryItemCompositeDef ColtPeacemaker AdditionalHint]] "Револьвер \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Анахронизм"),
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_357",
	Damage = 34,
	ObjDamageMod = 40,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 17,
	OverwatchAngle = 5100,
	Noise = 32,
	Entity = "Weapon_Colt",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelShort",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"JAZZ_Fanning",
		"JAZZ_Bullseye",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	Recoil = 17,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 6,
	Grouping = 28,
	BaseJamChance = -100,
	WeaponResource = 3000,
}

