UndefineClass('ColtAnaconda')
DefineClass.ColtAnaconda = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T2",
	object_class = "Revolver",
	ScrapParts = 8,
	RepairCost = 30,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/Anaconda.png",
	DisplayName = T(600758452029, --[[ModItemInventoryItemCompositeDef ColtAnaconda DisplayName]] "Anaconda"),
	DisplayNamePlural = T(576916732572, --[[ModItemInventoryItemCompositeDef ColtAnaconda DisplayNamePlural]] "Anaconda"),
	Description = T(518994407073, --[[ModItemInventoryItemCompositeDef ColtAnaconda Description]] "Я знаю, о чём вы сейчас думаете. Есть в нем патроны, или нет. Это «Магнум» 44-го калибра, самый убойный револьвер на свете, и он может решить практически любую проблему в общении с людьми."),
	AdditionalHint = T(934305731778, --[[ModItemInventoryItemCompositeDef ColtAnaconda AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Револьвер - точный, надежный, но большие затраты ОД на выстрел и перезарядку\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможна установка практически любого прицела"),
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 1200,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_44CAL",
	Damage = 35,
	ObjDamageMod = 40,
	AimAccuracy = 9,
	CritChance = 10,
	CritChanceScaled = 40,
	MagazineSize = 6,
	WeaponRange = 21,
	OverwatchAngle = 5100,
	Noise = 32,
	Entity = "Weapon_ColtAnaconda44",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelShort",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"BaseIronsight_Anaconda",
				"ImprovedIronsight",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"LaserDot_Anaconda",
				"FlashlightDot_Anaconda",
				"UVDot_Anaconda",
			},
			'DefaultComponent', "BaseIronsight_Anaconda",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 89,
	BulletDropRange = 7,
	Grouping = 91,
	BaseJamChance = -100,
	WeaponResource = 4500,
}

