UndefineClass('Colt38Special')
DefineClass.Colt38Special = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 1,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/ColtPeaceMaker.png",
	DisplayName = T(436628869426, --[[ModItemInventoryItemCompositeDef Colt38Special DisplayName]] "Colt .38 Special"),
	DisplayNamePlural = T(427566606201, --[[ModItemInventoryItemCompositeDef Colt38Special DisplayNamePlural]] "Colt .38 Special"),
	Description = T(563384549909, --[[ModItemInventoryItemCompositeDef Colt38Special Description]] "TODO"),
	AdditionalHint = T(460566737568, --[[ModItemInventoryItemCompositeDef Colt38Special AdditionalHint]] "TODO"),
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_38",
	Damage = 16,
	ObjDamageMod = 40,
	AimAccuracy = 11,
	CritChance = 5,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 15,
	OverwatchAngle = 5100,
	Noise = 12,
	Entity = "38Special",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelShort_Pistol",
			},
			'DefaultComponent', "BarrelShort_Pistol",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 3000,
	ReloadAP = 5000,
	Recoil = 1,
	AutoShots = 3,
	Handling = 86,
	BulletDropRange = 7,
	Grouping = 92,
	BaseJamChance = -100,
}

