UndefineClass('ColtAnaconda')
DefineClass.ColtAnaconda = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 2-5",
	object_class = "Revolver",
	ReloadStyle = "Revolver",
	ScrapParts = 8,
	RepairCost = 5,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/Anaconda.png",
	DisplayName = T(769922391034, --[[ModItemInventoryItemCompositeDef ColtAnaconda DisplayName]] "Anaconda"),
	DisplayNamePlural = T(505981904083, --[[ModItemInventoryItemCompositeDef ColtAnaconda DisplayNamePlural]] "Anacondas"),
	Description = T(518994407073, --[[ModItemInventoryItemCompositeDef ColtAnaconda Description]] "Я знаю, о чём вы сейчас думаете. Есть в нем патроны, или нет. Это «Магнум» 44-го калибра, самый убойный револьвер на свете, и он может решить практически любую проблему в общении с людьми."),
	AdditionalHint = T(934305731778, --[[ModItemInventoryItemCompositeDef ColtAnaconda AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Револьвер \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сорок четвертый \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Кольт \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> неудобный"),
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 1200,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_44CAL",
	Damage = 35,
	ObjDamageMod = 40,
	AimAccuracy = 12,
	CritChanceScaled = 40,
	MagazineSize = 6,
	OverwatchAngle = 5100,
	Noise = 32,
	Entity = "Weapon_ColtAnaconda44",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelShort",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
				PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"JAZZ_BaseIronsight_Anaconda",
				"JAZZ_ImprovedIronsight",
				"JAZZ_LaserDot_Anaconda",
				"JAZZ_FlashlightDot_Anaconda",
				"JAZZ_UVDot_Anaconda",
			},
			'DefaultComponent', "JAZZ_BaseIronsight_Anaconda",
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"JAZZ_Fanning",
		"JAZZ_Bullseye",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	Recoil = 18,
	AutoShots = 0,
	BulletDropRange = 8,

	CloseRange = 0,

	CloseRangeFactor = 100,
	Grouping = 70,
	BaseJamChance = -100,
	WeaponResource = 3500,
}

