UndefineClass('ColtM1917')
DefineClass.ColtM1917 = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 1,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/Colt1917.png",
	DisplayName = T(436628869426, --[[ModItemInventoryItemCompositeDef ColtM1917 DisplayName]] "Colt M1917 .45 Service Revolver"),
	DisplayNamePlural = T(427566606201, --[[ModItemInventoryItemCompositeDef ColtM1917 DisplayNamePlural]] "Colt M1917 .45 Service Revolver"),
	Description = T(878461703337, --[[ModItemInventoryItemCompositeDef ColtM1917 Description]] "Баюн не сделал описание этому предмету :("),
	AdditionalHint = T(434107786112, --[[ModItemInventoryItemCompositeDef ColtM1917 AdditionalHint]] "Баюн не сделал описание этому предмету :("),
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_45ACP",
	Damage = 26,
	ObjDamageMod = 40,
	AimAccuracy = 12,
	CritChance = 5,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 16,
	OverwatchAngle = 5100,
	Noise = 28,
	Entity = "Colt1917",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	Recoil = 1,
	AutoShots = 3,
	Handling = 88,
	BulletDropRange = 7,
	Grouping = 92,
	BaseJamChance = -100,
}

