UndefineClass('ConcussiveGrenade')
DefineClass.ConcussiveGrenade = {
	__parents = { "GrenadeItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/ConcussiveGrenade",
	ItemType = "Grenade",
	DisplayName = T(893674710968, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade DisplayName]] "Flashbang"),
	DisplayNamePlural = T(904754847701, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade DisplayNamePlural]] "Flashbangs"),
	AdditionalHint = T(339045500192, --[[ModItemInventoryItemCompositeDef ConcussiveGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ослепляет цели\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Отменяет подготовленные выстрелы в радиусе взрыва\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Подавляет и лишает укрытия цели в центре\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Почти бесшумная"),
	UnitStat = "Explosives",
	Cost = 400,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 35,
	MaxStock = 5,
	CategoryPair = "Grenade",
	MaxStacks = 5,
	MinMishapChance = 1,
	MaxMishapChance = 50,
	MinMishapRange = 1,
	MaxMishapRange = 6,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	CenterAppliedEffects = {
		"Exposed",
		"Blinded",
		"SuppressStunGrenade",
	},
	CenterAreaOfEffect = 2,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	AreaAppliedEffects = {
		"CancelShot",
		"Blinded",
	},
	PenetrationClass = 1,
	BurnGround = false,
	BaseDamage = 0,
	Scatter = 6,
	AttackAP = 4000,
	BaseRange = 12,
	ThrowMaxRange = 22,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 40,
	Entity = "Weapon_StunGrenadeM84",
	ActionIcon = "UI/Icons/Hud/concussive_grenade",
}

