UndefineClass('CZ52')
DefineClass.CZ52 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 1,
	Icon = "Mod/e6L4ECj/WeaponIcons/CZ52.png",
	DisplayName = T(848119151903, --[[ModItemInventoryItemCompositeDef CZ52 DisplayName]] "CZ Vz. 52"),
	DisplayNamePlural = T(927743133237, --[[ModItemInventoryItemCompositeDef CZ52 DisplayNamePlural]] "CZ Vz. 52"),
	Description = T(107106412369, --[[ModItemInventoryItemCompositeDef CZ52 Description]] "Не особо популярный чехословацкий пистолет. На стандартных патронах 7.62х25мм, рассчитанных на повышенное давление в стволе, происходил чрезвычайно быстрый износ, что могло приводить к самопроизвольным выстрелам."),
	AdditionalHint = T(491343014488, --[[ModItemInventoryItemCompositeDef CZ52 AdditionalHint]] "Баюн не сделал описание этому предмету :("),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x25",
	Damage = 19,
	ObjDamageMod = 20,
	AimAccuracy = 7,
	CritChanceScaled = 35,
	MagazineSize = 8,
	WeaponRange = 18,
	OverwatchAngle = 5400,
	Noise = 22,
	Entity = "CZ52",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
			'DefaultComponent', "su",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 84,
	BulletDropRange = 6,
	Grouping = 94,
	BaseJamChance = -20,
	WeaponResource = 650,
}

