UndefineClass('CZ75')
DefineClass.CZ75 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 7,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/CZ75.png",
	DisplayName = T(848119151903, --[[ModItemInventoryItemCompositeDef CZ75 DisplayName]] "CZ75"),
	DisplayNamePlural = T(927743133237, --[[ModItemInventoryItemCompositeDef CZ75 DisplayNamePlural]] "CZ75"),
	Description = T(107106412369, --[[ModItemInventoryItemCompositeDef CZ75 Description]] 'Спортивный, боевой, полицейский, гражданский пистолет из Чехии. Практически, победитель оружейного "Евровидения", но первое место принадлежит тому, кого нельзя называть. Иначе придется его купить.'),
	AdditionalHint = T(491343014488, --[[ModItemInventoryItemCompositeDef CZ75 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удобный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Безопасный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Чемпионский"),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 22,
	ObjDamageMod = 20,
	AimAccuracy = 8,
	CritChanceScaled = 35,
	MagazineSize = 16,
	WeaponRange = 18,
	OverwatchAngle = 5400,
	Noise = 24,
	Entity = "CZ75",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
			'DefaultComponent', "su",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 27,
	BulletDropRange = 6,
	Grouping = 52,
	BaseJamChance = -20,
	WeaponResource = 1500,
}

