UndefineClass('DeLisle')
DefineClass.DeLisle = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "SniperRifle",
	ScrapParts = 10,
	RepairCost = 8,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/DeLisle.png",
	ItemType = "DMR",
	DisplayName = T(732531674185, "De Lisle Carbine"),
	DisplayNamePlural = T(707630654921, "De Lisle Carbines"),
	Description = "",
	AdditionalHint = "",
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 7500,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_45ACP",
	Damage = 30,
	ObjDamageMod = 50,
	AimAccuracy = 25,
	CritChance = 30,
	CritChanceScaled = 80,
	MagazineSize = 7,
	WeaponRange = 28,
	OverwatchAngle = 1200,
	Noise = 2,
	HandSlot = "TwoHanded",
	Entity = "DeLisle",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"Jazz_IronSight",
			},
			'DefaultComponent', "Jazz_IronSight",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"SuppressorIntegrated",
			},
			'DefaultComponent', "SuppressorIntegrated",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 52,
	BulletDropRange = 10,
	Grouping = 170,
	BaseJamChance = -10,
	WeaponResource = 6000,
}

