UndefineClass('DoubleBarrelShotgun')
DefineClass.DoubleBarrelShotgun = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "Shotgun",
	ScrapParts = 8,
	RepairCost = 3,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/DoubleBarrel.png",
	DisplayName = T(907424409524, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun DisplayName]] "Двустволка"),
	DisplayNamePlural = T(810124779127, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun DisplayNamePlural]] "Двустволки"),
	Description = T(649524596282, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun Description]] 'Простое охотничье оружие. Модные боевые дробовики могут быть самозарядными или вообще стрелять очередями, но только эта дедовская двустволка способна выстреливать по два патрона за раз. Как сказал один великий серьезный человек "Из двух стволов стрелять в два раза веселее".'),
	AdditionalHint = T(982931592669, --[[ModItemInventoryItemCompositeDef DoubleBarrelShotgun AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Двустволка\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  Быстро стреляет\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  Надежный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1200,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 120,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 2,
	WeaponRange = 21,
	PointBlankBonus = 1,
	OverwatchAngle = 2280,
	BuckshotConeAngle = 240,
	BuckshotFalloffDamage = 10,
	Noise = 40,
	HandSlot = "TwoHanded",
	Entity = "Weapon_DBShotgun",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLongShotgun",
				"BarrelNormal",
				"BarrelShortShotgun",
			},
			'DefaultComponent', "BarrelNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"DoubleBarrel",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 5000,
	ReloadAP = 3000,
	MaxAimActions = 2,
	BurstShots = 1,
	AutoShots = 1,
	Handling = -10,
	BulletDropRange = 8,
	Grouping = 140,
	BaseJamChance = -100,
	WeaponResource = 3000,
}

