UndefineClass('DP27')
DefineClass.DP27 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "MachineGun",
	ScrapParts = 12,
	RepairCost = 2,
	Reliability = 35,
	Icon = "Mod/e6L4ECj/WeaponIcons/DP27.png",
	DisplayName = T(973194681593, --[[ModItemInventoryItemCompositeDef DP27 DisplayName]] "ДП-27"),
	DisplayNamePlural = T(457155447326, --[[ModItemInventoryItemCompositeDef DP27 DisplayNamePlural]] "ДП-27"),
	Description = T(968512989346, --[[ModItemInventoryItemCompositeDef DP27 Description]] "Ручной пулемет ДП был принят на вооружение РККА в 1927 году и стал одним из первых оружейных образцов, созданных с нуля в молодом Советском государстве. С честью прошел всю Великую Отечественную Войну и уже давно отошел от дел, но тут его нашли вы."),
	AdditionalHint = T(881416264419, --[[ModItemInventoryItemCompositeDef DP27 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Легкий"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 3000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x54R",
	Damage = 37,
	ObjDamageMod = 90,
	AimAccuracy = 20,
	MagazineSize = 47,
	WeaponRange = 57,
	Noise = 68,
	HandSlot = "TwoHanded",
	Entity = "DP27",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 8000,
	ReloadAP = 8000,
	Recoil = 16,
	BurstShots = 6,
	AutoShots = 6,
	Handling = 30,
	BulletDropRange = 22,
	Grouping = 278,
	BaseJamChance = -5,
	WeaponResource = 15000,
}

