UndefineClass('FlareStick')
DefineClass.FlareStick = {
	__parents = { "Flare" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Flare",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/FlareStick",
	ItemType = "Throwables",
	DisplayName = T(581195033607, --[[ModItemInventoryItemCompositeDef FlareStick DisplayName]] "Сигнальная шашка"),
	DisplayNamePlural = T(431696879632, --[[ModItemInventoryItemCompositeDef FlareStick DisplayNamePlural]] "Сигнальные шашки"),
	AdditionalHint = T(560759240469, --[[ModItemInventoryItemCompositeDef FlareStick AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Освещает большую территорию\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая вероятность неудачи\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бесшумное"),
	UnitStat = "Explosives",
	Cost = 200,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MaxStacks = 5,
	MinMishapChance = 10,
	MaxMishapChance = 50,
	MinMishapRange = 1,
	MaxMishapRange = 6,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaOfEffect = 4,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 8,
	AttackAP = 4000,
	BaseRange = 12,
	ThrowMaxRange = 30,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 0,
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/flare",
}

