UndefineClass('FNMAG')
DefineClass.FNMAG = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "MachineGun",
	ScrapParts = 16,
	RepairCost = 8,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/FNMAG.png",
	DisplayName = T(528780556719, --[[ModItemInventoryItemCompositeDef FNMAG DisplayName]] "FN MAG"),
	DisplayNamePlural = T(747265213458, --[[ModItemInventoryItemCompositeDef FNMAG DisplayNamePlural]] "FN MAG"),
	Description = T(826668610685, --[[ModItemInventoryItemCompositeDef FNMAG Description]] "Единый пулемет бельгийского производства, под патрон 7.62 NATO. Разработанный в 1950х, до сих пор является образцовым оружием. Максимальная универсальность, возможность крепления на технику, на станок, стрельбы с рук и сошек, сменный ствол. Вот только... тяжелый, падлюка."),
	AdditionalHint = T(568354544935, --[[ModItemInventoryItemCompositeDef FNMAG AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая скорострельность"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 35000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 36,
	ObjDamageMod = 80,
	AimAccuracy = 29,
	MagazineSize = 100,
	WeaponRange = 62,
	OverwatchAngle = 600,
	Noise = 65,
	HandSlot = "TwoHanded",
	Entity = "KSP_58_B",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"KSP_BIPOD",
			},
			'DefaultComponent', "KSP_BIPOD",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 9000,
	ReloadAP = 10000,
	Recoil = 16,
	BurstShots = 8,
	AutoShots = 8,
	Handling = 33,
	BulletDropRange = 22,
	Grouping = 330,
	BaseJamChance = -10,
	WeaponResource = 10000,
}

