UndefineClass('FNMinimi')
DefineClass.FNMinimi = {
	__parents = { "LightMachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "LightMachineGun",
	ScrapParts = 16,
	RepairCost = 10,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/Minimi.png",
	DisplayName = T(723941795453, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayName]] "Minimi"),
	DisplayNamePlural = T(814341971836, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayNamePlural]] "Minimi"),
	Description = T(795167411023, --[[ModItemInventoryItemCompositeDef FNMinimi Description]] "Пулемет Minimi под патрон 5.56 НАТО разрабатывался в качестве оружия поддержки на уровне взвода. Он настолько хорошо исполнял свою роль, что его приняли на вооружение ВС США, и теперь весь мир знает его как М249 SAW. Также существует вариант Minimi под патрон 7,62 НАТО."),
	AdditionalHint = T(270977662171, --[[ModItemInventoryItemCompositeDef FNMinimi AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Легкий пулемет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Кладет строчку как поссать сходить"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 60000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 25,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_556",
	Damage = 20,
	ObjDamageMod = 50,
	AimAccuracy = 13,
	MagazineSize = 100,
	WeaponRange = 54,
	OverwatchAngle = 840,
	Noise = 48,
	HandSlot = "TwoHanded",
	Entity = "Weapon_FNMinimi",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelLongImproved",
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagBelt_100-200",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 8000,
	ReloadAP = 8000,
	Recoil = 6,
	BurstShots = 10,
	Handling = -15,
	BulletDropRange = 17,
	Grouping = 57,
	WeaponResource = 7500,
}

