UndefineClass('FNMinimi')
DefineClass.FNMinimi = {
	__parents = { "LightMachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "LightMachineGun",
	ScrapParts = 16,
	RepairCost = 10,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/Minimi.png",
	DisplayName = T(967860288607, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayName]] "Minimi"),
	DisplayNamePlural = T(559267255380, --[[ModItemInventoryItemCompositeDef FNMinimi DisplayNamePlural]] "Minimis"),
	Description = T(460196952811, --[[ModItemInventoryItemCompositeDef FNMinimi Description]] "The 5.56 NATO Minimi is meant to provide squad-level fire support. It does so well that it was adopted by the US military and most people know it as the M249 squad automatic weapon. There is also a Minimi variant firing 7.62 NATO rounds."),
	AdditionalHint = T(270977662171, --[[ModItemInventoryItemCompositeDef FNMinimi AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Легкий пулемет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Кладет строчку как поссать сходить"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 22000,
	CanAppearInShop = true,
	Tier = 4,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_556",
	Damage = 20,
	ObjDamageMod = 50,
	AimAccuracy = 13,
	MagazineSize = 100,
	WeaponRange = 54,
	OverwatchAngle = 840,
	Noise = 48,
	HandSlot = "TwoHanded",
	Entity = "Weapon_FNMinimi",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelLong",
				"JAZZ_BarrelLongImproved",
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelNormalImproved",
				"JAZZ_BarrelShort",
				"JAZZ_BarrelShortImproved",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
			'DefaultComponent', "JAZZ_Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockHeavy",
				"JAZZ_StockNormal",
			},
			'DefaultComponent', "JAZZ_StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagBelt_100_200",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
		"BurstFire",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
		"JAZZ_TargetSweep",
	},
	ShootAP = 8000,
	ReloadAP = 8000,
	WeaponMass = 80,
	CyclicRPM = 700,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	AutoShots = 7,
	Recoil = 18,
	BurstShots = 4,

	CloseRange = 8,

	CloseRangeFactor = 85,
	BulletDropRange = 17,
	Grouping = 57,
	WeaponResource = 7500,
}

