UndefineClass('FragGrenade')
DefineClass.FragGrenade = {
	__parents = { "GrenadeItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/Frag Grenade",
	ItemType = "Grenade",
	DisplayName = T(172826329217, --[[ModItemInventoryItemCompositeDef FragGrenade DisplayName]] "Граната M24"),
	DisplayNamePlural = T(167822758999, --[[ModItemInventoryItemCompositeDef FragGrenade DisplayNamePlural]] "Гранаты M24"),
	Description = "",
	AdditionalHint = T(243383619902, --[[ModItemInventoryItemCompositeDef FragGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Взрывается при контакте\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> На близкой дистанции только разброс (Ловкость + Взрывчатка; уверенно примерно с 30)"),
	UnitStat = "Explosives",
	Cost = 300,
	CanAppearInShop = true,
	CategoryPair = "Grenade",
	MaxStacks = 3,
	MinMishapChance = 0,
	MaxMishapChance = 40,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterObjDamageMod = 50,
	CenterAppliedEffects = {
		"Headshot",
		"Armsshot",
		"Legsshot",
	},
	AreaOfEffect = 4,
	CenterAreaOfEffect = 2,
	AreaUnitDamageMod = 50,
	AreaObjDamageMod = 25,
	PenetrationClass = 1,
	DeathType = "BlowUp",
	BaseDamage = 60,
	Scatter = 6,
	BaseRange = 2,
	ThrowMaxRange = 25,
	CanBounce = false,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 8000,
	IgnoreCoverReduction = 33,
	Noise = 80,
	Entity = "MilitaryCamp_Grenade_01",
	ActionIcon = "UI/Icons/Hud/frag_grenade",
}

