UndefineClass('FRF2')
DefineClass.FRF2 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1+",
	object_class = "SniperRifle",
	ScrapParts = 14,
	RepairCost = 5,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/FRF2.png",
	DisplayName = T(799798287692, --[[ModItemInventoryItemCompositeDef FRF2 DisplayName]] "FR F2"),
	DisplayNamePlural = T(821596806678, --[[ModItemInventoryItemCompositeDef FRF2 DisplayNamePlural]] "FR F2"),
	Description = T(155102946917, --[[ModItemInventoryItemCompositeDef FRF2 Description]] 'Современная "болтовка" на вооружении ВС Франции. Представляет собой модернизированную винтовку FR F1 - измененная ложа, приклад, пластиковый теплоизолирующий кожух на стволе. Используется в разработке системы оружия солдата будущего FELIN. Винтовка будущих 1970-х...'),
	AdditionalHint = T(357652125031, --[[ModItemInventoryItemCompositeDef FRF2 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Продольно-скользящий затвор - высокие затраты ОД на выстрел\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Интегрированные прицел и сошки"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 12000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_75French",
	Damage = 35,
	ObjDamageMod = 80,
	AimAccuracy = 26,
	CritChanceScaled = 40,
	MagazineSize = 10,
	WeaponRange = 75,
	OverwatchAngle = 360,
	Noise = 56,
	HandSlot = "TwoHanded",
	Entity = "FRF2",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_Scope_8x_SCROME",
			},
			'DefaultComponent', "JAZZ_Scope_8x_SCROME",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'DefaultComponent', "Bipod",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 7000,
	ReloadAP = 5000,
	MaxAimActions = 4,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 35,
	BulletDropRange = 23,
	Grouping = 450,
	BaseJamChance = -10,
	WeaponResource = 6000,
}

