UndefineClass('G36')
DefineClass.G36 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T2+",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/G36.png",
	DisplayName = T(637644235374, --[[ModItemInventoryItemCompositeDef G36 DisplayName]] "G36"),
	DisplayNamePlural = T(493010224161, --[[ModItemInventoryItemCompositeDef G36 DisplayNamePlural]] "G36"),
	Description = T(514897379898, --[[ModItemInventoryItemCompositeDef G36 Description]] "Футуристичного вида штурмовая винтовка с интегрированной двойной системой прицеливания. Газовый поршень короткого хода и патрон 5,56 НАТО - что еще нужно для стабильной, прицельной стрельбы?"),
	AdditionalHint = T(590205659814, --[[ModItemInventoryItemCompositeDef G36 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 26000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 20,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 44,
	PointBlankBonus = 1,
	OverwatchAngle = 1920,
	Noise = 50,
	HandSlot = "TwoHanded",
	Entity = "Weapon_HKG36",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelLong",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagDrum_30-100_cumbersome",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"TacGrip",
				"VerticalGrip",
				"GrenadeLauncher",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockFolded",
				"StockHeavy",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"Jazz_G36Sight",
				"Jazz_G36Scope",
			},
			'DefaultComponent', "Jazz_G36Sight",
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 4000,
	Recoil = 10,
	BurstShots = 4,
	AutoShots = 8,
	Handling = 74,
	BulletDropRange = 16,
	Grouping = 275,
	BaseJamChance = -10,
}

