UndefineClass('G36')
DefineClass.G36 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 15,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/G36.png",
	DisplayName = T(675182711489, --[[ModItemInventoryItemCompositeDef G36 DisplayName]] "G36"),
	DisplayNamePlural = T(349971410946, --[[ModItemInventoryItemCompositeDef G36 DisplayNamePlural]] "G36s"),
	Description = T(511176251955, --[[ModItemInventoryItemCompositeDef G36 Description]] "Futuristic assault rifle with an integrated dual combat sighting system. The 5.56 NATO cartridge combined with the short-stroke gas piston system make this a joy to shoot."),
	AdditionalHint = T(590205659814, --[[ModItemInventoryItemCompositeDef G36 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Умеренно точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Умеренно надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Умеренно скорострельный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Das ist gut"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 26000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 11,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 44,
	PointBlankBonus = 1,
	OverwatchAngle = 1320,
	Noise = 46,
	HandSlot = "TwoHanded",
	Entity = "Weapon_HKG36",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelLong",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_Compensator",
				"JAZZ_Suppressor",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagDrum_30-100_cumbersome",
				"JAZZ_MagQuick",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_TacGrip",
				"JAZZ_VerticalGrip",
				"JAZZ_GrenadeLauncher",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockNormal",
				"JAZZ_StockFolded",
				"JAZZ_StockHeavy",
			},
			'DefaultComponent', "JAZZ_StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_G36Sight",
				"JAZZ_G36Scope",
			},
			'DefaultComponent', "JAZZ_G36Sight",
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 10,
	BurstShots = 4,
	AutoShots = 8,

	CloseRange = 6,

	CloseRangeFactor = 85,
	BulletDropRange = 16,
	Grouping = 63,
	BaseJamChance = -10,
	WeaponResource = 7800,
}

