UndefineClass('G36c')
DefineClass.G36c = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "Carbine",
	ScrapParts = 10,
	RepairCost = 16,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/G36C.png",
	DisplayName = T(164978166764, --[[ModItemInventoryItemCompositeDef G36c DisplayName]] "G36c"),
	DisplayNamePlural = T(985251261053, --[[ModItemInventoryItemCompositeDef G36c DisplayNamePlural]] "G36c"),
	Description = T(742518516674, --[[ModItemInventoryItemCompositeDef G36c Description]] 'Ультракороткий вариант G36 в компоновке "коммандо". Вместо фирменного оптико-электронного прицела и ручки для переноски - универсальная планка. Как и любое оружие этого класса - компактный, но чересчур шумный.'),
	AdditionalHint = T(354147184590, --[[ModItemInventoryItemCompositeDef G36c AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Может стрелять в движении \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Универсальный обвес"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 24000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 10,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 39,
	OverwatchAngle = 1560,
	Noise = 48,
	HandSlot = "TwoHanded",
	Entity = "G36c",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_DefMuzzle",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_SuppressorImproved",
			},
			'DefaultComponent', "JAZZ_DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagQuick_G36",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_TacGrip",
				"JAZZ_VerticalGrip",
				"JAZZ_GrenadeLauncher_M14",
			},
			'DefaultComponent', "JAZZ_TacGrip",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
			'DefaultComponent', "JAZZ_LaserDot",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
	},
	ShootAP = 4000,
	ReloadAP = 6000,
	WeaponMass = 35,
	CyclicRPM = 0,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	BurstShots = 0,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 5,

	CloseRangeFactor = 90,
	BulletDropRange = 14,
	Grouping = 63,
	BaseJamChance = -15,
	WeaponResource = 6500,
}

