UndefineClass('G36c')
DefineClass.G36c = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T3",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/G36C.png",
	DisplayName = T(164978166764, --[[ModItemInventoryItemCompositeDef G36c DisplayName]] "G36c"),
	DisplayNamePlural = T(985251261053, --[[ModItemInventoryItemCompositeDef G36c DisplayNamePlural]] "G36c"),
	Description = T(742518516674, --[[ModItemInventoryItemCompositeDef G36c Description]] 'Ультракороткий вариант G36 в компоновке "коммандо". Вместо фирменного оптико-электронного прицела и ручки для переноски - универсальная планка. Как и любое оружие этого класса - компактный, но чересчур шумный.'),
	AdditionalHint = T(354147184590, --[[ModItemInventoryItemCompositeDef G36c AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Можно использовать для стрельбы на бегу\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность при стрельбе навскидку"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 24000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 22,
	ObjDamageMod = 50,
	AimAccuracy = 16,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 39,
	OverwatchAngle = 2520,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "G36c",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"DefMuzzle",
				"ImprovisedSuppressor",
				"SuppressorImproved",
			},
			'DefaultComponent', "DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"TacGrip",
				"VerticalGrip",
				"GrenadeLauncher_M14",
			},
			'DefaultComponent', "TacGrip",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
			'DefaultComponent', "LaserDot",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightUnFolded",
				"StockLightFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
		"RunAndGun",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	Recoil = 12,
	AutoShots = 8,
	Handling = 84,
	BulletDropRange = 15,
	Grouping = 245,
	BaseJamChance = -15,
}

