UndefineClass('G3A3')
DefineClass.G3A3 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 13,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/G3A3.png",
	DisplayName = T(179839012718, "G3A3"),
	DisplayNamePlural = T(248581813381, "G3A3"),
	Description = T(995185159847, "С 1959 по 1995 годы - основное стрелковое оружие Бундесвера. A3 - поздний серийный вариант, с пластиковым вентилируемым цевьем и барабанным целиком. В основе автоматики - фирменная схема с роликовым замедлением полусвободного затвора. Странным путем пошла эволюция оружия, в то время как у советов уже был автомат под промежуточный патрон."),
	AdditionalHint = T(350976395234, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая дальность эффективной стрельбы\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ужасная точность при стрельбе навскидку или очередями"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 18000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 35,
	ObjDamageMod = 80,
	AimAccuracy = 29,
	MagazineSize = 20,
	WeaponRange = 58,
	OverwatchAngle = 960,
	Noise = 62,
	HandSlot = "TwoHanded",
	Entity = "G3A3",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagSmall20_10",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"SuppressorImproved",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 30,
	BurstShots = 2,
	AutoShots = 5,
	Handling = 55,
	BulletDropRange = 20,
	Grouping = 296,
	BaseJamChance = -30,
	WeaponResource = 9000,
}

