UndefineClass('G3A4')
DefineClass.G3A4 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 13,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/G3A4.png",
	DisplayName = T(555464992529, "G3A4"),
	DisplayNamePlural = T(690529267847, "G3A4"),
	Description = T(384221107329, "Та же G3A3, но с раздвижным телескопическим прикладом, призванным хоть как-то сократить габариты громоздкой винтовки."),
	AdditionalHint = T(816969893415, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая дальность эффективной стрельбы\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ужасная точность при стрельбе навскидку с разложенным прикладом"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 22000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 35,
	ObjDamageMod = 80,
	AimAccuracy = 29,
	MagazineSize = 20,
	WeaponRange = 58,
	OverwatchAngle = 1200,
	Noise = 62,
	HandSlot = "TwoHanded",
	Entity = "G3A4",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"DefMuzzle",
				"Compensator",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagSmall20_10",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 30,
	BurstShots = 2,
	AutoShots = 5,
	Handling = 55,
	BulletDropRange = 20,
	Grouping = 298,
	BaseJamChance = -30,
	WeaponResource = 9000,
}

