UndefineClass('G3SniperV1')
DefineClass.G3SniperV1 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T2-",
	object_class = "SniperRifle",
	ScrapParts = 14,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/G3Sniper.png",
	ItemType = "DMR",
	DisplayName = T(958223576910, --[[ModItemInventoryItemCompositeDef G3SniperV1 DisplayName]] "G3 SG"),
	DisplayNamePlural = T(933103009214, --[[ModItemInventoryItemCompositeDef G3SniperV1 DisplayNamePlural]] "G3 SG"),
	Description = T(213918680889, --[[ModItemInventoryItemCompositeDef G3SniperV1 Description]] "Heckler-Koch G3SG1 - cнайперская целевая винтовка, разработанная путем незначительной доработки серийной штурмовой винтовки G3. Для модернизации отбирались винтовки, показавшие лучшую кучность на заводских тестах."),
	AdditionalHint = T(257228948726, --[[ModItemInventoryItemCompositeDef G3SniperV1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Снайперская версия G3A3\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон, но большая отдача\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая дальность эффективной стрельбы"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 25000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 40,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 35,
	ObjDamageMod = 80,
	AimAccuracy = 26,
	CritChanceScaled = 20,
	MagazineSize = 20,
	WeaponRange = 62,
	OverwatchAngle = 1200,
	Noise = 48,
	HandSlot = "TwoHanded",
	Entity = "G3Sniper",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"DefMuzzle",
				"Compensator",
				"SuppressorImproved",
			},
			'DefaultComponent', "DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
			},
			'DefaultComponent', "JAZZ_Scope_DA15_6x",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagSmall20_10",
				"MagNormal",
			},
			'DefaultComponent', "MagSmall20_10",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 6000,
	ReloadAP = 5000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 62,
	BulletDropRange = 20,
	Grouping = 310,
	BaseJamChance = -30,
	WeaponResource = 14500,
}

