UndefineClass('Galil')
DefineClass.Galil = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 50,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/Galil.png",
	DisplayName = T(268498479614, --[[ModItemInventoryItemCompositeDef Galil DisplayName]] "Galil"),
	DisplayNamePlural = T(204404678981, --[[ModItemInventoryItemCompositeDef Galil DisplayNamePlural]] "Galil"),
	Description = T(288080233237, --[[ModItemInventoryItemCompositeDef Galil Description]] "Изначально разрабатывался со встроенной открывашкой, чтобы солдаты не гробили магазины в попытках вскрывать ими бутылки. По какой-то неизвестной причине пытается косплеить АК-47."),
	AdditionalHint = T(770511551101, --[[ModItemInventoryItemCompositeDef Galil AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая эффективность при стрельбе навскидку, но не в автоогне"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 3200,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 32,
	ObjDamageMod = 80,
	AimAccuracy = 22,
	MagazineSize = 25,
	WeaponRange = 54,
	OverwatchAngle = 1440,
	Noise = 75,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Galil",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelNormal",
				"BarrelShort",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLight",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"Galil_Brake_Default",
				"Compensator",
				"Suppressor",
				"ImprovisedSuppressor",
				"SuppressorImproved",
			},
			'DefaultComponent', "Galil_Brake_Default",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"GrenadeLauncher_Galil",
				"Galil_Handguard_Default",
				"Bipod_Galil",
			},
			'DefaultComponent', "Bipod_Galil",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge_25_40",
				"MagNormal",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	Recoil = 32,
	AutoShots = 6,
	Handling = 65,
	BulletDropRange = 20,
	Grouping = 280,
}

