UndefineClass('Gewehr98')
DefineClass.Gewehr98 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1-",
	object_class = "SniperRifle",
	ScrapParts = 8,
	Reliability = 25,
	Icon = "Mod/e6L4ECj/WeaponIcons/K98.png",
	DisplayName = T(217134868057, --[[ModItemInventoryItemCompositeDef Gewehr98 DisplayName]] "Gewehr 98"),
	DisplayNamePlural = T(525213233954, --[[ModItemInventoryItemCompositeDef Gewehr98 DisplayNamePlural]] "Gewehr 98"),
	Description = T(910257473110, --[[ModItemInventoryItemCompositeDef Gewehr98 Description]] "Говорят, что этот шедевр Пауля Маузера стал дедушкой всех «болтов» - ружей с продольно-скользящим затвором. От него ведут родословную чуть ли не все современные снайперские и охотничьи винтовки."),
	AdditionalHint = T(232973799458, --[[ModItemInventoryItemCompositeDef Gewehr98 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Продольно-скользящий затвор - высокие затраты ОД на выстрел\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Низкая точность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1100,
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_792",
	Damage = 42,
	ObjDamageMod = 80,
	AimAccuracy = 25,
	CritChanceScaled = 40,
	MagazineSize = 5,
	WeaponRange = 62,
	OverwatchAngle = 360,
	Noise = 60,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Gewehr98",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'AvailableComponents', {
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_CombatScope_2x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_Scope_DA15_6x",
				"ImprovedIronsight",
				"GewehrDefaultSight",
			},
			'DefaultComponent', "GewehrDefaultSight",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	MaxAimActions = 4,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 32,
	BulletDropRange = 26,
	Grouping = 360,
	WeaponResource = 5000,
}

