UndefineClass('GlowStick')
DefineClass.GlowStick = {
	__parents = { "Flare" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Flare",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/GlowStick",
	ItemType = "Throwables",
	DisplayName = T(162602825192, --[[ModItemInventoryItemCompositeDef GlowStick DisplayName]] "ХИС"),
	DisplayNamePlural = T(734469665900, --[[ModItemInventoryItemCompositeDef GlowStick DisplayNamePlural]] "ХИС"),
	AdditionalHint = T(589698013135, --[[ModItemInventoryItemCompositeDef GlowStick AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Освещает небольшую область"),
	UnitStat = "Explosives",
	Cost = 100,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 50,
	CategoryPair = "Grenade",
	MaxStacks = 3,
	MinMishapChance = 2,
	MaxMishapChance = 50,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaOfEffect = 2,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 6,
	AttackAP = 2000,
	BaseRange = 14,
	ThrowMaxRange = 18,
	CanBounce = false,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 0,
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/throw_glowstick",
	ExpirationTurns = 10,
}

