UndefineClass('GoldenGun')
DefineClass.GoldenGun = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Vanilla unique — Gold Fever; JAZZ caliber/attacks",
	object_class = "SniperRifle",
	ScrapParts = 16,
	RepairCost = 20,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/GoldenGun",
	DisplayName = T(726601867404, --[[ModItemInventoryItemCompositeDef GoldenGun DisplayName]] "Gold Fever"),
	DisplayNamePlural = T(126313842219, --[[ModItemInventoryItemCompositeDef GoldenGun DisplayNamePlural]] "Gold Fever"),
	Description = T(998072775687, --[[ModItemInventoryItemCompositeDef GoldenGun Description]] "This custom-made M14 is coated with 24-karat gold and has a mean aura."),
	AdditionalHint = T(439493128569, --[[ModItemInventoryItemCompositeDef GoldenGun AdditionalHint]] "<bullet_point> Insensitive\n<bullet_point> Cumbersome (no Free Move)\n<bullet_point> Very noisy"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 25000,
	RestockWeight = 0,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 40,
	ObjDamageMod = 90,
	AimAccuracy = 12,
	CritChanceScaled = 40,
	MagazineSize = 20,
	IgnoreCoverReduction = 1,
	WeaponRange = 62,
	OverwatchAngle = 720,
	Noise = 75,
	HandSlot = "TwoHanded",
	Entity = "Weapon_M14_GoldEquip",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
			'DefaultComponent', "JAZZ_Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_M14_Default_Muzzle",
				"JAZZ_Compensator",
				"JAZZ_Suppressor",
			},
			'DefaultComponent', "JAZZ_M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 22,
	BurstShots = 0,
	AutoShots = 0,
	WeaponMass = 55,
	WeaponSizeClass = "Long",
	CloseRange = 16,
	CloseRangeFactor = 70,
	BulletDropRange = 17,
	Grouping = 55,
	WeaponResource = 10000,
}

