UndefineClass('GrizzlyLAR')
DefineClass.GrizzlyLAR = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "Pistol",
	ScrapParts = 10,
	RepairCost = 15,
	Reliability = 20,
	Icon = "Mod/e6L4ECj/WeaponIcons/GrizzlyLAR.png",
	DisplayName = T(121264662868, "Grizzly LAR"),
	DisplayNamePlural = T(906903634947, "Grizzly LAR"),
	Description = T(855624394430, "Баюн не сделал описание этому предмету :("),
	AdditionalHint = T(643376234175, "Баюн не сделал описание этому предмету :("),
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 10000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_44CAL",
	Damage = 34,
	ObjDamageMod = 50,
	AimAccuracy = 18,
	CritChance = 10,
	CritChanceScaled = 45,
	MagazineSize = 6,
	OverwatchAngle = 4920,
	Noise = 36,
	Entity = "GrizzlyLAR",
	ComponentSlots = {},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	Recoil = 1,
	AutoShots = 3,
	Handling = 78,
	BulletDropRange = 7,
	Grouping = 80,
	WeaponResource = 800,
	CanAppearUsed = false,
}

