UndefineClass('HE_Grenade')
DefineClass.HE_Grenade = {
	__parents = { "GrenadeItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/HEGrenade",
	ItemType = "Grenade",
	DisplayName = T(211344759878, --[[ModItemInventoryItemCompositeDef HE_Grenade DisplayName]] "Граната Mk2"),
	DisplayNamePlural = T(246480537411, --[[ModItemInventoryItemCompositeDef HE_Grenade DisplayNamePlural]] "Гранаты Mk2"),
	AdditionalHint = T(663236691841, --[[ModItemInventoryItemCompositeDef HE_Grenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Взрывается при контакте"),
	UnitStat = "Explosives",
	Cost = 400,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Grenade",
	MaxStacks = 3,
	MinMishapChance = 0,
	MaxMishapChance = 50,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterObjDamageMod = 50,
	CenterAppliedEffects = {
		"Armsshot",
		"Headshot",
		"Legsshot",
	},
	AreaOfEffect = 5,
	CenterAreaOfEffect = 2,
	AreaUnitDamageMod = 50,
	AreaObjDamageMod = 25,
	PenetrationClass = 1,
	DeathType = "BlowUp",
	BaseDamage = 70,
	Scatter = 6,
	BaseRange = 3,
	ThrowMaxRange = 25,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 8000,
	Noise = 60,
	Entity = "MilitaryCamp_Grenade_02",
	ActionIcon = "UI/Icons/Hud/throw_grenade",
}

