UndefineClass('HiPower')
DefineClass.HiPower = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 2-2",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 9,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/Hipower.png",
	DisplayName = T(796605924344, --[[ModItemInventoryItemCompositeDef HiPower DisplayName]] "Hi-Power"),
	DisplayNamePlural = T(376748831554, --[[ModItemInventoryItemCompositeDef HiPower DisplayNamePlural]] "Hi-Powers"),
	Description = T(644234035738, --[[ModItemInventoryItemCompositeDef HiPower Description]] "Если 1911 - это прадедушка всех пистолетов в мире, то Хай-Пауэр - это их двоюродный дедушка. Считается одним из самых безопасных пистолетов в мире из-за  наличия одинарного УСМ, которое исключает выстрел без предварительного взвода курка."),
	AdditionalHint = T(361743792592, --[[ModItemInventoryItemCompositeDef HiPower AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Браунинг\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Это вам не это"),
	UnitStat = "Marksmanship",
	Cost = 1100,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 100,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 22,
	ObjDamageMod = 20,
	AimAccuracy = 9,
	CritChanceScaled = 20,
	MagazineSize = 13,
	WeaponRange = 17,
	OverwatchAngle = 5400,
	Noise = 24,
	Entity = "Weapon_Browning_HP",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_25_PISTOL_9",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelNormalImproved",
				"JAZZ_BarrelShort",
				"JAZZ_BarrelShortImproved",
				"JAZZ_BarrelLong",
				"JAZZ_BarrelLongImproved",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	MaxAimActions = 2,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 7,
	Grouping = 70,
	BaseJamChance = -10,
	WeaponResource = 1400,
}

