UndefineClass('HiPower')
DefineClass.HiPower = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-2",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 9,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/Hipower.png",
	DisplayName = T(348898367603, --[[ModItemInventoryItemCompositeDef HiPower DisplayName]] "Hi-Power"),
	DisplayNamePlural = T(765614045230, --[[ModItemInventoryItemCompositeDef HiPower DisplayNamePlural]] "Hi-Power"),
	Description = T(644234035738, --[[ModItemInventoryItemCompositeDef HiPower Description]] "Если 1911 - это прадедушка всех пистолетов в мире, то Хай-Пауэр - это их двоюродный дедушка. Считается одним из самых безопасных пистолетов в мире из-за  наличия одинарного УСМ, которое исключает выстрел без предварительного взвода курка."),
	AdditionalHint = T(361743792592, --[[ModItemInventoryItemCompositeDef HiPower AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Браунинг\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Это вам не это"),
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 22,
	ObjDamageMod = 20,
	AimAccuracy = 7,
	CritChanceScaled = 20,
	MagazineSize = 13,
	WeaponRange = 17,
	OverwatchAngle = 5400,
	Noise = 24,
	Entity = "Weapon_Browning_HP",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormalFine",
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelNormalImproved",
				"BarrelShort",
				"BarrelShortImproved",
				"BarrelLong",
				"BarrelLongImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
		"PistolPerk_Mozambique",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 16,
	BulletDropRange = 6,
	Grouping = 17,
	BaseJamChance = -10,
	WeaponResource = 1400,
}

