UndefineClass('HK23e')
DefineClass.HK23e = {
	__parents = { "LightMachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "LightMachineGun",
	ScrapParts = 16,
	RepairCost = 16,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/HK23.png",
	DisplayName = T(109123476314, --[[ModItemInventoryItemCompositeDef HK23e DisplayName]] "HK23e"),
	DisplayNamePlural = T(772194811780, --[[ModItemInventoryItemCompositeDef HK23e DisplayNamePlural]] "HK23e"),
	Description = T(597937543269, --[[ModItemInventoryItemCompositeDef HK23e Description]] "HK 23E - последний серийный вариант пулемета HK 21 в калибре 5.56mm NATO. Имеет удлиненную ствольную коробку и модифицированный спусковой механизм, допускающий ведение огня очередями с отсечкой по 3 выстрела."),
	AdditionalHint = T(331961558889, --[[ModItemInventoryItemCompositeDef HK23e AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Легкий пулемет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Слабая отдача \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 170000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_556",
	Damage = 22,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	MagazineSize = 100,
	WeaponRange = 52,
	OverwatchAngle = 840,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "HK23e",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 8000,
	ReloadAP = 9000,
	Recoil = 6,
	BurstShots = 7,
	AutoShots = 7,
	Handling = -25,
	BulletDropRange = 18,
	Grouping = 60,
	BaseJamChance = -30,
	WeaponResource = 10000,
}

