UndefineClass('HK33')
DefineClass.HK33 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 14,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/HK33.png",
	DisplayName = T(918715946710, --[[ModItemInventoryItemCompositeDef HK33 DisplayName]] "HK33"),
	DisplayNamePlural = T(551664372478, --[[ModItemInventoryItemCompositeDef HK33 DisplayNamePlural]] "HK33"),
	Description = T(864975846345, --[[ModItemInventoryItemCompositeDef HK33 Description]] "Винтовка с полусвободным затвором на основе винтовки G3 под новый тогда патрон .223 Remington. Самими немцами не используется, но получила распространение в странах третьего мира. Производится, например, по лицензии в той-же Турции."),
	AdditionalHint = T(747191951831, --[[ModItemInventoryItemCompositeDef HK33 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Маленькая G3 \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежная \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстро стреляет"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 25000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 10,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 46,
	PointBlankBonus = 1,
	OverwatchAngle = 1320,
	Noise = 62,
	HandSlot = "TwoHanded",
	Entity = "HK_33",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'AvailableComponents', {
				"JAZZ_HK33Lower",
				"JAZZ_HK33LowerMod",
			},
			'DefaultComponent', "JAZZ_HK33Lower",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"JAZZ_HK33Handguard",
				"JAZZ_HK33HandguardMod",
			},
			'DefaultComponent', "JAZZ_HK33Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelShortRunNGun",
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelLong",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_Compensator",
				"JAZZ_Suppressor",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagDrum_30_100_HK33",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_TacGrip",
				"JAZZ_VerticalGrip",
				"JAZZ_GrenadeLauncher",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	WeaponMass = 36,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 16,
	BurstShots = 4,
	AutoShots = 7,
	BulletDropRange = 14,

	CloseRange = 6,

	CloseRangeFactor = 85,
	Grouping = 57,
	BaseJamChance = -30,
	WeaponResource = 7600,
}

