UndefineClass('HK416')
DefineClass.HK416 = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	MaxStock = 1,
	comment = "Tier 3-1",
	object_class = "Carbine",
	ScrapParts = 10,
	RepairCost = 14,
	Reliability = 90,
	Icon = "Mod/e6L4ECj/WeaponIcons/HK416_Standard.png",
	DisplayName = T(890000000033101, "HK416"),
	DisplayNamePlural = T(890000000033101, "HK416"),
	Description = T(890000000033103, "Современный карабин под патрон 5,56×45 мм. Сменные стволы, приклады и прицелы; магазин STANAG на 30 патронов."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 18000,
	CanAppearInShop = true,
	Tier = 4,
	RestockWeight = 30,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 46,
	OverwatchAngle = 1560,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "JAZZ_HK416_Standard",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_HK416_BarrelNormal",
				"JAZZ_HK416_BarrelShort",
				"JAZZ_HK416_BarrelLong",
			},
			'DefaultComponent', "JAZZ_HK416_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_HK416_Stock",
				"JAZZ_HK416_StockCTR",
			},
			'DefaultComponent', "JAZZ_HK416_Stock",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
			},
		}),
			PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GrenadeLauncher",
				"JAZZ_VerticalGrip",
				"JAZZ_TacGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
		}),
},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"AutoFire",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 17,
	BurstShots = 4,
	AutoShots = 9,
	WeaponMass = 35,
	CyclicRPM = 850,
	WeaponSizeClass = "Carbine",
	CloseRange = 5,
	CloseRangeFactor = 90,
	BulletDropRange = 15,
	Grouping = 57,
	BaseJamChance = -40,
	WeaponResource = 8000,
}
