UndefineClass('Ithaca')
DefineClass.Ithaca = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1+",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 50,
	Reliability = 30,
	Icon = "Mod/e6L4ECj/WeaponIcons/Ithaca.png",
	DisplayName = T(369993581386, --[[ModItemInventoryItemCompositeDef Ithaca DisplayName]] "Ithaca37"),
	DisplayNamePlural = T(181330570580, --[[ModItemInventoryItemCompositeDef Ithaca DisplayNamePlural]] "Ithaca37"),
	Description = T(929958056232, --[[ModItemInventoryItemCompositeDef Ithaca Description]] "Популярное некогда ружье для охоты, самообороны и даже иногда нападения. Сейчас, конечно, сдает позиции более коммерчески успешным образцам, но нет-нет да иногда где-нибудь мелькнет. Ну вы помните, да - Идем со мной, если хочешь жить!"),
	AdditionalHint = T(703583682840, --[[ModItemInventoryItemCompositeDef Ithaca AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Помповый - высокие затраты од на выстрел\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможность модификаций"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 3500,
	CanAppearInShop = true,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 15,
	MagazineSize = 4,
	WeaponRange = 21,
	PointBlankBonus = 1,
	OverwatchAngle = 1980,
	BuckshotConeAngle = 180,
	BuckshotFalloffDamage = 10,
	HandSlot = "TwoHanded",
	Entity = "Ithaca37",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', nil),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_Scope_6x",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelShortShotgun",
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockNo",
			},
			'DefaultComponent', "StockNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 76,
	BulletDropRange = 8,
	Grouping = 145,
}

