UndefineClass('Ithaca')
DefineClass.Ithaca = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "Shotgun",
	ReloadStyle = "Tube",
	ScrapParts = 10,
	RepairCost = 5,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/Ithaca.png",
	DisplayName = T(369993581386, --[[ModItemInventoryItemCompositeDef Ithaca DisplayName]] "Ithaca37"),
	DisplayNamePlural = T(181330570580, --[[ModItemInventoryItemCompositeDef Ithaca DisplayNamePlural]] "Ithaca37"),
	Description = T(929958056232, --[[ModItemInventoryItemCompositeDef Ithaca Description]] "Популярное некогда ружье для охоты, самообороны и даже иногда нападения. Сейчас, конечно, сдает позиции более коммерчески успешным образцам, но нет-нет да иногда где-нибудь мелькнет. Ну вы помните, да - Идем со мной, если хочешь жить!"),
	AdditionalHint = T(703583682840, --[[ModItemInventoryItemCompositeDef Ithaca AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дробовик \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 3500,
	CanAppearInShop = true,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 10,
	CritChanceScaled = 20,
	MagazineSize = 4,
	WeaponRange = 21,
	PointBlankBonus = 1,
	OverwatchAngle = 1980,
	BuckshotConeAngle = 180,
	BuckshotProjectiles = 1,
	BuckshotFalloffDamage = 10,
	Noise = 38,
	HandSlot = "TwoHanded",
	Entity = "Ithaca37",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', nil),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelShortShotgun",
				"JAZZ_BarrelNormal",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockNormal",
				"JAZZ_StockNo",
			},
			'DefaultComponent', "JAZZ_StockNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 6000,
	ReloadAP = 5000,
	WeaponMass = 36,
	CyclicRPM = 0,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 25,
	MaxAimActions = 2,
	BurstShots = 0,
	AutoShots = 0,

	CloseRange = 5,

	CloseRangeFactor = 90,
	BulletDropRange = 8,
	Grouping = 145,
	WeaponResource = 1800,
}

