UndefineClass('JAZZ_FNFAL_Tactical')
DefineClass.JAZZ_FNFAL_Tactical = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3 - JAZZ-WEAPON-FAL-FAMILY-001",
	object_class = "BattleRifle",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/JAZZ_FNFAL_Tactical.png",
	DisplayName = T(990002700, --[[ModItemInventoryItemCompositeDef JAZZ_FNFAL_Tactical DisplayName]] "FN FAL Tactical"),
	DisplayNamePlural = T(990002701, --[[ModItemInventoryItemCompositeDef JAZZ_FNFAL_Tactical DisplayNamePlural]] "FN FAL Tacticals"),
	Description = T(990002702, --[[ModItemInventoryItemCompositeDef JAZZ_FNFAL_Tactical Description]] "Та же фалочка, но собранная под современное железо: цевьё на планках, полимерный приклад, место под длинный ствол. Бельгийская классика, доведённая до ума теми, кому из неё стрелять."),
	AdditionalHint = T(990002703, --[[ModItemInventoryItemCompositeDef JAZZ_FNFAL_Tactical AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Планки везде \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ровнее в очереди \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Длинный ствол"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 8500,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 60,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 34,
	ObjDamageMod = 80,
	AimAccuracy = 14,
	MagazineSize = 20,
	WeaponRange = 57,
	OverwatchAngle = 960,
	Noise = 62,
	HandSlot = "TwoHanded",
	Entity = "Weapon_FNFAL",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_FNFAL_TacHandguard",
			},
			'DefaultComponent', "JAZZ_FNFAL_TacHandguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Compensator",
				"JAZZ_Suppressor",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagNormalFine_FAL",
				"JAZZ_MagLarge_20_30_FAL",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelLong",
				"JAZZ_BarrelLongImproved",
				"JAZZ_BarrelNormalImproved",
				"JAZZ_BarrelHeavy",
				"JAZZ_BarrelShort",
				"JAZZ_BarrelShortImproved",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockNormal",
				"JAZZ_StockHeavy",
			},
			'DefaultComponent', "JAZZ_StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GrenadeLauncher",
				"JAZZ_TacGrip",
				"JAZZ_VerticalGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_Salvo",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 36,
	AutoShots = 6,
	WeaponMass = 43,
	CyclicRPM = 650,
	CloseRange = 11,
	CloseRangeFactor = 80,
	BulletDropRange = 19,
	Grouping = 51,
	BaseJamChance = -15,
	WeaponResource = 8200,
}
