UndefineClass('JazzArmor_TwaronHelmHeavy')
DefineClass.JazzArmor_TwaronHelmHeavy = {
	__parents = { "Armor" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Class2 H",
	object_class = "Armor",
	ScrapParts = 6,
	Degradation = 30,
	Icon = "Mod/e6L4ECj/ArmorIcons/TwaronHelmH.png",
	DisplayName = T(964124006795, "Шлем Тварон, Тяжелый"),
	DisplayNamePlural = T(696326635294, "Шлемы Тварон, Тяжелый"),
	Description = T(889128024610, "Твароновый шлем с бронещитком, защищающим лицо и глаза бойца. Предлагает отличную защиту при приемлемом весе."),
	AdditionalHint = T(377018690641, "Модульный шлем, тяжелый вариант"),
	Valuable = 1,
	Cost = 3000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 1,
	CategoryPair = "Heavy",
	Slot = "Head",
	PenetrationClass = 2,
	DamageReduction = 20,
	AdditionalReduction = 60,
	ProtectedBodyParts = set( "Head", "Neck" ),
	ArmorRating = 25,
	MeleeArmorRating = 10,
	BlockFaceSlot = true,
	Weight = 4,
	Vision = -5,
	StunGrenadeProtection = 10,
	ArmorResource = 180,
	Repairability = 80,
}

