UndefineClass('JAZZ_M14_MkIII')
DefineClass.JAZZ_M14_MkIII = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Unique - JAZZ-WEAPON-M14-FAMILY-001",
	object_class = "SniperRifle",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/JAZZ_M14_MkIII.png",
	DisplayName = T(990002714, --[[ModItemInventoryItemCompositeDef JAZZ_M14_MkIII DisplayName]] "M14 Mk III"),
	DisplayNamePlural = T(990002715, --[[ModItemInventoryItemCompositeDef JAZZ_M14_MkIII DisplayNamePlural]] "M14 Mk III"),
	Description = T(990002716, --[[ModItemInventoryItemCompositeDef JAZZ_M14_MkIII Description]] "Кастомный M14 с рельсой Mk III, своим камуфляжем и обвесом. Не путать с золотым Gold Fever."),
	AdditionalHint = T(990002717, --[[ModItemInventoryItemCompositeDef JAZZ_M14_MkIII AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Уник \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Не в Bobby Ray"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 28000,
	CanAppearInShop = false,
	Tier = 3,
	RestockWeight = 0,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 33,
	ObjDamageMod = 80,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 20,
	WeaponRange = 58,
	OverwatchAngle = 900,
	Noise = 63,
	HandSlot = "TwoHanded",
	Entity = "JAZZ_M14_MkIII",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
            'SlotType', "Barrel",
            'Modifiable', false,
            'AvailableComponents', { "JAZZ_BarrelNormal" },
            'DefaultComponent', "JAZZ_BarrelNormal",
        }),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockHeavy",
				"JAZZ_StockNormal",
				"JAZZ_StockLight",
			},
			'DefaultComponent', "JAZZ_StockHeavy",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagSmall20_10_M14",
			},
			'DefaultComponent', "JAZZ_MagSmall20_10_M14",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GrenadeLauncher_M14",
				"JAZZ_TacGrip_M14",
				"JAZZ_VerticalGrip_M14",
				"JAZZ_Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_M14_Default_Muzzle",
				"JAZZ_Compensator",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
			'DefaultComponent', "JAZZ_Suppressor",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'DefaultComponent', "JAZZ_Scope_12x",
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Rail",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Rail_MkIII",
			},
			'DefaultComponent', "JAZZ_Rail_MkIII",
		}),
},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 22,
	BurstShots = 0,
	AutoShots = 0,
	WeaponMass = 55,
	WeaponSizeClass = "Long",
	CloseRange = 16,
	CloseRangeFactor = 70,
	BulletDropRange = 17,
	Grouping = 45,
	BaseJamChance = -10,
	WeaponResource = 4000,
}
