UndefineClass('L42A1')
DefineClass.L42A1 = {
	MaxStock = 1,
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "SniperRifle",
	ScrapParts = 14,
	RepairCost = 7,
	Reliability = 90,
	Icon = "Mod/e6L4ECj/WeaponIcons/L42A1.png",
	DisplayName = T(761915301101, "L42A1"),
	DisplayNamePlural = T(761915301102, "L42A1"),
	Description = T(761915301103, "Британская винтовка с ручным перезаряжанием под патрон 7,62x51 мм и собственным оптическим прицелом."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 10000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 35,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 37,
	ObjDamageMod = 80,
	AimAccuracy = 14,
	CritChanceScaled = 50,
	MagazineSize = 10,
	WeaponRange = 72,
	OverwatchAngle = 420,
	Noise = 46,
	HandSlot = "TwoHanded",
	Entity = "L42A1",
	fxClass = "M24Sniper",
	ComponentSlots = {
        PlaceObj('WeaponComponentSlot', {
            'SlotType', "Scope", 'Modifiable', false,
            'AvailableComponents', { "JAZZ_L42A1_Scope" },
            'DefaultComponent', "JAZZ_L42A1_Scope",
        }),
    },
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 8000,
	ReloadAP = 6000,
	BurstShots = 0,
	WeaponMass = 44,
	CyclicRPM = 0,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	Recoil = 22,
	AutoShots = 0,

	CloseRange = 16,

	CloseRangeFactor = 70,
	BulletDropRange = 18,
	Grouping = 43,
	BaseJamChance = -20,
	WeaponResource = 5500,
}

