UndefineClass('M14SAW')
DefineClass.M14SAW = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-2",
	object_class = "BattleRifle",
	ScrapParts = 10,
	RepairCost = 10,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/M14.png",
	DisplayName = T(929580740853, --[[ModItemInventoryItemCompositeDef M14SAW DisplayName]] "M-14"),
	DisplayNamePlural = T(270485818300, --[[ModItemInventoryItemCompositeDef M14SAW DisplayNamePlural]] "M-14s"),
	Description = T(513913385785, --[[ModItemInventoryItemCompositeDef M14SAW Description]] "Глубоко модифицированная винтовка M1 - измененный газовый двигатель, магазинное питание, новый на тот момент (начало 1950х) патрон 7.62х51мм. Винтовка оказалась крайне бесполезной в условиях войны в джунглях, из-за чего была заменена M16."),
	AdditionalHint = T(895635386126, --[[ModItemInventoryItemCompositeDef M14SAW AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Запах напалма по утрам. \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сильная отдача"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 33,
	ObjDamageMod = 80,
	AimAccuracy = 10,
	MagazineSize = 20,
	WeaponRange = 62,
	OverwatchAngle = 960,
	Noise = 65,
	HandSlot = "TwoHanded",
	Entity = "Weapon_M14",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelHeavy",
				"JAZZ_BarrelLong",
				"JAZZ_BarrelLongImproved",
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelNormalImproved",
				"JAZZ_BarrelShort",
				"JAZZ_BarrelShortImproved",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockHeavy",
				"JAZZ_StockNormal",
				"JAZZ_StockLight",
			},
			'DefaultComponent', "JAZZ_StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagNormalFine_M14",
				"JAZZ_MagSmall20_10_M14",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GrenadeLauncher_M14",
				"JAZZ_TacGrip_M14",
				"JAZZ_VerticalGrip_M14",
				"JAZZ_Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_M14_Default_Muzzle",
				"JAZZ_Compensator",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
			},
			'DefaultComponent', "JAZZ_M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_Salvo",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	WeaponMass = 36,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 36,
	BurstShots = 4,
	AutoShots = 7,

	CloseRange = 8,

	CloseRangeFactor = 80,
	BulletDropRange = 17,
	Grouping = 41,
	WeaponResource = 4500,
}

