UndefineClass('M16A1')
DefineClass.M16A1 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 9,
	Reliability = 45,
	Icon = "Mod/e6L4ECj/WeaponIcons/M16A1.png",
	DisplayName = T(775007485793, --[[ModItemInventoryItemCompositeDef M16A1 DisplayName]] "M16A1"),
	DisplayNamePlural = T(720763685329, --[[ModItemInventoryItemCompositeDef M16A1 DisplayNamePlural]] "M16A1"),
	Description = T(291276979254, --[[ModItemInventoryItemCompositeDef M16A1 Description]] "Ранний вариант винтовки М16 (AR15), принятый на вооружение US Army в далеком 1967 году. Из-за стремления этой самой US Army сэкономить, винтовка получила кучу проблем с надежностью, отмыть от которых репутацию она не может до сих пор."),
	AdditionalHint = T(242556118888, --[[ModItemInventoryItemCompositeDef M16A1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ненадежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Счастливый сын"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 4000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 90,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 20,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 46,
	OverwatchAngle = 1260,
	Noise = 52,
	HandSlot = "TwoHanded",
	Entity = "M16A1",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_LaserDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"JAZZ_Handguard",
				"JAZZ_M16A1LaunchHandGuard",
			},
			'DefaultComponent', "JAZZ_Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagNormalFine_AR15",
				"JAZZ_MagLarge_50_AR15",
				"JAZZ_MagQuick_AR15",
				"JAZZ_MagSmall30_20",
			},
			'DefaultComponent', "JAZZ_MagSmall30_20",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_HolsterBelt",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_3x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"AutoFire",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	WeaponMass = 36,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 16,
	BurstShots = 4,
	AutoShots = 7,

	CloseRange = 8,

	CloseRangeFactor = 85,
	BulletDropRange = 15,
	Grouping = 61,
	BaseJamChance = 5,
	WeaponResource = 4000,
}

