UndefineClass('M16A2')
DefineClass.M16A2 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 11,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/M16A2.png",
	DisplayName = T(506098327802, "M16A2"),
	DisplayNamePlural = T(919482370189, "M16A2"),
	Description = T(206041732514, "Пожалуй, самый легендарный образец западного огнестрельного оружия. М16 была первой винтовкой под патрон 5,56 НАТО, разработанный специально под ее 20-дюймовый ствол. Высокая скорость полета пули обеспечивает как точность на дальних дистанциях, так и удобство стрельбы очередями, хоть М16 и проигрывает в убойной силе своему основному конкуренту, АК-47. Главное, не обращайте внимания на досылатель патрона..."),
	AdditionalHint = T(967388007174, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность при прицельной стрельбе одиночными или очередями\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Отсутствует режим автоматического огня"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5500,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 22,
	ObjDamageMod = 50,
	AimAccuracy = 23,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 48,
	OverwatchAngle = 1560,
	Noise = 52,
	HandSlot = "TwoHanded",
	Entity = "M16A2",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
				"ImprovisedSuppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagLarge",
				"MagNormal",
				"MagQuick",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"Handguard",
				"M16A1LaunchHandGuard",
			},
			'DefaultComponent', "Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_3x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 9,
	AutoShots = 8,
	Handling = 64,
	BulletDropRange = 17,
	Grouping = 296,
	WeaponResource = 5500,
}

