UndefineClass('M16A4')
DefineClass.M16A4 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 14,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/M16A4.png",
	DisplayName = T(403087186042, --[[ModItemInventoryItemCompositeDef M16A4 DisplayName]] "M16A4"),
	DisplayNamePlural = T(684216400032, --[[ModItemInventoryItemCompositeDef M16A4 DisplayNamePlural]] "M16A4"),
	Description = T(332382553568, --[[ModItemInventoryItemCompositeDef M16A4 Description]] 'Современный вариант известной американской винтовки М16. Индекс А4 - означает наличие планки Пикатини вместо маскотной несъемной рукоятки для переноски. Кроме того, винтовка оборудована широким набором других посадочных мест для улучшения "кастомизации" конкретной винтовки под задачи конкретного бойца.'),
	AdditionalHint = T(315157271455, --[[ModItemInventoryItemCompositeDef M16A4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Отсечка по три \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Слабая отдача \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Архивраг калаша"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 25000,
	CanAppearInShop = true,
	Tier = 3,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 24,
	ObjDamageMod = 50,
	AimAccuracy = 14,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 48,
	OverwatchAngle = 1200,
	Noise = 52,
	HandSlot = "TwoHanded",
	Entity = "M16A4",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagSmall30_20",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher",
				"VerticalGrip",
				"TacGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"ImprovisedSuppressor",
				"Suppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"DefaultIronsight_AR15",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 8,
	AutoShots = 8,
	Handling = -5,
	BulletDropRange = 17,
	Grouping = 62,
	BaseJamChance = -20,
	WeaponResource = 8500,
}

