UndefineClass('M1897')
DefineClass.M1897 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 6,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/M1897.png",
	DisplayName = T(363996539626, --[[ModItemInventoryItemCompositeDef M1897 DisplayName]] "M1897"),
	DisplayNamePlural = T(752169816926, --[[ModItemInventoryItemCompositeDef M1897 DisplayNamePlural]] "M1897"),
	Description = T(235310003929, --[[ModItemInventoryItemCompositeDef M1897 Description]] "Американцы - люди практичные, своевременно отвечающие вызовам времени. Нужно убивать врагов в окопах - выдадим солдату дробовик! У солдата кончились патроны - придадим к дробовику штык! И казалось бы, дядька пулемет давно отправил на свалку истории эти окопные мясорубки, но Легиону Гранд Чиена на занятиях политинформацией об этом рассказать забыли."),
	AdditionalHint = T(241195052187, --[[ModItemInventoryItemCompositeDef M1897 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дробовик \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неточный бой \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2500,
	CanAppearInShop = true,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 6,
	CritChanceScaled = 20,
	MagazineSize = 5,
	WeaponRange = 21,
	PointBlankBonus = 1,
	OverwatchAngle = 2160,
	BuckshotConeAngle = 180,
	BuckshotProjectiles = 1,
	BuckshotFalloffDamage = 10,
	Noise = 36,
	HandSlot = "TwoHanded",
	Entity = "M1897",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_DuckbillChoke",
				"JAZZ_FullChoke",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	WeaponMass = 36,
	CyclicRPM = 0,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 25,
	MaxAimActions = 2,
	BurstShots = 0,
	AutoShots = 0,

	CloseRange = 5,

	CloseRangeFactor = 90,
	BulletDropRange = 7,
	Grouping = 110,
	BaseJamChance = -10,
	WeaponResource = 600,
}

