UndefineClass('M1897')
DefineClass.M1897 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1+",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 50,
	Reliability = 30,
	Icon = "Mod/e6L4ECj/WeaponIcons/M1897.png",
	DisplayName = T(363996539626, --[[ModItemInventoryItemCompositeDef M1897 DisplayName]] "M1897"),
	DisplayNamePlural = T(752169816926, --[[ModItemInventoryItemCompositeDef M1897 DisplayNamePlural]] "M1897"),
	Description = T(235310003929, --[[ModItemInventoryItemCompositeDef M1897 Description]] "Американцы - люди практичные, своевременно отвечающие вызовам времени. Нужно убивать врагов в окопах - выдадим солдату дробовик! У солдата кончились патроны - придадим к дробовику штык! И казалось бы, дядька пулемет давно отправил на свалку истории эти окопные мясорубки, но Легиону Гранд Чиена на занятиях политинформацией об этом рассказать забыли."),
	AdditionalHint = T(241195052187, --[[ModItemInventoryItemCompositeDef M1897 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Помповый - высокие затраты од на выстрел"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2500,
	CanAppearInShop = true,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 15,
	MagazineSize = 5,
	WeaponRange = 21,
	PointBlankBonus = 1,
	OverwatchAngle = 2160,
	BuckshotConeAngle = 180,
	BuckshotFalloffDamage = 10,
	Noise = 36,
	HandSlot = "TwoHanded",
	Entity = "M1897",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"DuckbillChoke",
				"FullChoke",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 75,
	BulletDropRange = 7,
	Grouping = 110,
	BaseJamChance = -10,
	WeaponResource = 600,
}

