UndefineClass('M1A')
DefineClass.M1A = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "SniperRifle",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/M1A.png",
	ItemType = "DMR",
	DisplayName = T(877495623062, --[[ModItemInventoryItemCompositeDef M1A DisplayName]] "M1A"),
	DisplayNamePlural = T(477348066740, --[[ModItemInventoryItemCompositeDef M1A DisplayNamePlural]] "M1A"),
	Description = T(535323373272, --[[ModItemInventoryItemCompositeDef M1A Description]] "Самозарядная винтовка Springfield M1A. Выпускается в США для гражданского рынка, с полимерной ложей и 10-зарядным магазином. Конструктивно представляет собой винтовку М14, без режима автоматического огня."),
	AdditionalHint = T(341732095926, --[[ModItemInventoryItemCompositeDef M1A AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Улучшенная версия M14\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая надежность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 25000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 33,
	ObjDamageMod = 80,
	AimAccuracy = 34,
	CritChanceScaled = 30,
	MagazineSize = 20,
	WeaponRange = 58,
	OverwatchAngle = 900,
	Noise = 62,
	HandSlot = "TwoHanded",
	Entity = "M1A",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelShortImproved",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"StockHeavy",
				"StockNormal",
				"StockLight",
			},
			'DefaultComponent', "StockHeavy",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"GrenadeLauncher_M14",
				"TacGrip_M14",
				"VerticalGrip_M14",
				"Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"M14_Default_Muzzle",
				"Compensator",
				"ImprovisedSuppressor",
				"Suppressor",
				"SuppressorImproved",
			},
			'DefaultComponent', "M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LaserDot",
				"FlashlightDot",
				"UVDot",
				"Flashlight",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"HandguardM1ARail",
				"HandguardM1A",
			},
			'DefaultComponent', "HandguardM1A",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 55,
	BulletDropRange = 20,
	Grouping = 340,
	BaseJamChance = -30,
	WeaponResource = 4500,
}

