UndefineClass('M1A')
DefineClass.M1A = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "SniperRifle",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/M1A.png",
	DisplayName = T(877495623062, --[[ModItemInventoryItemCompositeDef M1A DisplayName]] "M1A"),
	DisplayNamePlural = T(477348066740, --[[ModItemInventoryItemCompositeDef M1A DisplayNamePlural]] "M1A"),
	Description = T(535323373272, --[[ModItemInventoryItemCompositeDef M1A Description]] "Самозарядная винтовка Springfield M1A. Выпускается в США для гражданского рынка, с полимерной ложей и 10-зарядным магазином. Конструктивно представляет собой винтовку М14, без режима автоматического огня."),
	AdditionalHint = T(341732095926, --[[ModItemInventoryItemCompositeDef M1A AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> М14 нормального человека"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 25000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 33,
	ObjDamageMod = 80,
	AimAccuracy = 14,
	CritChanceScaled = 30,
	MagazineSize = 20,
	WeaponRange = 65,
	OverwatchAngle = 900,
	Noise = 62,
	HandSlot = "TwoHanded",
	Entity = "M1A",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelShortImproved",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockHeavy",
				"JAZZ_StockNormal",
				"JAZZ_StockLight",
			},
			'DefaultComponent', "JAZZ_StockHeavy",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagNormalFine_M14",
				"JAZZ_MagSmall20_10_M14",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GrenadeLauncher_M14",
				"JAZZ_TacGrip_M14",
				"JAZZ_VerticalGrip_M14",
				"JAZZ_Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_M14_Default_Muzzle",
				"JAZZ_Compensator",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
			'DefaultComponent', "JAZZ_M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"JAZZ_HandguardM1ARail",
				"JAZZ_HandguardM1A",
			},
			'DefaultComponent', "JAZZ_HandguardM1A",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	BurstShots = 0,
	WeaponMass = 55,
	CyclicRPM = 0,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	Recoil = 22,
	AutoShots = 0,

	CloseRange = 12,

	CloseRangeFactor = 70,
	BulletDropRange = 19,
	Grouping = 59,
	BaseJamChance = -30,
	WeaponResource = 4500,
}

