UndefineClass('M21')
DefineClass.M21 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "SniperRifle",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/M21.png",
	DisplayName = T(502906359887, --[[ModItemInventoryItemCompositeDef M21 DisplayName]] "M-21"),
	DisplayNamePlural = T(838944198380, --[[ModItemInventoryItemCompositeDef M21 DisplayNamePlural]] "M-21"),
	Description = T(950654199607, --[[ModItemInventoryItemCompositeDef M21 Description]] "Американская армейская снайперская винтовка, представляет собой винтовку М14 со снятым переводчиком огня, и установленным оптическим прицелом. Дешево, сердито, эффективно."),
	AdditionalHint = T(341847967956, --[[ModItemInventoryItemCompositeDef M21 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> М14 с прицелом"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 11250,
	CanAppearInShop = false,
	Tier = 3,
	RestockWeight = 0,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 33,
	ObjDamageMod = 80,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 20,
	WeaponRange = 58,
	OverwatchAngle = 900,
	Noise = 63,
	HandSlot = "TwoHanded",
	Entity = "JAZZ_M14",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
            'SlotType', "Barrel",
            'Modifiable', false,
            'AvailableComponents', { "JAZZ_BarrelNormal" },
            'DefaultComponent', "JAZZ_BarrelNormal",
        }),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockHeavy",
				"JAZZ_StockNormal",
				"JAZZ_StockLight",
			},
			'DefaultComponent', "JAZZ_StockHeavy",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagSmall20_10_M14",
			},
			'DefaultComponent', "JAZZ_MagSmall20_10_M14",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GrenadeLauncher_M14",
				"JAZZ_TacGrip_M14",
				"JAZZ_VerticalGrip_M14",
				"JAZZ_Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_M14_Default_Muzzle",
				"JAZZ_Compensator",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
			'DefaultComponent', "JAZZ_M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Scope_M21_ART",
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_Scope_M21_ART",
		}),
	
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Rail",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Rail_M21",
			},
			'DefaultComponent', "JAZZ_Rail_M21",
		}),
},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 22,
	BurstShots = 0,
	AutoShots = 0,
	WeaponMass = 55,
	WeaponSizeClass = "Long",
	CloseRange = 16,
	CloseRangeFactor = 70,
	BulletDropRange = 17,
	Grouping = 45,
	BaseJamChance = -10,
	WeaponResource = 4000,
}

