UndefineClass('M3GreaseGun')
DefineClass.M3GreaseGun = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 1,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/M3GreaseGun.png",
	ItemType = "SMG",
	DisplayName = T(635674998872, --[[ModItemInventoryItemCompositeDef M3GreaseGun DisplayName]] "M3 Grease Gun"),
	DisplayNamePlural = T(954941893648, --[[ModItemInventoryItemCompositeDef M3GreaseGun DisplayNamePlural]] "M3 Grease Guns"),
	Description = T(941101439263, --[[ModItemInventoryItemCompositeDef M3GreaseGun Description]] 'Когда в условиях войны фрезеровать Томпсоны становится чересчур дорого, ВПК начинает выдавать вот таких вот ублюдков. А вы "ноктюрн сыграть смогли бы" на автоматах из водопроводных труб?'),
	AdditionalHint = T(740469872238, --[[ModItemInventoryItemCompositeDef M3GreaseGun AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неточный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Складной приклад \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Масленка без масла"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 500,
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_45ACP",
	Damage = 25,
	ObjDamageMod = 25,
	AimAccuracy = 5,
	CritChanceScaled = 30,
	MagazineSize = 30,
	OverwatchAngle = 4320,
	Noise = 36,
	HandSlot = "TwoHanded",
	Entity = "Grease",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	MaxAimActions = 2,
	Recoil = 8,
	BurstShots = 2,
	AutoShots = 5,
	Handling = -7,
	BulletDropRange = 8,
	Grouping = 38,
	WeaponResource = 4200,
}

