UndefineClass('M41Shotgun')
DefineClass.M41Shotgun = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T3-",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 10,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/M41.png",
	DisplayName = T(517967410302, --[[ModItemInventoryItemCompositeDef M41Shotgun DisplayName]] "M1014"),
	DisplayNamePlural = T(696989087809, --[[ModItemInventoryItemCompositeDef M41Shotgun DisplayNamePlural]] "M1014"),
	Description = T(484141046789, --[[ModItemInventoryItemCompositeDef M41Shotgun Description]] 'Самозарядный газоотводный дробовик 12-го калибра.  Введение в систему газового двигателя было необходимо после критической неудачи системы "инерционной автоматики", дробовика М3, которая просто напросто не работала на патронах со слабой навеской.'),
	AdditionalHint = T(616071689879, --[[ModItemInventoryItemCompositeDef M41Shotgun AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможность модификаций"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 32000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 20,
	MagazineSize = 6,
	WeaponRange = 24,
	PointBlankBonus = 1,
	OverwatchAngle = 1200,
	BuckshotConeAngle = 120,
	BuckshotFalloffDamage = 20,
	Noise = 32,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Benelli_M4",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelShortShotgun_Benelli",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"Buckshot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 3000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 75,
	BulletDropRange = 9,
	Grouping = 155,
	WeaponResource = 2400,
	CanAppearUsed = false,
}

