UndefineClass('M45')
DefineClass.M45 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 3,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/CarlGustaf.png",
	DisplayName = T(519964585006, --[[ModItemInventoryItemCompositeDef M45 DisplayName]] "Carl Gustaf M/45"),
	DisplayNamePlural = T(178177064561, --[[ModItemInventoryItemCompositeDef M45 DisplayNamePlural]] "Carl Gustaf M/45"),
	Description = T(562922376716, --[[ModItemInventoryItemCompositeDef M45 Description]] "Этот автомат хоть и выглядит, как продукт инженерии военного времени, сделанный из водопроводной трубы и листового металла, простоял на вооружении армии Швеции вплоть до начала 20-го века. И повезло ему, что пришлось просто стоять."),
	AdditionalHint = T(539332597589, --[[ModItemInventoryItemCompositeDef M45 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Складной приклад Карл!!!"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1700,
	CanAppearInShop = true,
	RestockWeight = 50,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 25,
	ObjDamageMod = 20,
	AimAccuracy = 7,
	MagazineSize = 32,
	WeaponRange = 26,
	OverwatchAngle = 4320,
	Noise = 32,
	HandSlot = "TwoHanded",
	Entity = "M45",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	WeaponMass = 80,
	CyclicRPM = 700,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	BurstShots = 4,
	Recoil = 18,
	AutoShots = 7,

	CloseRange = 2,

	CloseRangeFactor = 95,
	BulletDropRange = 12,
	Grouping = 55,
	BaseJamChance = -20,
	WeaponResource = 3800,
}

