UndefineClass('M4A1')
DefineClass.M4A1 = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "Carbine",
	ScrapParts = 10,
	RepairCost = 14,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/M4A1.png",
	DisplayName = T(464450575707, --[[ModItemInventoryItemCompositeDef M4A1 DisplayName]] "M4A1"),
	DisplayNamePlural = T(108497703803, --[[ModItemInventoryItemCompositeDef M4A1 DisplayNamePlural]] "M4A1"),
	Description = T(737944122811, --[[ModItemInventoryItemCompositeDef M4A1 Description]] "Основной карабин армии США и десятков других, и, скорее всего, останется им еще на долгое время, несмотря на неоднократно высказываемые претензии к недостаточной надежности в суровых условиях эксплуатации."),
	AdditionalHint = T(609073273191, --[[ModItemInventoryItemCompositeDef M4A1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Может стрелять в движении \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Универсальный обвес"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 27000,
	CanAppearInShop = true,
	Tier = 3,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 22,
	ObjDamageMod = 50,
	AimAccuracy = 11,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 42,
	OverwatchAngle = 1560,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "M4A1",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_IronSight",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_IronSight",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagSmall30_20",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_GrenadeLauncher",
				"JAZZ_VerticalGrip",
				"JAZZ_TacGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Compensator",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"AutoFire",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 10,
	BurstShots = 4,
	AutoShots = 8,

	CloseRange = 4,

	CloseRangeFactor = 90,
	BulletDropRange = 15,
	Grouping = 57,
	BaseJamChance = -10,
	WeaponResource = 8000,
}

