UndefineClass('M4Commando')
DefineClass.M4Commando = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Убираем",
	object_class = "SubmachineGun",
	ScrapParts = 10,
	Reliability = 80,
	Icon = "UI/Icons/Weapons/Commando",
	DisplayName = T(426920004036, --[[ModItemInventoryItemCompositeDef M4Commando DisplayName]] "ОТКЛЮЧЕНО"),
	DisplayNamePlural = T(903389608798, --[[ModItemInventoryItemCompositeDef M4Commando DisplayNamePlural]] "ОТКЛЮЧЕНО"),
	Description = T(346391822201, --[[ModItemInventoryItemCompositeDef M4Commando Description]] "How would you make a short barrel M16 work? Answer - lower muzzle velocity and huge muzzle flash."),
	AdditionalHint = T(682701716433, --[[ModItemInventoryItemCompositeDef M4Commando AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий шанс критического попадания\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Увеличенная эффективность прицеливания"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 8700,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "SubmachineGuns",
	Caliber = "556",
	AimAccuracy = 4,
	CritChanceScaled = 30,
	MagazineSize = 30,
	WeaponRange = 27,
	PointBlankBonus = 1,
	OverwatchAngle = 1440,
	Noise = 15,
	HandSlot = "TwoHanded",
	Entity = "Weapon_CAR15",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"Handguard_Commando",
				"JAZZ_VerticalGrip_Commando",
				"JAZZ_GrenadeLauncher_Commando",
			},
			'DefaultComponent', "Handguard_Commando",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagNormalFine",
				"JAZZ_MagLarge",
				"JAZZ_MagLargeFine",
				"JAZZ_MagQuick",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockNormal",
				"JAZZ_StockLight",
			},
			'DefaultComponent', "JAZZ_StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
			},
		}),
				PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Compensator",
				"JAZZ_MuzzleBooster",
				"JAZZ_Suppressor",
				"JAZZ_ImprovisedSuppressor",
			},
			'DefaultComponent', "JAZZ_Compensator",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 3000,
}

