UndefineClass('M60')
DefineClass.M60 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "MachineGun",
	ScrapParts = 16,
	RepairCost = 5,
	Reliability = 45,
	Icon = "Mod/e6L4ECj/WeaponIcons/M60.png",
	DisplayName = T(341695303297, --[[ModItemInventoryItemCompositeDef M60 DisplayName]] 'M60 "Свинья"'),
	DisplayNamePlural = T(391588411003, --[[ModItemInventoryItemCompositeDef M60 DisplayNamePlural]] 'M60 "Свиньи"'),
	Description = T(559259765691, --[[ModItemInventoryItemCompositeDef M60 Description]] "Американский единый пулемет, принятый на вооружение Армии и Флота США в 1957 году. Оказался не слишком удачным, что не помешало ему стать основным оружием поддержки американской пехоты в ходе войны во Вьетнаме. На безрыбье и свин - пулемет."),
	AdditionalHint = T(529371457427, --[[ModItemInventoryItemCompositeDef M60 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Единый пулемет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ненадежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый - ограничивает свободу движений"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Cost = 15000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 35,
	ObjDamageMod = 80,
	AimAccuracy = 12,
	MagazineSize = 100,
	WeaponRange = 55,
	OverwatchAngle = 600,
	Noise = 64,
	HandSlot = "TwoHanded",
	Entity = "M60",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
			'DefaultComponent', "JAZZ_Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
		"JAZZ_MGSuppressionFire",
	},
	ShootAP = 9000,
	ReloadAP = 9000,
	WeaponMass = 80,
	CyclicRPM = 700,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	Recoil = 22,
	BurstShots = 4,
	AutoShots = 0,

	CloseRange = 8,

	CloseRangeFactor = 85,
	BulletDropRange = 17,
	Grouping = 38,
	WeaponResource = 8000,
}

