UndefineClass('M60E3')
DefineClass.M60E3 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "MachineGun",
	ScrapParts = 16,
	RepairCost = 6,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/M60E3.png",
	DisplayName = T(566971066898, --[[ModItemInventoryItemCompositeDef M60E3 DisplayName]] "M60E3"),
	DisplayNamePlural = T(799534164629, --[[ModItemInventoryItemCompositeDef M60E3 DisplayNamePlural]] "M60E3"),
	Description = T(355056223930, --[[ModItemInventoryItemCompositeDef M60E3 Description]] "Современная модификация американского единого пулемета М60, отличается повышенной надежностью работы и исправлением ряда врожденных недостатков оригинала. Состоит в небольших количествах на вооружении Сил Специальных операций США."),
	AdditionalHint = T(992340160044, --[[ModItemInventoryItemCompositeDef M60E3 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Cost = 16000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 35,
	ObjDamageMod = 80,
	AimAccuracy = 27,
	MagazineSize = 100,
	WeaponRange = 56,
	OverwatchAngle = 600,
	Noise = 64,
	HandSlot = "TwoHanded",
	Entity = "M60E3",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Mount",
			'Modifiable', false,
			'AvailableComponents', {
				"M60E3HandGrip",
				"M60E4ModernMount",
			},
			'DefaultComponent', "M60E3HandGrip",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"LROptics",
				"LROpticsAdvanced",
				"ReflexSight",
				"ReflexSightAdvanced",
				"ScopeCOG",
				"ScopeCOGQuick",
				"ThermalScope",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 9000,
	ReloadAP = 9000,
	Recoil = 18,
	BurstShots = 5,
	AutoShots = 5,
	Handling = 42,
	BulletDropRange = 20,
	Grouping = 285,
	WeaponResource = 8500,
}

