UndefineClass('M72LAW')
DefineClass.M72LAW = {
	__parents = { "RocketLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "RocketLauncher",
	ScrapParts = 16,
	Repairable = false,
	Reliability = 98,
	Caliber = "JAZZ_Caliber_Warhead",
	Entity = "M72LAW2",
	DisplayName = T(162495707543, --[[ModItemInventoryItemCompositeDef M72LAW DisplayName]] "M72LAW2"),
	DisplayNamePlural = T(290561693953, --[[ModItemInventoryItemCompositeDef M72LAW DisplayNamePlural]] "M72LAW2"),
	Description = T(152357941079, --[[ModItemInventoryItemCompositeDef M72LAW Description]] "Изначально разработанный как противотанковое оружие, этот реактивный гранатомет сейчас используется против легкой техники, зданий и вообще всего, что не понравится оператору установки."),
	AdditionalHint = T(980300816631, --[[ModItemInventoryItemCompositeDef M72LAW AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Выстреливает снаряд, летящий по прямой до цели\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Наносит небольшой урон стоящим позади стрелка\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Вероятность неудачи растет с увеличением расстояния\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Громоздкое (нет бесплатного перемещения)"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Mechanical",
	Valuable = 1,
	Cost = 14000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "HeavyWeapons",
	Damage = 50,
	ObjDamageMod = 600,
	CritChanceScaled = 0,
	PenetrationClass = 2,
	WeaponRange = 45,
	HandSlot = "TwoHanded",
	fxClass = "RPG7",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 6000,
	ReloadAP = 4000,
	BackfireRange = 2,
	BackfireDamage = 8,
}

