UndefineClass('M72LAW')
DefineClass.M72LAW = {
	__parents = { "RocketLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "RocketLauncher",
	ScrapParts = 16,
	Repairable = false,
	DisposableLauncher = true,
	EmbeddedOrdnance = "Warhead_Frag",
	Reliability = 98,
	Caliber = "JAZZ_Caliber_Warhead",
	Entity = "M72LAW2",
	Icon = "Mod/e6L4ECj/WeaponIcons/M72LAW.png",
	DisplayName = T(162495707543, --[[ModItemInventoryItemCompositeDef M72LAW DisplayName]] "M72 LAW"),
	DisplayNamePlural = T(290561693953, --[[ModItemInventoryItemCompositeDef M72LAW DisplayNamePlural]] "M72 LAW"),
	Description = T(152357941079, --[[ModItemInventoryItemCompositeDef M72LAW Description]] "Одноразовый реактивный гранатомет с одним встроенным выстрелом. После пуска труба выбрасывается на землю."),
	AdditionalHint = T(980300816631, --[[ModItemInventoryItemCompositeDef M72LAW AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Одноразовый: не перезаряжается\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> После выстрела пустая труба падает на землю\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Выстреливает снаряд по прямой; опасная зона за спиной стрелка\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Вероятность неудачи растет с увеличением расстояния"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Mechanical",
	Valuable = 1,
	Cost = 9000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 45,
	CategoryPair = "HeavyWeapons",
	ObjDamageMod = 600,
	CritChanceScaled = 0,
	PenetrationClass = 2,
	WeaponRange = 45,
	Noise = 30,
	HandSlot = "TwoHanded",
	fxClass = "RPG7",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 9000,
	MagazineSize = 1,
	BackfireRange = 2,
	BackfireDamage = 8,
}

