UndefineClass('M79')
DefineClass.M79 = {
	__parents = { "GrenadeLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "GrenadeLauncher",
	ScrapParts = 16,
	RepairCost = 50,
	Reliability = 50,
	MinMishapChance = -5,
	MaxMishapChance = 40,
	MaxMishapRange = 6,
	MinMishapRange = 1,
	Caliber = "JAZZ_Caliber_40mmGrenade",
	AttackAP = 8000,
	BombardRadius = 3,
	ComponentSlots = {},
	Entity = "M79",
	Icon = "Mod/e6L4ECj/WeaponIcons/M79.png",
	DisplayName = T(971400395106, --[[ModItemInventoryItemCompositeDef M79 DisplayName]] "M79"),
	DisplayNamePlural = T(989047236569, --[[ModItemInventoryItemCompositeDef M79 DisplayNamePlural]] "M79"),
	Description = T(769570824531, --[[ModItemInventoryItemCompositeDef M79 Description]] 'Легендарный американский 40 мм пехотный гранатомет времен войны во Вьетнаме, являющийся пращуром современных "подствольников". На прикладе ножом в спешке вырезано "Джонни, они на деревьях!"'),
	AdditionalHint = T(397383171067, --[[ModItemInventoryItemCompositeDef M79 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> 40-мм гранатомет.
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> На близкой дистанции только разброс; шанс провала растёт с дальностью (Меткость + Взрывчатка)."),
	LargeItem = 1,
	UnitStat = "Explosives",
	Valuable = 1,
	Cost = 5000,
	CanAppearInShop = true,
	MaxStock = 1,
	RestockWeight = 20,
	CategoryPair = "HeavyWeapons",
	ObjDamageMod = 25,
	CritChanceScaled = 0,
	WeaponRange = 40,
	Noise = 30,
	HandSlot = "TwoHanded",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 7000,
	ReloadAP = 7000,
	Handling = 70,
	WeaponResource = 300,
}

