UndefineClass('MAC1950')
DefineClass.MAC1950 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-1",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 2,
	Icon = "Mod/e6L4ECj/WeaponIcons/MAC1950.png",
	DisplayName = T(890000000001150, --[[ModItemInventoryItemCompositeDef MAC1950 DisplayName]] "MAC Mle 1950"),
	DisplayNamePlural = T(890000000001290, --[[ModItemInventoryItemCompositeDef MAC1950 DisplayNamePlural]] "MAC Mle 1950"),
	Description = T(890000000000008, --[[ModItemInventoryItemCompositeDef MAC1950 Description]] "Послевоенный служебный и боевой пистолет, разработанный во французском Правительственном Арсенале. Представляет собой вполне неплохую конвертацию 1911 под патрон 9мм Люгер. Пистолеты mle 1950 были распространены в силовых структурах франции и колонии вплоть до конца 1980-х."),
	AdditionalHint = T(809154413425, --[[ModItemInventoryItemCompositeDef MAC1950 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ненадежный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Малый магазин\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Недальнобойный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Старый\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бесполезный"),
	UnitStat = "Marksmanship",
	Cost = 1100,
	CanAppearInShop = false,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 16,
	ObjDamageMod = 20,
	AimAccuracy = 8,
	CritChanceScaled = 35,
	MagazineSize = 8,
	WeaponRange = 17,
	OverwatchAngle = 5400,
	Noise = 22,
	Entity = "MAC1950",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_13_PISTOL_52",
				"JAZZ_MagLarge_8_PISTOL_52",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
								"JAZZ_ImprovisedSuppressor",
								"JAZZ_Suppressor",
							},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
			},
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	MaxAimActions = 2,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 5,
	Grouping = 40,
	BaseJamChance = -20,
	WeaponResource = 350,
}

