UndefineClass('Machete_Sharpened')
DefineClass.Machete_Sharpened = {
	__parents = { "MacheteWeapon" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "MacheteWeapon",
	ScrapParts = 2,
	Reliability = 50,
	Icon = "UI/Icons/Weapons/Machete",
	SubIcon = "UI/Icons/Weapons/sharpened",
	DisplayName = T(308289656110, --[[ModItemInventoryItemCompositeDef Machete_Sharpened DisplayName]] "Заточенное мачете"),
	DisplayNamePlural = T(269336377425, --[[ModItemInventoryItemCompositeDef Machete_Sharpened DisplayNamePlural]] "Заточенные мачете"),
	Description = T(559511805609, --[[ModItemInventoryItemCompositeDef Machete_Sharpened Description]] "Хозяйственный инструмент для прокладывания дороги через джунги, рубки тростника или бананов. Или людей."),
	AdditionalHint = T(433580785416, --[[ModItemInventoryItemCompositeDef Machete_Sharpened AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Увеличенный доп. урон от силы\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Заточенное: высокий урон"),
	LargeItem = 1,
	UnitStat = "Dexterity",
	Cost = 1300,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 2,
	RestockWeight = 15,
	CategoryPair = "MeleeWeapons",
	BaseChanceToHit = 100,
	CritChance = 5,
	BaseDamage = 25,
	AimAccuracy = 15,
	PenetrationClass = 4,
	DamageMultiplier = 150,
	WeaponRange = 0,
	Charge = true,
	AttackAP = 4000,
	MaxAimActions = 1,
	Noise = 1,
	NeckAttackType = "lethal",
	Entity = "Weapon_Machete_03",
	HolsterSlot = "Shoulder",
	CanAppearUsed = false,
}

