UndefineClass('Machete_Balanced')
DefineClass.Machete_Balanced = {
	__parents = { "MacheteWeapon" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "MacheteWeapon",
	ScrapParts = 2,
	Reliability = 50,
	Icon = "UI/Icons/Weapons/Machete",
	SubIcon = "UI/Icons/Weapons/balanced",
	DisplayName = T(327581548846, "Сбалансирован. мачете"),
	DisplayNamePlural = T(485784855197, "Сбалансирован. мачете"),
	Description = T(918310176002, "Хозяйственный инструмент для прокладывания дороги через джунги, рубки тростника или бананов. Или людей."),
	AdditionalHint = T(647226077950, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Увеличенный доп. урон от силы \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сбалансированное: увеличенная эффективность прицеливания"),
	LargeItem = 1,
	UnitStat = "Dexterity",
	Cost = 1300,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 15,
	CategoryPair = "MeleeWeapons",
	BaseChanceToHit = 100,
	CritChanceScaled = 20,
	BaseDamage = 17,
	AimAccuracy = 20,
	PenetrationClass = 4,
	DamageMultiplier = 150,
	WeaponRange = 0,
	Charge = true,
	AttackAP = 4000,
	MaxAimActions = 1,
	Noise = 1,
	NeckAttackType = "lethal",
	Entity = "Weapon_Machete_03",
	HolsterSlot = "Shoulder",
	CanAppearUsed = false,
}

