UndefineClass('Makarov')
DefineClass.Makarov = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-3",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 5,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/Makarov.png",
	DisplayName = T(890000000000220, --[[ModItemInventoryItemCompositeDef Makarov DisplayName]] "Пистолет Макарова"),
	DisplayNamePlural = T(890000000001088, --[[ModItemInventoryItemCompositeDef Makarov DisplayNamePlural]] "Пистолеты Макарова"),
	Description = T(413605184956, --[[ModItemInventoryItemCompositeDef Makarov Description]] "Самый известный советский и российский пистолет. В современных реалиях его принято ругать, но чаще всего это делают те, кто стреляет разве что в монстров с экрана монитора."),
	AdditionalHint = T(890000000000100, --[[ModItemInventoryItemCompositeDef Makarov AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Малый магазин\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Открывает пиво"),
	UnitStat = "Marksmanship",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 1,
	RestockWeight = 125,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x18",
	Damage = 18,
	ObjDamageMod = 15,
	AimAccuracy = 5,
	CritChanceScaled = 35,
	MagazineSize = 8,
	WeaponRange = 15,
	OverwatchAngle = 5400,
	Noise = 18,
	Entity = "Makarov",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
			},
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	MaxAimActions = 2,
	Recoil = 14,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 6,
	Grouping = 72,
	BaseJamChance = -100,
	WeaponResource = 3000,
}

