UndefineClass('MAS36')
DefineClass.MAS36 = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "BattleRifle",
	ScrapParts = 8,
	RepairCost = 3,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/MAS36.png",
	DisplayName = T(890000000000482, --[[ModItemInventoryItemCompositeDef MAS36 DisplayName]] "MAS36"),
	DisplayNamePlural = T(890000000001116, --[[ModItemInventoryItemCompositeDef MAS36 DisplayNamePlural]] "MAS36"),
	Description = T(890000000000005, --[[ModItemInventoryItemCompositeDef MAS36 Description]] "Линейная пехотная винтовка производства Франции периода ВМВ, была разработана в 1930-х годах, что делает ее относительной новинкой в сравнении с винтовками Мосина, Маузера, Ли Энфильда и Спрингфилда. Но, как известно, особой конкуренции Маузерам у нее составить не получилось."),
	AdditionalHint = T(890000000000124, --[[ModItemInventoryItemCompositeDef MAS36 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Винтовка с ручным перезаряжанием \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный Медленно стреляет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дед сдавался"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_75French",
	Damage = 38,
	ObjDamageMod = 80,
	AimAccuracy = 11,
	CritChanceScaled = 50,
	MagazineSize = 5,
	WeaponRange = 57,
	OverwatchAngle = 420,
	Noise = 59,
	HandSlot = "TwoHanded",
	Entity = "MAS36",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_Salvo",
	},
	ShootAP = 8000,
	ReloadAP = 5000,
	BurstShots = 0,
	WeaponMass = 36,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 11,

	CloseRangeFactor = 80,
	BulletDropRange = 17,
	Grouping = 40,
	WeaponResource = 7000,
}

