UndefineClass('MAS49')
DefineClass.MAS49 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "SniperRifle",
	ScrapParts = 8,
	RepairCost = 6,
	Reliability = 55,
	Icon = "Mod/e6L4ECj/WeaponIcons/MAS49.png",
	DisplayName = T(729447298300, --[[ModItemInventoryItemCompositeDef MAS49 DisplayName]] "MAS-49/56"),
	DisplayNamePlural = T(830429456946, --[[ModItemInventoryItemCompositeDef MAS49 DisplayNamePlural]] "MAS-49/56"),
	Description = T(789944142367, --[[ModItemInventoryItemCompositeDef MAS49 Description]] "После Второй Мировой Войны деоккупированная Франция нуждалась в новом современном оружии, и еще в 1944 году была разработана и выпущена первая партия этих винтовок с газовым двигателем с прямым отводом пороховых газов (да, как в AR-15 потом). Практически сразу им пришлось повоевать в Индокитае и Вьетнаме, с неплохими отзывами по надежности и кучности боя."),
	AdditionalHint = T(546051968989, --[[ModItemInventoryItemCompositeDef MAS49 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Низкие од на выстрел\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Низкая точность прицельной стрельбы\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможность стрельбы на бегу"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2000,
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_75French",
	Damage = 36,
	ObjDamageMod = 80,
	AimAccuracy = 29,
	CritChanceScaled = 30,
	MagazineSize = 10,
	WeaponRange = 55,
	OverwatchAngle = 1320,
	Noise = 68,
	HandSlot = "TwoHanded",
	Entity = "MAS49",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 50,
	BulletDropRange = 23,
	Grouping = 260,
	WeaponResource = 4000,
}

