UndefineClass('MAS49')
DefineClass.MAS49 = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "BattleRifle",
	ScrapParts = 8,
	RepairCost = 6,
	Reliability = 55,
	Icon = "Mod/e6L4ECj/WeaponIcons/MAS49.png",
	DisplayName = T(890000000000974, --[[ModItemInventoryItemCompositeDef MAS49 DisplayName]] "MAS-49/56"),
	DisplayNamePlural = T(890000000001123, --[[ModItemInventoryItemCompositeDef MAS49 DisplayNamePlural]] "MAS-49/56"),
	Description = T(890000000001050, --[[ModItemInventoryItemCompositeDef MAS49 Description]] "После Второй Мировой Войны деоккупированная Франция нуждалась в новом современном оружии, и еще в 1944 году была разработана и выпущена первая партия этих винтовок с газовым двигателем с прямым отводом пороховых газов (да, как в AR-15 потом). Практически сразу им пришлось повоевать в Индокитае и Вьетнаме, с неплохими отзывами по надежности и кучности боя."),
	AdditionalHint = T(890000000000692, --[[ModItemInventoryItemCompositeDef MAS49 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Средняя по всем показателям винтовка"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2000,
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_75French",
	Damage = 36,
	ObjDamageMod = 80,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 10,
	WeaponRange = 58,
	OverwatchAngle = 1320,
	Noise = 68,
	HandSlot = "TwoHanded",
	Entity = "MAS49",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_Salvo",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	BurstShots = 1,
	AutoShots = 1,

	CloseRange = 8,

	CloseRangeFactor = 80,
	BulletDropRange = 16,
	Grouping = 44,
	WeaponResource = 4000,
}

