UndefineClass('MG42')
DefineClass.MG42 = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "MachineGun",
	ScrapParts = 12,
	RepairCost = 3,
	Icon = "Mod/e6L4ECj/WeaponIcons/MG42.png",
	DisplayName = T(389483103177, --[[ModItemInventoryItemCompositeDef MG42 DisplayName]] "MG42"),
	DisplayNamePlural = T(734302797284, --[[ModItemInventoryItemCompositeDef MG42 DisplayNamePlural]] "MG42"),
	Description = T(180798552012, --[[ModItemInventoryItemCompositeDef MG42 Description]] "Благодаря невероятному темпу стрельбы MG42 позволяет максимально эффективно вести огонь на подавление. Дедушка старый, но дедушка - немец."),
	AdditionalHint = T(128714866748, --[[ModItemInventoryItemCompositeDef MG42 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая скорострельность"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Cost = 3000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_792",
	Damage = 36,
	ObjDamageMod = 60,
	AimAccuracy = 22,
	MagazineSize = 50,
	WeaponRange = 54,
	OverwatchAngle = 600,
	Noise = 72,
	HandSlot = "TwoHanded",
	Entity = "Weapon_MG42",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'Modifiable', false,
			'AvailableComponents', {
				"Bipod_MG42",
			},
			'DefaultComponent', "Bipod_MG42",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 9000,
	ReloadAP = 8000,
	Recoil = 20,
	BurstShots = 12,
	AutoShots = 12,
	Handling = 33,
	BulletDropRange = 25,
	Grouping = 290,
	BaseJamChance = 3,
	WeaponResource = 6000,
}

