UndefineClass('MGL')
DefineClass.MGL = {
	__parents = { "GrenadeLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeLauncher",
	ScrapParts = 16,
	Reliability = 50,
	Caliber = "JAZZ_Caliber_40mmGrenade",
	AttackAP = 4000,
	BombardRadius = 3,
	ComponentSlots = {},
	Entity = "Weapon_MilkorMGL",
	Icon = "UI/Icons/Weapons/weapon_MGL",
	DisplayName = T(652294375588, --[[ModItemInventoryItemCompositeDef MGL DisplayName]] "MGL"),
	DisplayNamePlural = T(111923304462, --[[ModItemInventoryItemCompositeDef MGL DisplayNamePlural]] "MGL"),
	Description = T(872562014733, --[[ModItemInventoryItemCompositeDef MGL Description]] "Шестизарядный револьверный гранатомет производства ЮАР. Максимально широко распространен по всему миру. Максимально широко распространяет других людей."),
	AdditionalHint = T(876312872911, --[[ModItemInventoryItemCompositeDef MGL AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Стреляет дальнобойными 40-мм гранатами\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Вероятность неудачи растет с увеличением расстояния\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Громоздкое (нет бесплатного перемещения)"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Explosives",
	Valuable = 1,
	Cost = 55000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 20,
	CategoryPair = "HeavyWeapons",
	ObjDamageMod = 25,
	CritChanceScaled = 0,
	MagazineSize = 6,
	WeaponRange = 45,
	HandSlot = "TwoHanded",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 4000,
	ReloadAP = 6000,
	Handling = 80,
}

