UndefineClass('MGL')
DefineClass.MGL = {
	__parents = { "GrenadeLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "GrenadeLauncher",
	ScrapParts = 16,
	Reliability = 50,
	MinMishapChance = -5,
	MaxMishapChance = 40,
	MaxMishapRange = 6,
	MinMishapRange = 1,
	Caliber = "JAZZ_Caliber_40mmGrenade",
	AttackAP = 5000,
	BombardRadius = 3,
	ComponentSlots = {},
	Entity = "Weapon_MilkorMGL",
	Icon = "UI/Icons/Weapons/weapon_MGL",
	DisplayName = T(778467383249, --[[ModItemInventoryItemCompositeDef MGL DisplayName]] "MGL"),
	DisplayNamePlural = T(429606722516, --[[ModItemInventoryItemCompositeDef MGL DisplayNamePlural]] "MGLs"),
	Description = T(872562014733, --[[ModItemInventoryItemCompositeDef MGL Description]] "Шестизарядный револьверный гранатомет производства ЮАР. Максимально широко распространен по всему миру. Максимально широко распространяет других людей."),
	AdditionalHint = T(876312872911, --[[ModItemInventoryItemCompositeDef MGL AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> 40-мм гранатомет. \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Шанс промаха увеличивается с расстоянием. \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый - ограничивает свободу движений"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Explosives",
	Valuable = 1,
	Cost = 55000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	RestockWeight = 20,
	CategoryPair = "HeavyWeapons",
	ObjDamageMod = 25,
	CritChanceScaled = 0,
	MagazineSize = 6,
	WeaponRange = 40,
	Noise = 30,
	HandSlot = "TwoHanded",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 5000,
	ReloadAP = 10000,
	WeaponResource = 250,
}

