UndefineClass('MicroUZI')
DefineClass.MicroUZI = {
	__parents = { "Autopistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "Autopistol",
	ScrapParts = 6,
	RepairCost = 5,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/MicroUZI.png",
	DisplayName = T(551535604372, --[[ModItemInventoryItemCompositeDef MicroUZI DisplayName]] "Мини Узи"),
	DisplayNamePlural = T(492773756154, --[[ModItemInventoryItemCompositeDef MicroUZI DisplayNamePlural]] "Мини Узи"),
	Description = T(111329132858, --[[ModItemInventoryItemCompositeDef MicroUZI Description]] 'Максимально компактный и скорострельный израильский пистолет-пулемет. На тот случай, если вы должны кому-то денег и "гости" приехали на лифте. Не сметь работать в шабат!'),
	AdditionalHint = T(305727013459, --[[ModItemInventoryItemCompositeDef MicroUZI AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Одноручный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Складной приклад\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Скорострельный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> УЗИшка"),
	UnitStat = "Marksmanship",
	Cost = 2200,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 20,
	ObjDamageMod = 20,
	AimAccuracy = 8,
	MagazineSize = 20,
	WeaponRange = 19,
	OverwatchAngle = 4920,
	Noise = 28,
	Entity = "Weapon_Uzi",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelNormalImproved",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagDrum_30_50_UZI",
				"JAZZ_MagLarge_20_30_UZI",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Pistol",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Compensator",
				"JAZZ_PistolSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"JAZZ_Freeswap",
			},
			'DefaultComponent', "JAZZ_Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"DualShot",
		"JAZZ_SmgStorm",
		"JAZZ_RunAndSMGStorm",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	WeaponMass = 27,
	CyclicRPM = 1200,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	MaxAimActions = 2,
	Recoil = 21,
	BurstShots = 6,
	AutoShots = 12,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 6,
	Grouping = 55,
	BaseJamChance = -10,
	WeaponResource = 2500,
}

