UndefineClass('Mini14')
DefineClass.Mini14 = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "Carbine",
	ScrapParts = 10,
	RepairCost = 8,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/Mini14.png",
	DisplayName = T(890000000000977, --[[ModItemInventoryItemCompositeDef Mini14 DisplayName]] "Мини-14"),
	DisplayNamePlural = T(890000000000936, --[[ModItemInventoryItemCompositeDef Mini14 DisplayNamePlural]] "Мини-14"),
	Description = T(250336798974, --[[ModItemInventoryItemCompositeDef Mini14 Description]] "Облегченный уменьшенный карабин на базе армейской винтовки М14, максимально доступен для гражданского стрелка - от охоты и самообороны, до обучения стрельбе в тире. Валовый карабин требует серьезной доводки напильником."),
	AdditionalHint = T(873632115793, --[[ModItemInventoryItemCompositeDef Mini14 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Может стрелять в движении \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Можно переделать в автомат \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 7500,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 25,
	ObjDamageMod = 50,
	AimAccuracy = 10,
	CritChanceScaled = 20,
	MagazineSize = 20,
	WeaponRange = 48,
	OverwatchAngle = 1200,
	Noise = 50,
	HandSlot = "TwoHanded",
	Entity = "Mini14",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelShort",
				"JAZZ_BarrelNormal",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_20_30_MINI14",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Trigger",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Autofire",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	WeaponMass = 30,
	CyclicRPM = 750,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	Recoil = 22,
	BurstShots = 4,
	AutoShots = 8,

	CloseRange = 5,

	CloseRangeFactor = 90,
	BulletDropRange = 16,
	Grouping = 61,
	BaseJamChance = -10,
	WeaponResource = 6000,
}

