UndefineClass('Mini14')
DefineClass.Mini14 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "SniperRifle",
	ScrapParts = 10,
	RepairCost = 8,
	Reliability = 45,
	Icon = "Mod/e6L4ECj/WeaponIcons/Mini14.png",
	ItemType = "DMR",
	DisplayName = T(732531674185, --[[ModItemInventoryItemCompositeDef Mini14 DisplayName]] "Мини-14"),
	DisplayNamePlural = T(707630654921, --[[ModItemInventoryItemCompositeDef Mini14 DisplayNamePlural]] "Мини-14"),
	Description = T(250336798974, --[[ModItemInventoryItemCompositeDef Mini14 Description]] "Облегченный уменьшенный карабин на базе армейской винтовки М14, максимально доступен для гражданского стрелка - от охоты и самообороны, до обучения стрельбе в тире. Валовый карабин требует серьезной доводки напильником."),
	AdditionalHint = T(873632115793, --[[ModItemInventoryItemCompositeDef Mini14 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая эффективность как прицельной стрельбы, так и навскидку\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможность стрельбы на бегу"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 7500,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 22,
	CritChanceScaled = 20,
	MagazineSize = 20,
	WeaponRange = 48,
	OverwatchAngle = 1500,
	Noise = 50,
	HandSlot = "TwoHanded",
	Entity = "Mini14",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelShort",
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_20_30",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 5000,
	ReloadAP = 4000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 70,
	BulletDropRange = 16,
	Grouping = 275,
	BaseJamChance = -10,
	WeaponResource = 6000,
}

