UndefineClass('MK14EBR')
DefineClass.MK14EBR = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1 - JAZZ-WEAPON-M14-FAMILY-001",
	object_class = "BattleRifle",
	ScrapParts = 10,
	RepairCost = 10,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/MK14EBR.png",
	DisplayName = T(990002710, --[[ModItemInventoryItemCompositeDef MK14EBR DisplayName]] "Mk 14 EBR"),
	DisplayNamePlural = T(990002711, --[[ModItemInventoryItemCompositeDef MK14EBR DisplayNamePlural]] "Mk 14 EBR"),
	Description = T(990002712, --[[ModItemInventoryItemCompositeDef MK14EBR Description]] "Mk 14 EBR на шасси Sage: пистолетная рукоять, складной AR-приклад и рейки. Тот же 7.62x51, но уже не ложка USGI."),
	AdditionalHint = T(990002713, --[[ModItemInventoryItemCompositeDef MK14EBR AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Современное шасси \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Очередь и авто"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 20000,
	CanAppearInShop = true,
	Tier = 4,
	RestockWeight = 25,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 33,
	ObjDamageMod = 80,
	AimAccuracy = 10,
	MagazineSize = 20,
	WeaponRange = 62,
	OverwatchAngle = 960,
	Noise = 65,
	HandSlot = "TwoHanded",
	Entity = "MK14EBR",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
            'SlotType', "Barrel",
            'Modifiable', false,
            'AvailableComponents', { "JAZZ_BarrelNormal" },
            'DefaultComponent', "JAZZ_BarrelNormal",
        }),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockHeavy",
				"JAZZ_StockNormal",
				"JAZZ_StockLight",
			},
			'DefaultComponent', "JAZZ_StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagSmall20_10_M14",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				
				"JAZZ_TacGrip_M14",
				"JAZZ_VerticalGrip_M14",
				"JAZZ_Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_M14_Default_Muzzle",
				"JAZZ_Compensator",
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
			},
			'DefaultComponent', "JAZZ_M14_Default_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = false,
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_Salvo",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	Recoil = 28,
	BurstShots = 4,
	AutoShots = 7,
	WeaponMass = 36,
	CyclicRPM = 700,
	CloseRange = 11,
	CloseRangeFactor = 80,
	BulletDropRange = 17,
	Grouping = 41,
	WeaponResource = 4500,
}
