UndefineClass('Molotov')
DefineClass.Molotov = {
	__parents = { "GrenadeItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/Molotov",
	ItemType = "GrenadeFire",
	DisplayName = T(859195155732, --[[ModItemInventoryItemCompositeDef Molotov DisplayName]] "Коктейль Молотова"),
	DisplayNamePlural = T(112407563606, --[[ModItemInventoryItemCompositeDef Molotov DisplayNamePlural]] "Коктейли Молотова"),
	AdditionalHint = T(992551372753, --[[ModItemInventoryItemCompositeDef Molotov AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Воспламеняет место попадания и вызывает у целей <color EmStyle>горение</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая вероятность неудачи"),
	UnitStat = "Explosives",
	Cost = 150,
	CanAppearInShop = true,
	RestockWeight = 50,
	CategoryPair = "Grenade",
	MaxStacks = 3,
	MinMishapChance = 2,
	MaxMishapChance = 60,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaOfEffect = 2,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 25,
	Scatter = 6,
	BaseRange = 1,
	ThrowMaxRange = 20,
	CanBounce = false,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 0,
	aoeType = "fire",
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/molotov",
}

