UndefineClass('Mosin')
DefineClass.Mosin = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "SniperRifle",
	ScrapParts = 8,
	RepairCost = 3,
	Reliability = 90,
	Icon = "Mod/e6L4ECj/WeaponIcons/Mosin.png",
	DisplayName = T(890000000000481, --[[ModItemInventoryItemCompositeDef Mosin DisplayName]] "Винтовка Мосина"),
	DisplayNamePlural = T(890000000001115, --[[ModItemInventoryItemCompositeDef Mosin DisplayNamePlural]] "Винтовки Мосина"),
	Description = T(890000000000004, --[[ModItemInventoryItemCompositeDef Mosin Description]] "Основная винтовка советского солдата РККА во время ВОВ. Максимально стрательно была приведена к вариации СН - снят штык, загнута вниз рукоять затвора, приварено посадочное место для прицела. Однако, отсутствие маркировки на стволе выдает самозванку."),
	AdditionalHint = T(890000000000125, --[[ModItemInventoryItemCompositeDef Mosin AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Винтовка с ручным перезаряжанием \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Медленно стреляет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дед воевал"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	CategoryPair = "Rifles",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x54R",
	Damage = 40,
	ObjDamageMod = 80,
	AimAccuracy = 13,
	CritChanceScaled = 50,
	MagazineSize = 5,
	WeaponRange = 66,
	OverwatchAngle = 420,
	Noise = 59,
	HandSlot = "TwoHanded",
	Entity = "Mosin",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Scope_PU",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 8000,
	ReloadAP = 5000,
	BurstShots = 0,
	WeaponMass = 55,
	CyclicRPM = 0,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 12,

	CloseRangeFactor = 70,
	BulletDropRange = 16,
	Grouping = 41,
	WeaponResource = 7000,
}

