UndefineClass('MP40')
DefineClass.MP40 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 2,
	Reliability = 10,
	Icon = "Mod/e6L4ECj/WeaponIcons/MP40.png",
	DisplayName = T(808281336477, --[[ModItemInventoryItemCompositeDef MP40 DisplayName]] "MP40"),
	DisplayNamePlural = T(135534176285, --[[ModItemInventoryItemCompositeDef MP40 DisplayNamePlural]] "MP40"),
	Description = T(313702671802, --[[ModItemInventoryItemCompositeDef MP40 Description]] "Изначально разработанный для использования экипажами техники и десантниками, MP40 раскрыл свои лучшие качества надежного пистолета-пулемета в городских боях на Восточном фронте."),
	AdditionalHint = T(799661559477, --[[ModItemInventoryItemCompositeDef MP40 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ржавый\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 500,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 21,
	ObjDamageMod = 20,
	AimAccuracy = 8,
	MagazineSize = 32,
	WeaponRange = 25,
	OverwatchAngle = 4080,
	Noise = 32,
	HandSlot = "TwoHanded",
	Entity = "Weapon_MP40",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	Recoil = 4,
	BurstShots = 2,
	AutoShots = 5,
	Handling = -3,
	BulletDropRange = 10,
	Grouping = 32,
	BaseJamChance = 30,
	WeaponResource = 1600,
}

