UndefineClass('MP40')
DefineClass.MP40 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 2,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/MP40.png",
	DisplayName = T(623210280984, --[[ModItemInventoryItemCompositeDef MP40 DisplayName]] "MP40"),
	DisplayNamePlural = T(925856619983, --[[ModItemInventoryItemCompositeDef MP40 DisplayNamePlural]] "MP40s"),
	Description = T(107317552821, --[[ModItemInventoryItemCompositeDef MP40 Description]] "Initially designed for vehicle crews and paratroopers, It really became widely used when the brutal urban combat of the Eastern front showed the value of a reliable submachine gun. "),
	AdditionalHint = T(799661559477, --[[ModItemInventoryItemCompositeDef MP40 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Старый Немецкий Шмайссер (нет)"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 500,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 18,
	ObjDamageMod = 20,
	AimAccuracy = 15,
	MagazineSize = 32,
	WeaponRange = 25,
	OverwatchAngle = 4080,
	Noise = 32,
	HandSlot = "TwoHanded",
	Entity = "Weapon_MP40",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	MaxAimActions = 2,
	Recoil = 4,
	BurstShots = 2,
	AutoShots = 5,

	CloseRange = 2,

	CloseRangeFactor = 95,
	BulletDropRange = 9,
	Grouping = 32,
	BaseJamChance = 30,
	WeaponResource = 1600,
}

