UndefineClass('MP5A2')
DefineClass.MP5A2 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 12,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/MP5A2.png",
	DisplayName = T(626772068936, --[[ModItemInventoryItemCompositeDef MP5A2 DisplayName]] "MP5A2"),
	DisplayNamePlural = T(617919327732, --[[ModItemInventoryItemCompositeDef MP5A2 DisplayNamePlural]] "MP5A2"),
	Description = T(249894199741, --[[ModItemInventoryItemCompositeDef MP5A2 Description]] "Устаревший вариант немецкого автомата MP5, с УСМ без отсечки стрельбы по три выстрела. Один из самых распространенных полицейских автоматов в мире до сих пор. Отличный выбор для специальных операций любого толка, тысячи обезвреженных террористов по всему миру не дадут соврать."),
	AdditionalHint = T(850293537191, --[[ModItemInventoryItemCompositeDef MP5A2 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный "),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 60,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 23,
	ObjDamageMod = 20,
	AimAccuracy = 12,
	MagazineSize = 30,
	WeaponRange = 30,
	OverwatchAngle = 4320,
	Noise = 28,
	HandSlot = "TwoHanded",
	Entity = "MP5A2",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_50_MP5",
				"JAZZ_MagQuick_MP5",
				"JAZZ_MagSmall30_15_MP5",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Eotech",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_PistolSuppressor",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	WeaponMass = 31,
	CyclicRPM = 800,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	Recoil = 14,
	BurstShots = 4,
	AutoShots = 8,
	BulletDropRange = 10,

	CloseRange = 2,

	CloseRangeFactor = 95,
	Grouping = 62,
	BaseJamChance = -30,
	WeaponResource = 5000,
	CanAppearUsed = false,
}

