UndefineClass('MP5A2')
DefineClass.MP5A2 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "9mm T2",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/MP5A2.png",
	DisplayName = T(626772068936, --[[ModItemInventoryItemCompositeDef MP5A2 DisplayName]] "MP5A2"),
	DisplayNamePlural = T(617919327732, --[[ModItemInventoryItemCompositeDef MP5A2 DisplayNamePlural]] "MP5A2"),
	Description = T(249894199741, --[[ModItemInventoryItemCompositeDef MP5A2 Description]] "Устаревший вариант немецкого автомата MP5, с УСМ без отсечки стрельбы по три выстрела. Один из самых распространенных полицейских автоматов в мире до сих пор. Отличный выбор для специальных операций любого толка, тысячи обезвреженных террористов по всему миру не дадут соврать."),
	AdditionalHint = T(850293537191, --[[ModItemInventoryItemCompositeDef MP5A2 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 60,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 21,
	ObjDamageMod = 20,
	AimAccuracy = 13,
	MagazineSize = 30,
	WeaponRange = 30,
	OverwatchAngle = 4320,
	Noise = 22,
	HandSlot = "TwoHanded",
	Entity = "MP5A2",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagSmall30_15",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Eotech",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"PistolSuppressor",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	Recoil = 3,
	BurstShots = 4,
	AutoShots = 8,
	Handling = 90,
	BulletDropRange = 11,
	Grouping = 85,
	BaseJamChance = -30,
	WeaponResource = 11000,
	CanAppearUsed = false,
}

