UndefineClass('MP5A4')
DefineClass.MP5A4 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "9mm T2",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/MP5A4.png",
	DisplayName = T(123316525310, --[[ModItemInventoryItemCompositeDef MP5A4 DisplayName]] "MP5A4"),
	DisplayNamePlural = T(897337319220, --[[ModItemInventoryItemCompositeDef MP5A4 DisplayNamePlural]] "MP5A4"),
	Description = T(903859276526, --[[ModItemInventoryItemCompositeDef MP5A4 Description]] "Современный вариант автомата MP5, допускающий стрельбу как с отсечкой по три выстрела, так и полностью автоматический огонь. Все остальное осталось практически без изменений, автомат сразу хорошим получился."),
	AdditionalHint = T(545249677427, --[[ModItemInventoryItemCompositeDef MP5A4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Встроенный фонарик"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 7000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 60,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 21,
	ObjDamageMod = 20,
	AimAccuracy = 13,
	MagazineSize = 30,
	WeaponRange = 22,
	OverwatchAngle = 4320,
	Noise = 30,
	HandSlot = "TwoHanded",
	Entity = "MP5A4",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagSmall30_15",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Eotech",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"PistolSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
				"StockNormal",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
			},
			'DefaultComponent', "Flashlight",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	Recoil = 3,
	AutoShots = 8,
	Handling = 92,
	BulletDropRange = 11,
	Grouping = 85,
	BaseJamChance = -30,
	CanAppearUsed = false,
}

