UndefineClass('MP5K')
DefineClass.MP5K = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 12,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/MP5K2.png",
	DisplayName = T(271982946642, --[[ModItemInventoryItemCompositeDef MP5K DisplayName]] "MP5K"),
	DisplayNamePlural = T(879832194807, --[[ModItemInventoryItemCompositeDef MP5K DisplayNamePlural]] "MP5Ks"),
	Description = T(254086057863, --[[ModItemInventoryItemCompositeDef MP5K Description]] "Brutally short MP5 designed for close quarters engagements and personal defense. There is even a suitcase with a trigger on the handle for covert escort jobs."),
	AdditionalHint = T(713555595193, --[[ModItemInventoryItemCompositeDef MP5K AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Больше не одноручный (по просьбе Ливси)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Без приклада\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> MP5-Короткий"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 4200,
	CanAppearInShop = true,
	RestockWeight = 40,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 22,
	ObjDamageMod = 20,
	AimAccuracy = 12,
	MagazineSize = 30,
	OverwatchAngle = 4680,
	Noise = 30,
	HandSlot = "TwoHanded",
	Entity = "Weapon_MP5",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"JAZZ_VerticalGrip",
			},
			'DefaultComponent', "JAZZ_VerticalGrip",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelShort",
			},
			'DefaultComponent', "JAZZ_BarrelShort",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_50_MP5",
				"JAZZ_MagQuick_MP5",
				"JAZZ_MagSmall30_15_MP5",
			},
			'DefaultComponent', "JAZZ_MagSmall30_15_MP5",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockNormal",
				"JAZZ_StockHeavy",
				"JAZZ_StockNo",
			},
			'DefaultComponent', "JAZZ_StockNo",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Eotech",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_FeroZ24",
				"JAZZ_Scope_DA15_6x",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Compensator",
				"JAZZ_PistolSuppressor",
				"JAZZ_ImprovisedSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"JAZZ_Freeswap",
			},
			'DefaultComponent', "JAZZ_Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	WeaponMass = 30,
	CyclicRPM = 900,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	MaxAimActions = 2,
	Recoil = 18,
	BurstShots = 4,
	AutoShots = 9,

	CloseRange = 3,

	CloseRangeFactor = 95,
	BulletDropRange = 8,
	Grouping = 78,
	BaseJamChance = -30,
	WeaponResource = 4500,
	CanAppearUsed = false,
}

