UndefineClass('MP7')
DefineClass.MP7 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "SubmachineGun",
	ScrapParts = 10,
	RepairCost = 18,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/MP7.png",
	DisplayName = T(584704183227, --[[ModItemInventoryItemCompositeDef MP7 DisplayName]] "MP7"),
	DisplayNamePlural = T(150579573516, --[[ModItemInventoryItemCompositeDef MP7 DisplayNamePlural]] "MP7"),
	Description = T(174939633208, --[[ModItemInventoryItemCompositeDef MP7 Description]] "Прямой конкурент бельгийского P90 за звание главного PDWаста в блоке НАТО. Внутри устроен как настоящая большая винтовка, что дает неплохую мощность при использовании патронов малого калибра. "),
	AdditionalHint = T(142265159773, --[[ModItemInventoryItemCompositeDef MP7 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Пробивает броню второго класса\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая скорострельность\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Одноручное"),
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 30000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_46",
	Damage = 18,
	ObjDamageMod = 25,
	AimAccuracy = 8,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 26,
	OverwatchAngle = 4680,
	Noise = 32,
	Entity = "MP7",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'AvailableComponents', {
				"VerticalGrip",
				"VerticalGripFld",
			},
			'DefaultComponent', "VerticalGripFld",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightUnFolded",
				"StockLightFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Open",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"DefaultIronsight_AR15",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"PistolSuppressor",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
		"DualShot",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	MaxAimActions = 2,
	Recoil = 6,
	BurstShots = 5,
	Handling = 10,
	BulletDropRange = 10,
	Grouping = 31,
	BaseJamChance = -30,
	WeaponResource = 8000,
}

