UndefineClass('MPL')
DefineClass.MPL = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 3,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/MPL.png",
	DisplayName = T(555365819120, --[[ModItemInventoryItemCompositeDef MPL DisplayName]] "Walther MP"),
	DisplayNamePlural = T(324062013193, --[[ModItemInventoryItemCompositeDef MPL DisplayNamePlural]] "Walther MP"),
	Description = T(932330768724, --[[ModItemInventoryItemCompositeDef MPL Description]] 'Пистолет-пулемет Вальтер MPL имеет вполне удачную конструкцию со свободным затвором с применением штамповки деталей. Сразу видно, что конструкторами был принят во внимание опыт ВОВ. Однако, потенциальными пользователями тоже был принят во внимание опыт ВОВ и оружие под маркой "Вальтер" просто не имело никакого шанса на успех на рынке.'),
	AdditionalHint = T(929080238056, --[[ModItemInventoryItemCompositeDef MPL AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Был на обложке Джа 2"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1900,
	CanAppearInShop = true,
	Tier = 1,
	RestockWeight = 100,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 24,
	ObjDamageMod = 20,
	AimAccuracy = 11,
	MagazineSize = 30,
	WeaponRange = 26,
	OverwatchAngle = 4320,
	Noise = 32,
	HandSlot = "TwoHanded",
	Entity = "MPL",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	WeaponMass = 30,
	CyclicRPM = 550,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	Recoil = 13,
	BurstShots = 3,
	AutoShots = 6,
	BulletDropRange = 10,

	CloseRange = 3,

	CloseRangeFactor = 95,
	Grouping = 40,
	BaseJamChance = -10,
	WeaponResource = 4000,
}

