UndefineClass('MR73')
DefineClass.MR73 = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 2-3",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 6,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/MR73.png",
	DisplayName = T(890000000000524, --[[ModItemInventoryItemCompositeDef MR73 DisplayName]] "Manurhin MR 73"),
	DisplayNamePlural = T(890000000000500, --[[ModItemInventoryItemCompositeDef MR73 DisplayNamePlural]] "Manurhin MR 73"),
	Description = T(890000000001230, --[[ModItemInventoryItemCompositeDef MR73 Description]] "Штатный револьвер французской полиции и даже полицейского спезнаца. Качество изготовления ощутимо выше, чем у ширпотреба вроде револьверов Colt, так что на эту пушку вполен можно положиться в самый трудный момент."),
	AdditionalHint = T(890000000000517, --[[ModItemInventoryItemCompositeDef MR73 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Револьвер\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Магнум \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удобный"),
	UnitStat = "Marksmanship",
	Cost = 6500,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 70,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_357",
	Damage = 29,
	ObjDamageMod = 40,
	AimAccuracy = 18,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 19,
	OverwatchAngle = 5100,
	Noise = 32,
	Entity = "M73Base",
	ComponentSlots = {
		
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelLong",
				"JAZZ_BarrelNormal",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handgrip",
			'AvailableComponents', {
				"JAZZ_Handgrip_Default",
				"JAZZ_Handgrip_Ergo",
			},
			'DefaultComponent', "JAZZ_Handgrip_Default",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"JAZZ_Fanning",
		"JAZZ_Bullseye",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	Recoil = 17,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 7,
	Grouping = 45,
	BaseJamChance = -100,
}

