UndefineClass('P38')
DefineClass.P38 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-3",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 3,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/P38.png",
	DisplayName = T(890000000001151, --[[ModItemInventoryItemCompositeDef P38 DisplayName]] "P38"),
	DisplayNamePlural = T(890000000001291, --[[ModItemInventoryItemCompositeDef P38 DisplayNamePlural]] "P38"),
	Description = T(890000000000014, --[[ModItemInventoryItemCompositeDef P38 Description]] "«8 предупредительных выстрелов плюс один прицельный бросок» - так говорили об этом пистолете в послевоенном Бундесвере. Однако, на момент своего появления, это было вполне себе неплохое оружие, пусть и частично переусложненное. В конце концов, именно он, а не Люгер или Маузер стал самым массовым немецким пистолетом ВМВ."),
	AdditionalHint = T(890000000000608, --[[ModItemInventoryItemCompositeDef P38 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Нормальный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Средний\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> В целом пойдет"),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 20,
	ObjDamageMod = 20,
	AimAccuracy = 7,
	CritChanceScaled = 35,
	MagazineSize = 8,
	WeaponRange = 18,
	OverwatchAngle = 5400,
	Noise = 18,
	Entity = "P38",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_13_PISTOL_52",
				"JAZZ_MagLarge_8_PISTOL_52",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelNormal",
				"JAZZ_BarrelShort_Pistol",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_PistolSuppressor",
			},
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	MaxAimActions = 2,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 6,
	Grouping = 56,
	BaseJamChance = -20,
}

