UndefineClass('P90')
DefineClass.P90 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "SubmachineGun",
	msg_reactions = {},
	unit_reactions = {},
	ScrapParts = 10,
	RepairCost = 20,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/P90.png",
	DisplayName = T(409531523901, --[[ModItemInventoryItemCompositeDef P90 DisplayName]] "P90"),
	DisplayNamePlural = T(895991470636, --[[ModItemInventoryItemCompositeDef P90 DisplayNamePlural]] "P90"),
	Description = T(589817908151, --[[ModItemInventoryItemCompositeDef P90 Description]] "Бельгийский пистолет-пулемет футуристичного вида в компоновке буллпап. Разработан специально под новый бронебойный малоимпульсный патрон калибра 5.7мм. Мнения об автомате делятся полярно - кто-то в восторге от его эргономики, кто-то наоборот, проклинает ее."),
	AdditionalHint = T(863940765509, --[[ModItemInventoryItemCompositeDef P90 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Топовый\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бронебойный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 12750,
	CanAppearInShop = true,
	Tier = 4,
	RestockWeight = 35,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_57",
	Damage = 20,
	ObjDamageMod = 25,
	AimAccuracy = 16,
	CritChanceScaled = 20,
	MagazineSize = 50,
	WeaponRange = 34,
	OverwatchAngle = 4440,
	Noise = 35,
	HandSlot = "TwoHanded",
	Entity = "P90",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_PistolSuppressor",
				"JAZZ_ImprovisedSuppressor",
			},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 7000,
	WeaponMass = 28,
	CyclicRPM = 900,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	Recoil = 17,
	BurstShots = 4,
	AutoShots = 9,

	CloseRange = 3,

	CloseRangeFactor = 95,
	BulletDropRange = 14,
	Grouping = 50,
	BaseJamChance = -30,
	WeaponResource = 9500,
	CanAppearUsed = false,
}

