UndefineClass('PB')
DefineClass.PB = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-UNIQ",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 5,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/PB.png",
	DisplayName = T(890000000000219, --[[ModItemInventoryItemCompositeDef PB DisplayName]] "Пистолет ПБ"),
	DisplayNamePlural = T(890000000001089, --[[ModItemInventoryItemCompositeDef PB DisplayNamePlural]] "Пистолеты ПБ"),
	Description = T(413605184956, --[[ModItemInventoryItemCompositeDef PB Description]] "Самый известный советский и российский пистолет. В современных реалиях его принято ругать, но чаще всего это делают те, кто стреляет разве что в монстров с экрана монитора."),
	AdditionalHint = T(890000000000101, --[[ModItemInventoryItemCompositeDef PB AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бесшумный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Длинная рука Кремля."),
	UnitStat = "Marksmanship",
	Cost = 1800,
	CanAppearInShop = false,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x18",
	Damage = 18,
	ObjDamageMod = 15,
	AimAccuracy = 7,
	CritChance = 20,
	CritChanceScaled = 45,
	MagazineSize = 8,
	WeaponRange = 16,
	OverwatchAngle = 5400,
	Noise = 2,
	Entity = "pb",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_SuppressorIntegrated",
			},
			'DefaultComponent', "JAZZ_SuppressorIntegrated",
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	MaxAimActions = 4,
	Recoil = 14,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 6,
	Grouping = 80,
	BaseJamChance = -100,
	WeaponResource = 3000,
}

