UndefineClass('PipeBomb')
DefineClass.PipeBomb = {
	__parents = { "ThrowableTrapItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "ThrowableTrapItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/PipeBomb",
	ItemType = "Grenade",
	DisplayName = T(642346688869, --[[ModItemInventoryItemCompositeDef PipeBomb DisplayName]] "Pipe Bomb"),
	DisplayNamePlural = T(494920208733, --[[ModItemInventoryItemCompositeDef PipeBomb DisplayNamePlural]] "Pipe Bombs"),
	AdditionalHint = T(738342557339, --[[ModItemInventoryItemCompositeDef PipeBomb AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Взрывается через 1 ход (или 5 секунд не в бою)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сильно зависит от Взрывчатки; высокая вероятность неудачи\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Вызывает кровотечение"),
	UnitStat = "Explosives",
	Cost = 120,
	CanAppearInShop = false,
	RestockWeight = 50,
	CategoryPair = "Grenade",
	MaxStacks = 5,
	MinMishapChance = 0,
	MaxMishapChance = 80,
	MinMishapRange = 1,
	MaxMishapRange = 9,
	CenterUnitDamageMod = 130,
	CenterAppliedEffects = {
		"Bleeding",
	},
	Scatter = 8,
	AttackAP = 3000,
	BaseRange = 0,
	ThrowMaxRange = 22,
	InaccurateMinOffset = 4000,
	InaccurateMaxOffset = 10000,
	Noise = 70,
	ThrowNoise = 8,
	Entity = "Explosive_TNT",
	ActionIcon = "UI/Icons/Hud/pipe_bomb",
	TriggerType = "Timed",
	ExplosiveType = "BlackPowder",
}

