UndefineClass('PKM')
DefineClass.PKM = {
	__parents = { "MachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "MachineGun",
	ScrapParts = 16,
	RepairCost = 10,
	Reliability = 90,
	Icon = "Mod/e6L4ECj/WeaponIcons/PKM.png",
	DisplayName = T(870783532014, --[[ModItemInventoryItemCompositeDef PKM DisplayName]] "ПКМ"),
	DisplayNamePlural = T(539461107116, --[[ModItemInventoryItemCompositeDef PKM DisplayNamePlural]] "ПКМ"),
	Description = T(921997761319, --[[ModItemInventoryItemCompositeDef PKM Description]] "Единый пулемет советской и российской армии. Разработан в 1960-х. Может использоваться на технике, на станке, в пехотном варианте. Легче в полтора раза, чем большинство натовских пулеметов. Легенда надежности."),
	AdditionalHint = T(982879482211, --[[ModItemInventoryItemCompositeDef PKM AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Низкая эффективность стрельбы навскидку"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 120000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "MachineGuns",
	Caliber = "JAZZ_Caliber_762x54R",
	Damage = 38,
	ObjDamageMod = 120,
	AimAccuracy = 13,
	MagazineSize = 100,
	WeaponRange = 60,
	OverwatchAngle = 600,
	Noise = 70,
	HandSlot = "TwoHanded",
	Entity = "PKM",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"DefMuzzle",
			},
			'DefaultComponent', "DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Mount",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"PKMModern",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"StockNormal",
				"PKMModStock",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
			'DefaultComponent', "Bipod",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"TacGrip",
				"VerticalGrip",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"PKMDefHandGrip",
				"PKMModHandGrip",
			},
			'DefaultComponent', "PKMDefHandGrip",
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Machine Gun",
	AvailableAttacks = {
		"MGBurstFire",
	},
	ShootAP = 9000,
	ReloadAP = 9000,
	Recoil = 17,
	BurstShots = 6,
	AutoShots = 6,
	Handling = -28,
	BulletDropRange = 25,
	Grouping = 38,
	BaseJamChance = -50,
	WeaponResource = 12000,
}

