UndefineClass('PP19Bizon')
DefineClass.PP19Bizon = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 12,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/Bizon.png",
	DisplayName = T(776690469955, --[[ModItemInventoryItemCompositeDef PP19Bizon DisplayName]] "ПП19 Бизон"),
	DisplayNamePlural = T(965842574005, --[[ModItemInventoryItemCompositeDef PP19Bizon DisplayNamePlural]] "ПП19 Бизон"),
	Description = T(946911790179, --[[ModItemInventoryItemCompositeDef PP19Bizon Description]] "Российский пистолет-пулемет, собранный на основе узлов автомата АКС-74, но с использованием автоматики со свободным затвором. Шнековый магазин на 64 патрона в отличие от пистолетов Calico приспособлен в качестве ухватистого цевья, а если добавить к этому малую отдачу, то крыть врага очередями становится очень приятно. Правда, потом приходится весь вечер весто ужина набивать эти самые магазины, но это того стоит, поверьте!"),
	AdditionalHint = T(622376849753, --[[ModItemInventoryItemCompositeDef PP19Bizon AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Метла 2.0 \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный, как бизон"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5250,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x18",
	Damage = 18,
	ObjDamageMod = 15,
	AimAccuracy = 13,
	CritChanceScaled = 30,
	MagazineSize = 64,
	WeaponRange = 26,
	OverwatchAngle = 4080,
	Noise = 26,
	HandSlot = "TwoHanded",
	Entity = "Bizon",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_PKAS",
				"JAZZ_Reflex_Cobra",
				"JAZZ_CombatScope_1P29",
				"JAZZ_Scope_PSO",
				"JAZZ_NightScope_NSPU",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 5000,
	ReloadAP = 7000,
	WeaponMass = 27,
	CyclicRPM = 680,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	Recoil = 12,
	BurstShots = 3,
	AutoShots = 7,

	CloseRange = 3,

	CloseRangeFactor = 95,
	BulletDropRange = 9,
	Grouping = 60,
	BaseJamChance = -30,
	WeaponResource = 6000,
	CanAppearUsed = false,
}

