UndefineClass('PP19Bizon')
DefineClass.PP19Bizon = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "918 T3",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/Bizon.png",
	DisplayName = T(776690469955, --[[ModItemInventoryItemCompositeDef PP19Bizon DisplayName]] "ПП19 Бизон"),
	DisplayNamePlural = T(965842574005, --[[ModItemInventoryItemCompositeDef PP19Bizon DisplayNamePlural]] "ПП19 Бизон"),
	Description = T(946911790179, --[[ModItemInventoryItemCompositeDef PP19Bizon Description]] "Российский пистолет-пулемет, собранный на основе узлов автомата АКС-74, но с использованием автоматики со свободным затвором. Шнековый магазин на 64 патрона в отличие от пистолетов Calico приспособлен в качестве ухватистого цевья, а если добавить к этому малую отдачу, то крыть врага очередями становится очень приятно. Правда, потом приходится весь вечер весто ужина набивать эти самые магазины, но это того стоит, поверьте!"),
	AdditionalHint = T(622376849753, --[[ModItemInventoryItemCompositeDef PP19Bizon AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Делает 12 выстрелов при использовании автоматического огня"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 8000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 50,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x18",
	Damage = 16,
	ObjDamageMod = 15,
	AimAccuracy = 12,
	CritChance = 5,
	CritChanceScaled = 30,
	MagazineSize = 64,
	WeaponRange = 24,
	OverwatchAngle = 4080,
	HandSlot = "TwoHanded",
	Entity = "Bizon",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_PKAS",
				"JAZZ_Reflex_Cobra",
				"JAZZ_CombatScope_1P29",
				"JAZZ_Scope_PSO",
				"JAZZ_NightScope_NSPU",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 7000,
	Recoil = 1,
	BurstShots = 4,
	AutoShots = 12,
	Handling = 80,
	BulletDropRange = 10,
	Grouping = 80,
	BaseJamChance = -30,
	WeaponResource = 17000,
	CanAppearUsed = false,
}

