UndefineClass('PPS43')
DefineClass.PPS43 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "7.62x25 T2",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/PPS43.png",
	ItemType = "SMG",
	DisplayName = T(466049040564, --[[ModItemInventoryItemCompositeDef PPS43 DisplayName]] "ППС-43"),
	DisplayNamePlural = T(302494084890, --[[ModItemInventoryItemCompositeDef PPS43 DisplayNamePlural]] "ППС-43"),
	Description = T(781716061274, --[[ModItemInventoryItemCompositeDef PPS43 Description]] 'Иногда технологии - это не полеты в космос и телепортация. Иногда технологии это то, что может быть собрано в осажденном городе на любом станке 12-летним пацаном за две корки хлеба в сутки. Лучший автомат ВОВ по совокупности характеристик. Но еще и лучшая "таблетка для памяти".'),
	AdditionalHint = T(776470962417, --[[ModItemInventoryItemCompositeDef PPS43 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Пробивает броню 2 класса"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 800,
	CanAppearInShop = true,
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x25",
	Damage = 21,
	ObjDamageMod = 15,
	AimAccuracy = 11,
	CritChanceScaled = 5,
	MagazineSize = 35,
	WeaponRange = 28,
	OverwatchAngle = 4200,
	Noise = 33,
	HandSlot = "TwoHanded",
	Entity = "PPS_43",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	Recoil = 7,
	AutoShots = 7,
	Handling = 80,
	BulletDropRange = 11,
	Grouping = 82,
	BaseJamChance = -10,
	WeaponResource = 12000,
}

