UndefineClass('PPS43')
DefineClass.PPS43 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 2,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/PPS43.png",
	ItemType = "SMG",
	DisplayName = T(466049040564, --[[ModItemInventoryItemCompositeDef PPS43 DisplayName]] "ППС-43"),
	DisplayNamePlural = T(302494084890, --[[ModItemInventoryItemCompositeDef PPS43 DisplayNamePlural]] "ППС-43"),
	Description = T(781716061274, --[[ModItemInventoryItemCompositeDef PPS43 Description]] 'Иногда технологии - это не полеты в космос и телепортация. Иногда технологии это то, что может быть собрано в осажденном городе на любом станке 12-летним пацаном за две корки хлеба в сутки. Лучший автомат ВОВ по совокупности характеристик. Но еще и лучшая "таблетка для памяти".'),
	AdditionalHint = T(776470962417, --[[ModItemInventoryItemCompositeDef PPS43 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Пробивает броню \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Складной приклад"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 800,
	CanAppearInShop = true,
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x25",
	Damage = 20,
	ObjDamageMod = 15,
	AimAccuracy = 7,
	CritChanceScaled = 5,
	MagazineSize = 35,
	WeaponRange = 32,
	OverwatchAngle = 4200,
	Noise = 37,
	HandSlot = "TwoHanded",
	Entity = "PPS_43",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	MaxAimActions = 2,
	Recoil = 7,
	AutoShots = 7,

	CloseRange = 2,

	CloseRangeFactor = 95,
	BulletDropRange = 12,
	Grouping = 29,
	BaseJamChance = -10,
	WeaponResource = 4800,
}

