UndefineClass('PPSH')
DefineClass.PPSH = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "7.62x25 T1-",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/PPSH.png",
	ItemType = "SMG",
	DisplayName = T(611519476345, --[[ModItemInventoryItemCompositeDef PPSH DisplayName]] "ППШ"),
	DisplayNamePlural = T(705465498623, --[[ModItemInventoryItemCompositeDef PPSH DisplayNamePlural]] "ППШ"),
	Description = T(392209165367, --[[ModItemInventoryItemCompositeDef PPSH Description]] "ППШ-41 (Пистолет-Пулемет конструкции Шпагина) был создан в 1941 году для замены более сложного и дорогого ППД-40. В этом же году принят на вооружение РККА. Впоследствии же стал символом доблести советского солдата и победы советского народа над фашизмом."),
	AdditionalHint = T(246973411865, --[[ModItemInventoryItemCompositeDef PPSH AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Пробивает броню 2 класса\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая скорострельность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x25",
	Damage = 20,
	ObjDamageMod = 15,
	AimAccuracy = 9,
	CritChanceScaled = 5,
	MagazineSize = 35,
	WeaponRange = 27,
	OverwatchAngle = 3900,
	Noise = 36,
	HandSlot = "TwoHanded",
	Entity = "PPSH",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagDrum_35-71",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	MaxAimActions = 2,
	Recoil = 7,
	BurstShots = 5,
	Handling = 75,
	BulletDropRange = 11,
	Grouping = 70,
	WeaponResource = 15000,
}

