UndefineClass('PPSH')
DefineClass.PPSH = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 3,
	CanAppearInShop = true,
	Tier = 1,
	Cost = 1600,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/PPSH.png",
	ItemType = "SMG",
	DisplayName = T(611519476345, --[[ModItemInventoryItemCompositeDef PPSH DisplayName]] "ППШ"),
	DisplayNamePlural = T(705465498623, --[[ModItemInventoryItemCompositeDef PPSH DisplayNamePlural]] "ППШ"),
	Description = T(392209165367, --[[ModItemInventoryItemCompositeDef PPSH Description]] "ППШ-41 (Пистолет-Пулемет конструкции Шпагина) был создан в 1941 году для замены более сложного и дорогого ППД-40. В этом же году принят на вооружение РККА. Впоследствии же стал символом доблести советского солдата и победы советского народа над фашизмом."),
	AdditionalHint = T(246973411865, --[[ModItemInventoryItemCompositeDef PPSH AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Окопная метла \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Пробивает броню"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	RestockWeight = 100,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x25",
	Damage = 18,
	ObjDamageMod = 15,
	AimAccuracy = 9,
	CritChanceScaled = 5,
	MagazineSize = 35,
	WeaponRange = 30,
	OverwatchAngle = 3900,
	Noise = 36,
	HandSlot = "TwoHanded",
	Entity = "PPSH",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagDrum_35_71",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	WeaponMass = 36,
	CyclicRPM = 900,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	AutoShots = 9,
	MaxAimActions = 2,
	Recoil = 13,
	BurstShots = 4,

	CloseRange = 3,

	CloseRangeFactor = 95,
	BulletDropRange = 11,
	Grouping = 26,
	WeaponResource = 6200,
}

