UndefineClass('PSG1')
DefineClass.PSG1 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-3",
	object_class = "SniperRifle",
	ScrapParts = 14,
	RepairCost = 25,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/PSG.png",
	DisplayName = T(887059977163, --[[ModItemInventoryItemCompositeDef PSG1 DisplayName]] "PSG1"),
	DisplayNamePlural = T(908671276161, --[[ModItemInventoryItemCompositeDef PSG1 DisplayNamePlural]] "PSG1"),
	Description = T(920160133295, --[[ModItemInventoryItemCompositeDef PSG1 Description]] "Самозарядная высокоточная винтовка, разработанная специально для полиции после Олимпиады в Мюнхене 1972 года. Конструкторы решили обойтись без механического прицела и сразу поставить оптику. Регулируемые приклад, щека приклада, спусковая группа и многое, многое другое. Всем своим видом эта винтовка кричит «Я могу хоть весь день наблюдать за захватом заложников в ожидании отмашки!»."),
	AdditionalHint = T(707852110578, --[[ModItemInventoryItemCompositeDef PSG1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Самая точная снайперка \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 100000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 37,
	ObjDamageMod = 80,
	AimAccuracy = 18,
	CritChanceScaled = 30,
	MagazineSize = 5,
	WeaponRange = 85,
	OverwatchAngle = 720,
	Noise = 65,
	HandSlot = "TwoHanded",
	Entity = "Weapon_PSG1",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockNormal",
				"StockHeavy",
			},
			'DefaultComponent', "StockNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagNormalFine",
				"MagLarge",
				"MagLargeFine",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_Scope_PSG",
			},
			'DefaultComponent', "JAZZ_Scope_PSG",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"FlashlightDot_PSG_M1",
				"Flashlight_PSG_M1",
				"LaserDot_PSG_M1",
				"UVDot_PSG_M1",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 8000,
	ReloadAP = 7000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = -25,
	BulletDropRange = 22,
	Grouping = 45,
	BaseJamChance = -20,
	WeaponResource = 9000,
}

