UndefineClass('R870')
DefineClass.R870 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T2",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/R870.png",
	DisplayName = T(228456778686, --[[ModItemInventoryItemCompositeDef R870 DisplayName]] "R870"),
	DisplayNamePlural = T(259673733542, --[[ModItemInventoryItemCompositeDef R870 DisplayNamePlural]] "R870"),
	Description = T(273443322486, --[[ModItemInventoryItemCompositeDef R870 Description]] 'Классическое "американское" помповое гладкоствольное ружье в охотничьей комплектации с подствольным магазином, вмещающим достаточно маленьких и злых патронов 12 калибра. Охота? Самооборона? Массовые беспорядки? Возьмите Рем, он был для этого сделан.'),
	AdditionalHint = T(119486433731, --[[ModItemInventoryItemCompositeDef R870 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Помповый - высокие затраты од на выстрел\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 7500,
	CanAppearInShop = true,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 17,
	MagazineSize = 6,
	WeaponRange = 22,
	PointBlankBonus = 1,
	OverwatchAngle = 1440,
	BuckshotConeAngle = 120,
	BuckshotFalloffDamage = 15,
	Noise = 37,
	HandSlot = "TwoHanded",
	Entity = "R870",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side2",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"SpeedLoader",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 4000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 72,
	BulletDropRange = 9,
	Grouping = 150,
	BaseJamChance = -10,
	WeaponResource = 1400,
}

