UndefineClass('RPG7')
DefineClass.RPG7 = {
	__parents = { "RocketLauncher" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "RocketLauncher",
	ScrapParts = 16,
	RepairCost = 100,
	Reliability = 50,
	MinMishapChance = 0,
	MaxMishapChance = 60,
	MaxMishapRange = 6,
	Caliber = "JAZZ_Caliber_Warhead",
	AttackAP = 8000,
	Entity = "Weapon_RPG7_Copy",
	Icon = "UI/Icons/Weapons/RPG-7",
	DisplayName = T(127122189693, --[[ModItemInventoryItemCompositeDef RPG7 DisplayName]] "РПГ-7"),
	DisplayNamePlural = T(302681108532, --[[ModItemInventoryItemCompositeDef RPG7 DisplayNamePlural]] "РПГ-7"),
	Description = T(707348010242, --[[ModItemInventoryItemCompositeDef RPG7 Description]] 'Ручной противотанковый гранатомет. Часто, когда говорят "гранатомет", или "РПГ", имеют в виду именно РПГ-7. Снаряжается надкалиберными 40 мм гранатами, с широкой номенклатурой используемых типов боеприпасов. '),
	AdditionalHint = T(151639464453, --[[ModItemInventoryItemCompositeDef RPG7 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Реактивный гранатомет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Шанс промаха увеличивается с расстоянием \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Опасная зона за спиной стрелка \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Тяжелый - ограничивает свободу движений"),
	LargeItem = 1,
	Cumbersome = 1,
	UnitStat = "Explosives",
	Valuable = 1,
	Cost = 60000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	RestockWeight = 40,
	CategoryPair = "HeavyWeapons",
	ObjDamageMod = 600,
	CritChanceScaled = 0,
	WeaponRange = 40,
	Noise = 100,
	HandSlot = "TwoHanded",
	HolsterSlot = "Shoulder",
	PreparedAttackType = "None",
	ShootAP = 9000,
	ReloadAP = 7000,
	Handling = 60,
	WeaponResource = 100,
	BackfireRange = 2,
	BackfireDamage = 8,
}

