UndefineClass('SCAR')
DefineClass.SCAR = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	MaxStock = 1,
	comment = "Tier 3-2",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 14,
	Reliability = 90,
	Icon = "Mod/e6L4ECj/WeaponIcons/SCAR_L_Standard.png",
	DisplayName = T(890000000034109, "SCAR-L"),
	DisplayNamePlural = T(890000000034109, "SCAR-L"),
	Description = T(890000000034121, "Модульная винтовка FN SCAR. Комплекты L/H меняют калибр, стволы — длину и характеристики. SSR — боевая винтовка под 7,62×51 мм с одиночным огнём."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 22000,
	CanAppearInShop = true,
	Tier = 4,
	RestockWeight = 25,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 24,
	ObjDamageMod = 50,
	AimAccuracy = 13,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 48,
	OverwatchAngle = 1560,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "JAZZ_SCAR_L_Standard",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Conversion",
			'AvailableComponents', {
				"JAZZ_SCAR_L",
				"JAZZ_SCAR_H",
				"JAZZ_SCAR_SSR",
			},
			'DefaultComponent', "JAZZ_SCAR_L",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_SCAR_BarrelNormal",
				"JAZZ_SCAR_BarrelShort",
				"JAZZ_SCAR_BarrelLong",
			},
			'DefaultComponent', "JAZZ_SCAR_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_SCAR_Stock",
				"JAZZ_SCAR_StockFolded",
			},
			'DefaultComponent', "JAZZ_SCAR_Stock",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_SCAR_Muzzle",
				"JAZZ_Compensator",
				"JAZZ_Suppressor",
			},
			'DefaultComponent', "JAZZ_SCAR_Muzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_Scope_6x",
				"JAZZ_NightScope",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_VerticalGrip",
				"JAZZ_TacGrip",
				"JAZZ_Bipod_Under",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
				"JAZZ_UVDot",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {"SingleShot","BurstFire","AutoFire","JAZZ_TargetSweep"},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 16,
	BurstShots = 4,
	AutoShots = 9,
	WeaponMass = 35,
	CyclicRPM = 650,
	WeaponSizeClass = "Long",
	CloseRange = 5,
	CloseRangeFactor = 90,
	BulletDropRange = 15,
	Grouping = 63,
	BaseJamChance = -40,
	WeaponResource = 10000,
}
