UndefineClass('Scorpion')
DefineClass.Scorpion = {
	__parents = { "Autopistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "Autopistol",
	ScrapParts = 3,
	RepairCost = 3,
	Icon = "Mod/e6L4ECj/WeaponIcons/Scorpion.png",
	DisplayName = T(389917013778, --[[ModItemInventoryItemCompositeDef Scorpion DisplayName]] "Scorpion"),
	DisplayNamePlural = T(505643276959, --[[ModItemInventoryItemCompositeDef Scorpion DisplayNamePlural]] "Scorpion"),
	Description = T(276327014875, --[[ModItemInventoryItemCompositeDef Scorpion Description]] "Маленький и удаленький чехословацкий автомат под советский пистолетный 9мм патрон. Оказался крайне удачным в использовании в контртеррористических операциях."),
	AdditionalHint = T(842942928399, --[[ModItemInventoryItemCompositeDef Scorpion AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Одноручный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Складной приклад \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Маленький \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удаленький"),
	UnitStat = "Marksmanship",
	CanAppearInShop = true,
	Tier = 1,
	Cost = 1500,
	RestockWeight = 100,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x18",
	Damage = 15,
	ObjDamageMod = 15,
	AimAccuracy = 7,
	CritChanceScaled = 5,
	MagazineSize = 20,
	WeaponRange = 19,
	OverwatchAngle = 4680,
	Noise = 22,
	Entity = "Scorpion",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
			},
			'DefaultComponent', "JAZZ_StockLightFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"JAZZ_Freeswap",
			},
			'DefaultComponent', "JAZZ_Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"DualShot",
		"JAZZ_SmgStorm",
		"JAZZ_RunAndSMGStorm",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 27,
	CyclicRPM = 900,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	MaxAimActions = 2,
	Recoil = 15,
	BurstShots = 4,
	AutoShots = 9,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 6,
	Grouping = 50,
	WeaponResource = 2000,
}

