UndefineClass('ScoutSniper')
DefineClass.ScoutSniper = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-UNIQ",
	object_class = "SniperRifle",
	ScrapParts = 14,
	RepairCost = 10,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/SteyrScout.png",
	DisplayName = T(111366988214, "Steyr Scout"),
	DisplayNamePlural = T(980521024048, "Steyr Scout"),
	Description = T(642546299209, "Австрийская снайперская винтовка. Оптический прицел кратности 2.5Х, установлен низко над стволом и с большим выносом вперед, что обеспечивает удобное прицеливание двумя глазами и быстрый захват цели. Ложа, затвор и спусковой механизм выполнен по индивидуальному заказу для миссисс Стерлинг за несусветное количество денег. Потому что она может  себе это позволить."),
	AdditionalHint = T(514313521194, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий шанс критического попадания\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая эффективность стрельбы навскидку"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 160000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 34,
	ObjDamageMod = 80,
	AimAccuracy = 36,
	CritChanceScaled = 50,
	MagazineSize = 5,
	WeaponRange = 85,
	OverwatchAngle = 420,
	Noise = 40,
	HandSlot = "TwoHanded",
	Entity = "SteyrScout",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_Scope_Scout",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"DefMuzzle",
				"Suppressor",
				"SuppressorImproved",
			},
			'DefaultComponent', "DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"BarrelsDefs",
			},
			'DefaultComponent', "BarrelsDefs",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	PreparedAttackType = "Both",
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 7000,
	ReloadAP = 7000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 55,
	BulletDropRange = 20,
	Grouping = 420,
	BaseJamChance = -30,
	WeaponResource = 7000,
}

