UndefineClass('ScoutSniper')
DefineClass.ScoutSniper = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-UNIQ",
	object_class = "SniperRifle",
	ScrapParts = 14,
	RepairCost = 10,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/SteyrScout.png",
	DisplayName = T(111366988214, --[[ModItemInventoryItemCompositeDef ScoutSniper DisplayName]] "Steyr Scout"),
	DisplayNamePlural = T(980521024048, --[[ModItemInventoryItemCompositeDef ScoutSniper DisplayNamePlural]] "Steyr Scout"),
	Description = T(642546299209, --[[ModItemInventoryItemCompositeDef ScoutSniper Description]] "Австрийская снайперская винтовка. Оптический прицел кратности 2.5Х, установлен низко над стволом и с большим выносом вперед, что обеспечивает удобное прицеливание двумя глазами и быстрый захват цели. Ложа, затвор и спусковой механизм выполнен по индивидуальному заказу для миссисс Стерлинг за несусветное количество денег. Потому что она может  себе это позволить."),
	AdditionalHint = T(514313521194, --[[ModItemInventoryItemCompositeDef ScoutSniper AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Винтовка с ручным перезаряжанием \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстро стреляет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 160000,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 1,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x51",
	Damage = 34,
	ObjDamageMod = 80,
	AimAccuracy = 15,
	CritChanceScaled = 50,
	MagazineSize = 5,
	WeaponRange = 85,
	OverwatchAngle = 420,
	Noise = 40,
	HandSlot = "TwoHanded",
	Entity = "SteyrScout",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_Scope_Scout",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'AvailableComponents', {
				"JAZZ_DefMuzzle",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
			'DefaultComponent', "JAZZ_DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_BarrelsDefs",
			},
			'DefaultComponent', "JAZZ_BarrelsDefs",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 6000,
	ReloadAP = 7000,
	BurstShots = 0,
	WeaponMass = 55,
	CyclicRPM = 0,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	Recoil = 22,
	AutoShots = 0,

	CloseRange = 16,

	CloseRangeFactor = 70,
	BulletDropRange = 21,
	Grouping = 45,
	BaseJamChance = -30,
	WeaponResource = 7000,
}

