UndefineClass('ShapedCharge')
DefineClass.ShapedCharge = {
	__parents = { "GrenadeItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/ShapedCharge",
	ItemType = "Grenade",
	DisplayName = T(380012367478, --[[ModItemInventoryItemCompositeDef ShapedCharge DisplayName]] "Shaped Charge"),
	DisplayNamePlural = T(622567247516, --[[ModItemInventoryItemCompositeDef ShapedCharge DisplayNamePlural]] "Shaped Charges"),
	AdditionalHint = T(622419236578, --[[ModItemInventoryItemCompositeDef ShapedCharge AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Наносит урон по сектору
<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сильно зависит от Взрывчатки; высокая вероятность неудачи при использовании всеми, кроме Барри"),
	UnitStat = "Explosives",
	Cost = 1500,
	CanAppearInShop = true,
	RestockWeight = 0,
	MaxStacks = 2,
	MinMishapChance = 2,
	MaxMishapChance = 80,
	MaxMishapRange = 6,
	CenterObjDamageMod = 300,
	AreaOfEffect = 8,
	CenterAreaOfEffect = 4,
	AreaUnitDamageMod = 50,
	PenetrationClass = 1,
	coneShaped = true,
	coneAngle = 45,
	BurnGround = false,
	DeathType = "BlowUp",
	BaseDamage = 80,
	Scatter = 6,
	BaseRange = 0,
	ThrowMaxRange = 23,
	CanBounce = false,
	Noise = 100,
	Entity = "MilitaryCamp_Grenade_01",
	ActionIcon = "UI/Icons/Hud/shaped_charge",
}

