UndefineClass('Sig550Custom')
DefineClass.Sig550Custom = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 16,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/SIG550Custom.png",
	ItemType = "DMR",
	DisplayName = T(518572936824, "Sig 550 RIS"),
	DisplayNamePlural = T(927601720702, "Sig 550 RIS"),
	Description = T(755003574664, "Вариант винтовки SIG 500 в современном кастомном обвесе, позволяющем установить дополнительные приспособления. Стильно, модно, молодежно. Даже завидно."),
	AdditionalHint = T(155361024222, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая эффективность при стрельбе очередями\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможности модификаций"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 100000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 26,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 48,
	OverwatchAngle = 1200,
	Noise = 46,
	HandSlot = "TwoHanded",
	Entity = "Sig550Custom",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"VerticalGrip",
				"GrenadeLauncher",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"UVDot",
				"Flashlight",
				"FlashlightDot",
				"LaserDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"SigErgoHandGrip",
				"SigDefHandGuard",
			},
			'DefaultComponent', "SigDefHandGuard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
				"StockHeavy",
			},
			'DefaultComponent', "UnfoldStocks",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"DefaultIronsight_AR15",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	Recoil = 8,
	BurstShots = 1,
	AutoShots = 8,
	Handling = 71,
	BulletDropRange = 17,
	Grouping = 300,
	BaseJamChance = -30,
	WeaponResource = 9500,
}

