UndefineClass('Sig552SWAT')
DefineClass.Sig552SWAT = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 16,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/SIG552SWAT.png",
	DisplayName = T(834623031798, --[[ModItemInventoryItemCompositeDef Sig552SWAT DisplayName]] "Sig 552 SWAT"),
	DisplayNamePlural = T(188243913550, --[[ModItemInventoryItemCompositeDef Sig552SWAT DisplayNamePlural]] "Sig 552 SWAT"),
	Description = T(128465089412, --[[ModItemInventoryItemCompositeDef Sig552SWAT Description]] "Короткоствольный автомат SIG 552 в конфигурации SWAT. Контр-террористы победили."),
	AdditionalHint = T(348107856485, --[[ModItemInventoryItemCompositeDef Sig552SWAT AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Можно использовать для стрельбы на бегу\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Низкая отдача\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможности модификаций"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 70000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 22,
	ObjDamageMod = 50,
	AimAccuracy = 23,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 40,
	OverwatchAngle = 2280,
	Noise = 48,
	HandSlot = "TwoHanded",
	Entity = "Sig552SWAT",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"SigDefHandGuard",
				"SigErgoHandGrip",
			},
			'DefaultComponent', "SigDefHandGuard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
		"RunAndGun",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 9,
	AutoShots = 7,
	Handling = 78,
	BulletDropRange = 16,
	Grouping = 250,
	BaseJamChance = -30,
	WeaponResource = 9000,
}

