UndefineClass('Sig550Custom')
DefineClass.Sig550Custom = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 16,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/SIG550Custom.png",
	DisplayName = T(518572936824, --[[ModItemInventoryItemCompositeDef Sig550Custom DisplayName]] "Sig 550 RIS"),
	DisplayNamePlural = T(927601720702, --[[ModItemInventoryItemCompositeDef Sig550Custom DisplayNamePlural]] "Sig 550 RIS"),
	Description = T(755003574664, --[[ModItemInventoryItemCompositeDef Sig550Custom Description]] "Вариант винтовки SIG 500 в современном кастомном обвесе, позволяющем установить дополнительные приспособления. Стильно, модно, молодежно. Даже завидно."),
	AdditionalHint = T(155361024222, --[[ModItemInventoryItemCompositeDef Sig550Custom AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстро стреляет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Слабая отдача"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 100000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 24,
	ObjDamageMod = 50,
	AimAccuracy = 15,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 48,
	OverwatchAngle = 1200,
	Noise = 46,
	HandSlot = "TwoHanded",
	Entity = "Sig550Custom",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_VerticalGrip",
				"JAZZ_GrenadeLauncher",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_UVDot",
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_FlashlightDot",
				"JAZZ_LaserDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"JAZZ_SigErgoHandGrip",
				"JAZZ_SigDefHandGuard",
			},
			'DefaultComponent', "JAZZ_SigDefHandGuard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_50_SIG",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockHeavy",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_DefaultIronsight_AR15",
			},
			'DefaultComponent', "JAZZ_DefaultIronsight_AR15",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	WeaponMass = 36,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 16,
	BurstShots = 4,
	AutoShots = 7,

	CloseRange = 8,

	CloseRangeFactor = 85,
	BulletDropRange = 18,
	Grouping = 63,
	BaseJamChance = -30,
	WeaponResource = 9500,
}

