UndefineClass('Sig550')
DefineClass.Sig550 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T3",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/SIG550.png",
	DisplayName = T(937651754900, --[[ModItemInventoryItemCompositeDef Sig550 DisplayName]] "Sig 550"),
	DisplayNamePlural = T(501240162927, --[[ModItemInventoryItemCompositeDef Sig550 DisplayNamePlural]] "Sig 550"),
	Description = T(453269317328, --[[ModItemInventoryItemCompositeDef Sig550 Description]] "Что получится, если АК попытаются изобрести в Швейцарии? Получится одна из самых крутых современных армейских винтовок. Классическая компоновка. Простота конструкции. Швейцарская точность и надежность. Никаких понтов."),
	AdditionalHint = T(534112939755, --[[ModItemInventoryItemCompositeDef Sig550 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая эффективность при стрельбе очередями"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 50000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 23,
	ObjDamageMod = 50,
	AimAccuracy = 22,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 48,
	OverwatchAngle = 1800,
	Noise = 50,
	HandSlot = "TwoHanded",
	Entity = "Sig550",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
				"StockHeavy",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
				"SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"SigDefHandGuard",
				"SigErgoHandGrip",
			},
			'DefaultComponent', "SigDefHandGuard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"DefaultIronsight_AR15",
			},
			'DefaultComponent', "DefaultIronsight_AR15",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 4000,
	Recoil = 8,
	AutoShots = 6,
	Handling = 74,
	BulletDropRange = 17,
	Grouping = 300,
	BaseJamChance = -30,
}

