UndefineClass('Sig552')
DefineClass.Sig552 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T3+",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/SIG552.png",
	DisplayName = T(829842196548, --[[ModItemInventoryItemCompositeDef Sig552 DisplayName]] "Sig 552"),
	DisplayNamePlural = T(668776562271, --[[ModItemInventoryItemCompositeDef Sig552 DisplayNamePlural]] "Sig 552"),
	Description = T(264662710858, --[[ModItemInventoryItemCompositeDef Sig552 Description]] "Ультракомпактный автомат производства SIG с классической компоновкой и не менее классической газоотводной системой. Серьезное дорогое оружие."),
	AdditionalHint = T(859037642619, --[[ModItemInventoryItemCompositeDef Sig552 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Можно использовать для стрельбы на бегу\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Низкая отдача"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 65000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 22,
	ObjDamageMod = 50,
	AimAccuracy = 17,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 40,
	OverwatchAngle = 2280,
	Noise = 48,
	HandSlot = "TwoHanded",
	Entity = "SIG552",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"SigDefHandGuard",
				"SigErgoHandGrip",
			},
			'DefaultComponent', "SigDefHandGuard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
				"StockHeavy",
			},
			'DefaultComponent', "UnfoldStocks",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
				"SuppressorImproved",
			},
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"CancelShot",
		"RunAndGun",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	Recoil = 9,
	AutoShots = 7,
	Handling = 85,
	BulletDropRange = 16,
	Grouping = 250,
	BaseJamChance = -30,
	WeaponResource = 9000,
}

