UndefineClass('Sig550')
DefineClass.Sig550 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 16,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/SIG550.png",
	DisplayName = T(937651754900, --[[ModItemInventoryItemCompositeDef Sig550 DisplayName]] "Sig 550"),
	DisplayNamePlural = T(501240162927, --[[ModItemInventoryItemCompositeDef Sig550 DisplayNamePlural]] "Sig 550"),
	Description = T(453269317328, --[[ModItemInventoryItemCompositeDef Sig550 Description]] "Что получится, если АК попытаются изобрести в Швейцарии? Получится одна из самых крутых современных армейских винтовок. Классическая компоновка. Простота конструкции. Швейцарская точность и надежность. Никаких понтов."),
	AdditionalHint = T(534112939755, --[[ModItemInventoryItemCompositeDef Sig550 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Можно забрать домой после срочной службы"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 24000,
	CanAppearInShop = true,
	Tier = 4,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 24,
	ObjDamageMod = 50,
	AimAccuracy = 15,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 48,
	OverwatchAngle = 1200,
	Noise = 46,
	HandSlot = "TwoHanded",
	Entity = "Sig550",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_50_SIG",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockHeavy",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Bipod",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"JAZZ_SigDefHandGuard",
				"JAZZ_SigErgoHandGrip",
			},
			'DefaultComponent', "JAZZ_SigDefHandGuard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"JAZZ_DefaultIronsight_AR15",
			},
			'DefaultComponent', "JAZZ_DefaultIronsight_AR15",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	WeaponMass = 41,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 3,
	BurstShots = 3,
	Recoil = 14,
	AutoShots = 7,

	CloseRange = 8,

	CloseRangeFactor = 85,
	BulletDropRange = 17,
	Grouping = 63,
	BaseJamChance = -30,
	WeaponResource = 9500,
}

