UndefineClass('Sig552')
DefineClass.Sig552 = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-1",
	object_class = "Carbine",
	ScrapParts = 10,
	RepairCost = 16,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/SIG552.png",
	DisplayName = T(829842196548, --[[ModItemInventoryItemCompositeDef Sig552 DisplayName]] "Sig 552"),
	DisplayNamePlural = T(668776562271, --[[ModItemInventoryItemCompositeDef Sig552 DisplayNamePlural]] "Sig 552"),
	Description = T(264662710858, --[[ModItemInventoryItemCompositeDef Sig552 Description]] "Ультракомпактный автомат производства SIG с классической компоновкой и не менее классической газоотводной системой. Серьезное дорогое оружие."),
	AdditionalHint = T(859037642619, --[[ModItemInventoryItemCompositeDef Sig552 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 65000,
	CanAppearInShop = true,
	Tier = 3,
	RestockWeight = 40,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 24,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	CritChanceScaled = 20,
	MagazineSize = 30,
	WeaponRange = 40,
	OverwatchAngle = 1560,
	Noise = 48,
	HandSlot = "TwoHanded",
	Entity = "SIG552",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_50_SIG",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'AvailableComponents', {
				"JAZZ_SigDefHandGuard",
				"JAZZ_SigErgoHandGrip",
			},
			'DefaultComponent', "JAZZ_SigDefHandGuard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_50_SIG",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockHeavy",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
				"JAZZ_Suppressor",
				"JAZZ_SuppressorImproved",
			},
		}),
	},
	Color = "Black",
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	WeaponMass = 32,
	CyclicRPM = 700,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	BurstShots = 4,
	Recoil = 20,
	AutoShots = 7,

	CloseRange = 5,

	CloseRangeFactor = 90,
	BulletDropRange = 17,
	Grouping = 63,
	BaseJamChance = -30,
	WeaponResource = 9000,
}

