UndefineClass('SKS')
DefineClass.SKS = {
	__parents = { "BattleRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "BattleRifle",
	msg_reactions = {},
	unit_reactions = {},
	ScrapParts = 10,
	RepairCost = 4,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/SKS.png",
	DisplayName = T(532780533839, --[[ModItemInventoryItemCompositeDef SKS DisplayName]] "СКС"),
	DisplayNamePlural = T(941296279714, --[[ModItemInventoryItemCompositeDef SKS DisplayNamePlural]] "СКС"),
	Description = T(410577681665, --[[ModItemInventoryItemCompositeDef SKS Description]] "Не востребованный в Советской Армии, тем не менее, весьма любим гражданскими стрелками в России за точность боя. Но это капля в море перед маниакальной страстью к нему стрелков в США. Хорошим тоном считается хотя бы один СКС на коллекцию. Хотя бы и китайский."),
	AdditionalHint = T(874658345000, --[[ModItemInventoryItemCompositeDef SKS AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Карабин под семерку \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстро стреляет"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 120,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x39",
	Damage = 28,
	ObjDamageMod = 50,
	AimAccuracy = 13,
	CritChanceScaled = 30,
	MagazineSize = 10,
	WeaponRange = 44,
	PointBlankBonus = 1,
	OverwatchAngle = 1320,
	Noise = 52,
	HandSlot = "TwoHanded",
	Entity = "SKS",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"JAZZ_Salvo",
	},
	ShootAP = 6000,
	ReloadAP = 5000,
	BurstShots = 0,
	WeaponMass = 36,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 21,
	AutoShots = 0,

	CloseRange = 8,

	CloseRangeFactor = 80,
	BulletDropRange = 16,
	Grouping = 60,
	BaseJamChance = -30,
	WeaponResource = 6000,
}

