UndefineClass('SKS')
DefineClass.SKS = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1-",
	object_class = "SniperRifle",
	msg_reactions = {},
	unit_reactions = {},
	ScrapParts = 10,
	RepairCost = 20,
	Reliability = 80,
	Icon = "Mod/e6L4ECj/WeaponIcons/SKS.png",
	ItemType = "DMR",
	DisplayName = T(532780533839, --[[ModItemInventoryItemCompositeDef SKS DisplayName]] "СКС"),
	DisplayNamePlural = T(941296279714, --[[ModItemInventoryItemCompositeDef SKS DisplayNamePlural]] "СКС"),
	Description = T(410577681665, --[[ModItemInventoryItemCompositeDef SKS Description]] "Не востребованный в Советской Армии, тем не менее, весьма любим гражданскими стрелками в России за точность боя. Но это капля в море перед маниакальной страстью к нему стрелков в США. Хорошим тоном считается хотя бы один СКС на коллекцию. Хотя бы и китайский."),
	AdditionalHint = T(874658345000, --[[ModItemInventoryItemCompositeDef SKS AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможность стрельбы на бегу"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 120,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x39",
	Damage = 28,
	ObjDamageMod = 50,
	AimAccuracy = 25,
	CritChance = 5,
	CritChanceScaled = 20,
	MagazineSize = 10,
	WeaponRange = 40,
	PointBlankBonus = 1,
	OverwatchAngle = 1500,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "SKS",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 62,
	BulletDropRange = 15,
	Grouping = 265,
	BaseJamChance = -30,
}

