UndefineClass('SmokeGrenade')
DefineClass.SmokeGrenade = {
	__parents = { "GrenadeItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/SmokeGrenade",
	ItemType = "Throwables",
	DisplayName = T(672761107292, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayName]] "Smoke Grenade"),
	DisplayNamePlural = T(783603654199, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayNamePlural]] "Smoke Grenades"),
	AdditionalHint = T(206588175055, --[[ModItemInventoryItemCompositeDef SmokeGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Не наносит урона\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Почти бесшумна"),
	UnitStat = "Explosives",
	Cost = 300,
	CanAppearInShop = true,
	Tier = 1,
	RestockWeight = 50,
	MaxStock = 8,
	CategoryPair = "Grenade",
	MaxStacks = 2,
	MinMishapChance = -2,
	MaxMishapChance = 40,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 5,
	AttackAP = 4000,
	BaseRange = 12,
	ThrowMaxRange = 24,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 5,
	aoeType = "smoke",
	Entity = "Weapon_SmokeGrenade_Test",
	ActionIcon = "UI/Icons/Hud/smoke_grenade",
}

