UndefineClass('SmokeGrenade')
DefineClass.SmokeGrenade = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/SmokeGrenade",
	ItemType = "Throwables",
	DisplayName = T(529889768393, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayName]] "Дымовая граната"),
	DisplayNamePlural = T(564232117531, --[[ModItemInventoryItemCompositeDef SmokeGrenade DisplayNamePlural]] "Дымовые гранаты"),
	AdditionalHint = T(206588175055, --[[ModItemInventoryItemCompositeDef SmokeGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Выстрелы, совершенные сквозь облака газа, дают лишь <color EmStyle>незначительные попадания</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Не наносит урона\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Почти бесшумна"),
	UnitStat = "Explosives",
	Cost = 300,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 25,
	CategoryPair = "Grenade",
	MinMishapChance = -2,
	MaxMishapChance = 40,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 5,
	AttackAP = 4000,
	BaseRange = 12,
	ThrowMaxRange = 18,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 0,
	aoeType = "smoke",
	Entity = "Weapon_SmokeGrenade_Test",
	ActionIcon = "UI/Icons/Hud/smoke_grenade",
}

