UndefineClass('SPAS12')
DefineClass.SPAS12 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/Spas12.png",
	ItemType = "Shotgun",
	DisplayName = T(820865531430, --[[ModItemInventoryItemCompositeDef SPAS12 DisplayName]] "SPAS-12"),
	DisplayNamePlural = T(127311436093, --[[ModItemInventoryItemCompositeDef SPAS12 DisplayNamePlural]] "SPAS-12"),
	Description = T(117074449677, --[[ModItemInventoryItemCompositeDef SPAS12 Description]] "Харизматичный боевой дробовик, который участвовал, наверное, в каждом боевике 80х и 90х. Кроме запоминающегося внешнего вида примечателен еще тем, что запрещен к продаже во многих странах, включая США. К сожалению, выпуск запчастей и обслуживание имеющихся на руках у владельцев дробовиков SPAS компанией Franchi был прекращен. Рыночек. Порешал."),
	AdditionalHint = T(163607039190, --[[ModItemInventoryItemCompositeDef SPAS12 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дробовик \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Хороший бой"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 28000,
	CanAppearInShop = true,
	Tier = 2,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 8,
	MagazineSize = 6,
	WeaponRange = 23,
	PointBlankBonus = 1,
	OverwatchAngle = 1080,
	BuckshotConeAngle = 180,
	BuckshotFalloffDamage = 15,
	Noise = 32,
	HandSlot = "TwoHanded",
	Entity = "Spas12",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"Buckshot",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 5000,
	ReloadAP = 7000,
	BurstShots = 1,
	AutoShots = 1,

	CloseRange = 4,

	CloseRangeFactor = 90,
	BulletDropRange = 9,
	Grouping = 140,
	WeaponResource = 2800,
	CanAppearUsed = false,
}

