UndefineClass('SpectreM4')
DefineClass.SpectreM4 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 8,
	Reliability = 55,
	Icon = "Mod/e6L4ECj/WeaponIcons/SpectreM4.png",
	DisplayName = T(248441865106, --[[ModItemInventoryItemCompositeDef SpectreM4 DisplayName]] "Spectre M4"),
	DisplayNamePlural = T(647142447172, --[[ModItemInventoryItemCompositeDef SpectreM4 DisplayNamePlural]] "Spectre M4"),
	Description = T(462344051547, --[[ModItemInventoryItemCompositeDef SpectreM4 Description]] 'Оружие для сил специального назначения и борьбы с терроризмом. Курковый спусковой механизм "двойного действия" (прям как на револьверах, ага) обеспечивает безопасное ношение оружия с патроном в патроннике без необходимости досыла патрона в случае контакта с противником.'),
	AdditionalHint = T(424006445377, --[[ModItemInventoryItemCompositeDef SpectreM4 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Без приклада \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Скорострельный  "),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5750,
	CanAppearInShop = true,
	Tier = 3,
	MaxStock = 5,
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 21,
	ObjDamageMod = 20,
	AimAccuracy = 9,
	MagazineSize = 50,
	WeaponRange = 25,
	OverwatchAngle = 4080,
	Noise = 34,
	Entity = "Spectr_M4",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 6000,
	WeaponMass = 29,
	CyclicRPM = 850,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	MaxAimActions = 2,
	Recoil = 18,
	BurstShots = 4,
	AutoShots = 8,

	CloseRange = 3,

	CloseRangeFactor = 95,
	BulletDropRange = 10,
	Grouping = 68,
	BaseJamChance = -20,
	WeaponResource = 3000,
}

