UndefineClass('SpectreM4')
DefineClass.SpectreM4 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-3",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 8,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/SpectreM4.png",
	DisplayName = T(248441865106, "Spectre M4"),
	DisplayNamePlural = T(647142447172, "Spectre M4"),
	Description = T(462344051547, 'Оружие для сил специального назначения и борьбы с терроризмом. Курковый спусковой механизм "двойного действия" (прям как на револьверах, ага) обеспечивает безопасное ношение оружия с патроном в патроннике без необходимости досыла патрона в случае контакта с противником.'),
	AdditionalHint = T(424006445377, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Низкая точность прицельной стрельбы\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая эффективность при стрельбе навскидку"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2800,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 19,
	ObjDamageMod = 20,
	AimAccuracy = 9,
	MagazineSize = 50,
	WeaponRange = 25,
	OverwatchAngle = 4080,
	Noise = 34,
	Entity = "Spectr_M4",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 6000,
	MaxAimActions = 2,
	Recoil = 5,
	BurstShots = 4,
	AutoShots = 9,
	Handling = 81,
	BulletDropRange = 9,
	Grouping = 80,
	BaseJamChance = -20,
	WeaponResource = 3000,
}

