UndefineClass('SR3M')
DefineClass.SR3M = {
	MaxStock = 1,
	CanAppearInShop = true,
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "SubmachineGun",
	ScrapParts = 10,
	RepairCost = 30,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/SR3M.png",
	DisplayName = T(761915300101, "СР-3М"),
	DisplayNamePlural = T(761915300102, "СР-3М"),
	Description = T(761915300103, "Компактный автомат под патрон 9×39 мм со складным прикладом и магазином на 30 патронов. В этой комплектации установлен штатный дульный насадок, без глушителя."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 22000,
	Tier = 4,
	RestockWeight = 20,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x39",
	Damage = 32,
	ObjDamageMod = 50,
	AimAccuracy = 10,
	CritChanceScaled = 30,
	MagazineSize = 30,
	WeaponRange = 26,
	OverwatchAngle = 1500,
	Noise = 30,
	HandSlot = "TwoHanded",
	Entity = "SR3M",
	fxClass = "AK74",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Handguard",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_Handguard",
			},
			'DefaultComponent', "JAZZ_Handguard",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_DefMuzzle",
			},
			'DefaultComponent', "JAZZ_DefMuzzle",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	MaxAimActions = 2,
	Recoil = 20,
	BurstShots = 4,
	AutoShots = 9,
	WeaponMass = 27,
	CyclicRPM = 900,
	WeaponSizeClass = "Compact",
	CloseRange = 3,
	CloseRangeFactor = 95,
	BulletDropRange = 11,
	Grouping = 58,
	BaseJamChance = -30,
	WeaponResource = 3000,
}

