UndefineClass('Sterling')
DefineClass.Sterling = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-2",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 3,
	Reliability = 55,
	Icon = "Mod/e6L4ECj/WeaponIcons/Sterling.png",
	DisplayName = T(488309253436, --[[ModItemInventoryItemCompositeDef Sterling DisplayName]] "Стерлинг"),
	DisplayNamePlural = T(214431276583, --[[ModItemInventoryItemCompositeDef Sterling DisplayNamePlural]] "СТЕРЛИНГ"),
	Description = T(919621275120, --[[ModItemInventoryItemCompositeDef Sterling Description]] "Поздневоенный и послевоенный британский автомат. Характерной чертой автомата является примыкаемый сбоку магазин, за который он и удерживается при стрельбе, что удобно в походе, но неудобно в бою. В целом, неплохой автомат. С учетом того, что британский."),
	AdditionalHint = T(468046569228, --[[ModItemInventoryItemCompositeDef Sterling AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Складной приклад \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Годится на безрыбье"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2200,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 60,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 21,
	ObjDamageMod = 20,
	AimAccuracy = 5,
	MagazineSize = 34,
	WeaponRange = 25,
	OverwatchAngle = 4200,
	Noise = 32,
	HandSlot = "TwoHanded",
	Entity = "Sterling",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightFolded",
				"JAZZ_StockLightUnFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	WeaponMass = 33,
	CyclicRPM = 550,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	MaxAimActions = 2,
	Recoil = 18,
	BurstShots = 3,
	AutoShots = 6,

	CloseRange = 2,

	CloseRangeFactor = 95,
	BulletDropRange = 9,
	Grouping = 34,
	BaseJamChance = -20,
	WeaponResource = 3200,
}

