UndefineClass('STG44')
DefineClass.STG44 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 3,
	Icon = "Mod/e6L4ECj/WeaponIcons/STG44.png",
	DisplayName = T(890000000000205, --[[ModItemInventoryItemCompositeDef STG44 DisplayName]] "StG-44"),
	DisplayNamePlural = T(890000000000073, --[[ModItemInventoryItemCompositeDef STG44 DisplayNamePlural]] "StG-44"),
	Description = T(890000000000018, --[[ModItemInventoryItemCompositeDef STG44 Description]] 'Первый в мире серийный автомат, или штурмовая винтовка. Собсно, "Штурмгевер" и означает штурмовая винтовка (говорят, Гитлер лично придумал, но больше похоже на байку). Несмотря на то, что на ход войны вундервафля уже влияния не оказала, именно на ней была опробована и успешно получила развитие идея "промежуточного" патрона.'),
	AdditionalHint = T(160551721775, --[[ModItemInventoryItemCompositeDef STG44 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Первый \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Старый \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Ненадежный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1500,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_792x33",
	Damage = 24,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	MagazineSize = 30,
	WeaponRange = 32,
	OverwatchAngle = 1140,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "STG44",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Scope_ZF4",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"HandlingWrap",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	Recoil = 18,
	AutoShots = 5,
	Handling = -15,
	BulletDropRange = 12,
	Grouping = 66,
	WeaponResource = 2500,
}

