UndefineClass('Stoeger')
DefineClass.Stoeger = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-UNIQ",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 6,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 40,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/Stoeger.png",
	DisplayName = T(373181623240, --[[ModItemInventoryItemCompositeDef Stoeger DisplayName]] "Вертикалка"),
	DisplayNamePlural = T(677632158950, --[[ModItemInventoryItemCompositeDef Stoeger DisplayNamePlural]] "Вертикалки"),
	Description = T(169244335459, --[[ModItemInventoryItemCompositeDef Stoeger Description]] 'Бокфлинт - или двуствольное охотничье ружье "вертикалка". Для местных выглядит дороговасто, так что, похоже, кое-кто из иностранных туристов-охотников решил перехать в Гранд-Чиен навсегда.'),
	AdditionalHint = T(260147426645, --[[ModItemInventoryItemCompositeDef Stoeger AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Двустволка \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстро стреляет \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный бой \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удобный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 4000,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 2,
	WeaponRange = 21,
	PointBlankBonus = 1,
	OverwatchAngle = 1680,
	BuckshotConeAngle = 180,
	BuckshotProjectiles = 1,
	BuckshotFalloffDamage = 10,
	Noise = 34,
	HandSlot = "TwoHanded",
	Entity = "stoeger_outback",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"DoubleBarrel",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 5000,
	ReloadAP = 3000,
	BurstShots = 0,
	WeaponMass = 36,
	CyclicRPM = 0,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	Recoil = 25,
	AutoShots = 0,

	CloseRange = 5,

	CloseRangeFactor = 90,
	BulletDropRange = 8,
	Grouping = 160,
	BaseJamChance = -100,
	WeaponResource = 3000,
}

