UndefineClass('Stoeger')
DefineClass.Stoeger = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1+",
	object_class = "Shotgun",
	ScrapParts = 10,
	RepairCost = 6,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/Stoeger.png",
	DisplayName = T(373181623240, --[[ModItemInventoryItemCompositeDef Stoeger DisplayName]] "Вертикалка"),
	DisplayNamePlural = T(677632158950, --[[ModItemInventoryItemCompositeDef Stoeger DisplayNamePlural]] "Вертикалки"),
	Description = T(169244335459, --[[ModItemInventoryItemCompositeDef Stoeger Description]] 'Бокфлинт - или двуствольное охотничье ружье "вертикалка". Для местных выглядит дороговасто, так что, похоже, кое-кто из иностранных туристов-охотников решил перехать в Гранд-Чиен навсегда.'),
	AdditionalHint = T(260147426645, --[[ModItemInventoryItemCompositeDef Stoeger AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Двустволка - низкие затраты од на выстрел и перезарядку\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2500,
	CategoryPair = "Shotguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 15,
	MagazineSize = 2,
	WeaponRange = 21,
	PointBlankBonus = 1,
	OverwatchAngle = 1680,
	BuckshotConeAngle = 180,
	BuckshotFalloffDamage = 10,
	Noise = 34,
	HandSlot = "TwoHanded",
	Entity = "stoeger_outback",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"Buckshot",
		"DoubleBarrel",
		"CancelShot",
	},
	ShootAP = 4000,
	ReloadAP = 3000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = 79,
	BulletDropRange = 8,
	Grouping = 160,
	BaseJamChance = -100,
	WeaponResource = 3000,
}

