UndefineClass('SVU')
DefineClass.SVU = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T3",
	object_class = "SniperRifle",
	ScrapParts = 14,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/SVU.png",
	ItemType = "DMR",
	DisplayName = T(945667888261, --[[ModItemInventoryItemCompositeDef SVU DisplayName]] "СВУ"),
	DisplayNamePlural = T(220809633195, --[[ModItemInventoryItemCompositeDef SVU DisplayNamePlural]] "СВУ"),
	Description = T(109657201401, --[[ModItemInventoryItemCompositeDef SVU Description]] 'СВД в компоновке буллпап. Из-за чего, а также из-за укороченного ствола, короче старшей сестры на 25 см, что повышает ее эффективность в маневренном городском бою. Однако, из-за компоновки буллпап спуск на длинной тяге вынесен вперед, что для снайперской винтовки неблагоприятно. Стрелок не чувствует момент "срыва курка".'),
	AdditionalHint = T(899701284012, --[[ModItemInventoryItemCompositeDef SVU AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность навскидку\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможность стрельбы очередями или в автоматическом режиме"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 90000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x54R",
	Damage = 38,
	ObjDamageMod = 80,
	AimAccuracy = 30,
	CritChanceScaled = 20,
	MagazineSize = 10,
	WeaponRange = 70,
	OverwatchAngle = 1200,
	Noise = 40,
	HandSlot = "TwoHanded",
	Entity = "SVU",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Scope_PSO",
				"JAZZ_Reflex_Cobra",
				"JAZZ_CombatScope_1P29",
				"JAZZ_NightScope_NSPU",
				"JAZZ_Reflex_PKAS",
			},
			'DefaultComponent', "JAZZ_Scope_PSO",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"BurstFire",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 25,
	AutoShots = 6,
	Handling = 60,
	BulletDropRange = 24,
	Grouping = 380,
	BaseJamChance = -20,
}

