UndefineClass('SVU')
DefineClass.SVU = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "SniperRifle",
	ScrapParts = 14,
	RepairCost = 15,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/SVU.png",
	DisplayName = T(945667888261, --[[ModItemInventoryItemCompositeDef SVU DisplayName]] "СВУ"),
	DisplayNamePlural = T(220809633195, --[[ModItemInventoryItemCompositeDef SVU DisplayNamePlural]] "СВУ"),
	Description = T(109657201401, --[[ModItemInventoryItemCompositeDef SVU Description]] 'СВД в компоновке буллпап. Из-за чего, а также из-за укороченного ствола, короче старшей сестры на 25 см, что повышает ее эффективность в маневренном городском бою. Однако, из-за компоновки буллпап спуск на длинной тяге вынесен вперед, что для снайперской винтовки неблагоприятно. Стрелок не чувствует момент "срыва курка".'),
	AdditionalHint = T(899701284012, --[[ModItemInventoryItemCompositeDef SVU AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Стреляет очередями \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> сильная отдача"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 90000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_762x54R",
	Damage = 38,
	ObjDamageMod = 80,
	AimAccuracy = 15,
	CritChanceScaled = 30,
	MagazineSize = 10,
	WeaponRange = 75,
	OverwatchAngle = 900,
	Noise = 30,
	HandSlot = "TwoHanded",
	Entity = "SVU",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Scope_PSO",
				"JAZZ_Reflex_Cobra",
				"JAZZ_CombatScope_1P29",
				"JAZZ_NightScope_NSPU",
				"JAZZ_Reflex_PKAS",
			},
			'DefaultComponent', "JAZZ_Scope_PSO",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Bipod",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Bipod",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"BurstFire",
		"JAZZ_JokerShot",
		"JAZZ_Bullseye",
	},
	ShootAP = 6000,
	ReloadAP = 9000,
	Recoil = 25,
	AutoShots = 6,
	Handling = -8,
	BulletDropRange = 19,
	Grouping = 44,
	BaseJamChance = -20,
	WeaponResource = 6500,
}

