UndefineClass('SWModel10')
DefineClass.SWModel10 = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 1,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/SWModel10.png",
	DisplayName = T(436628869426, --[[ModItemInventoryItemCompositeDef SWModel10 DisplayName]] "S&W Model10 .38 Special"),
	DisplayNamePlural = T(427566606201, --[[ModItemInventoryItemCompositeDef SWModel10 DisplayNamePlural]] "S&W Model10 .38 Special"),
	Description = T(878461703337, --[[ModItemInventoryItemCompositeDef SWModel10 Description]] "Один из самых распространенных боевых револьверов в мире. За все время компания S&W выпустила револверы Military and Police объемом более 6 миллионов штук. Начинал служить еще в Первую Мировую, продолжает выпускаться до сих пор. "),
	AdditionalHint = T(434107786112, --[[ModItemInventoryItemCompositeDef SWModel10 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Револьвер .38 Special\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Компактный Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Лучше Кольта"),
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_38",
	Damage = 16,
	ObjDamageMod = 40,
	AimAccuracy = 8,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 15,
	OverwatchAngle = 5100,
	Noise = 15,
	Entity = "SWModel10",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelShort_Pistol",
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
	},
	Color = "Default",
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"JAZZ_Fanning",
		"JAZZ_Bullseye",
	},
	ShootAP = 3000,
	ReloadAP = 5000,
	Recoil = 1,
	AutoShots = 3,
	Handling = 18,
	BulletDropRange = 7,
	Grouping = 56,
	BaseJamChance = -100,
}

