UndefineClass('SWModel10')
DefineClass.SWModel10 = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-1",
	object_class = "Revolver",
	ReloadStyle = "Revolver",
	ScrapParts = 6,
	RepairCost = 1,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/SWModel10.png",
	DisplayName = T(890000000000527, --[[ModItemInventoryItemCompositeDef SWModel10 DisplayName]] "S&W Model10 .38 Special"),
	DisplayNamePlural = T(890000000000503, --[[ModItemInventoryItemCompositeDef SWModel10 DisplayNamePlural]] "S&W Model10 .38 Special"),
	Description = T(890000000001224, --[[ModItemInventoryItemCompositeDef SWModel10 Description]] "Один из самых распространенных боевых револьверов в мире. За все время компания S&W выпустила револверы Military and Police объемом более 6 миллионов штук. Начинал служить еще в Первую Мировую, продолжает выпускаться до сих пор. "),
	AdditionalHint = T(890000000000519, --[[ModItemInventoryItemCompositeDef SWModel10 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Револьвер .38 Special\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Компактный Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Лучше Кольта"),
	UnitStat = "Marksmanship",
	Cost = 800,
	CanAppearInShop = true,
	Tier = 1,
	RestockWeight = 110,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_38",
	Damage = 16,
	ObjDamageMod = 40,
	AimAccuracy = 16,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 16,
	OverwatchAngle = 5100,
	Noise = 15,
	Entity = "SWModel10",
	ComponentSlots = {
		
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"JAZZ_BarrelShort_Pistol",
				"JAZZ_BarrelNormal",
			},
			'DefaultComponent', "JAZZ_BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Flashlight",
				"JAZZ_FlashlightOff",
				"JAZZ_LaserDot",
				"JAZZ_FlashlightDot",
				"JAZZ_UVDot",
			},
		}),
	},
	Color = "Default",
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"JAZZ_Fanning",
		"JAZZ_Bullseye",
	},
	ShootAP = 3000,
	ReloadAP = 5000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	Recoil = 15,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 5,
	Grouping = 50,
	BaseJamChance = -100,
}

