UndefineClass('SWModel5906')
DefineClass.SWModel5906 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 4,
	Icon = "Mod/e6L4ECj/WeaponIcons/SW5906.png",
	DisplayName = T(848119151903, --[[ModItemInventoryItemCompositeDef SWModel5906 DisplayName]] "S&W Model 5906"),
	DisplayNamePlural = T(927743133237, --[[ModItemInventoryItemCompositeDef SWModel5906 DisplayNamePlural]] "S&W Model 5906"),
	Description = T(107106412369, --[[ModItemInventoryItemCompositeDef SWModel5906 Description]] 'Спортивный, боевой, полицейский, гражданский пистолет из Чехии. Практически, победитель оружейного "Евровидения", но первое место принадлежит тому, кого нельзя называть. Иначе придется его купить.'),
	AdditionalHint = T(491343014488, --[[ModItemInventoryItemCompositeDef SWModel5906 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность"),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 23,
	ObjDamageMod = 20,
	AimAccuracy = 10,
	CritChance = 5,
	CritChanceScaled = 35,
	MagazineSize = 16,
	WeaponRange = 18,
	OverwatchAngle = 5400,
	Noise = 22,
	Entity = "SWModel5906",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
			'DefaultComponent', "su",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 84,
	BulletDropRange = 6,
	Grouping = 94,
	BaseJamChance = -20,
}

