UndefineClass('SWModel52')
DefineClass.SWModel52 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 1-2",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 7,
	Reliability = 30,
	Icon = "Mod/e6L4ECj/WeaponIcons/SW52.png",
	DisplayName = T(890000000001153, --[[ModItemInventoryItemCompositeDef SWModel52 DisplayName]] "S&W Model 52 .38 Special Pistol"),
	DisplayNamePlural = T(890000000001293, --[[ModItemInventoryItemCompositeDef SWModel52 DisplayNamePlural]] "S&W Model 52"),
	Description = T(890000000000007, --[[ModItemInventoryItemCompositeDef SWModel52 Description]] "Пистолет Смита и Вессона, так же известен как 38 Mastered. Представляет собой интересную конверсию вполне себе боевого пистолета модели 39 под патрон .38 S&W Special да еще и со специальными тупоконечными цилиндрическими пулями Wadcutter. В магазине из-за размеров патрона помещается всего 5 патронов, так что особо не разгуляешься."),
	AdditionalHint = T(890000000000605, --[[ModItemInventoryItemCompositeDef SWModel52 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  .38 Special\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  Cпасибо, что стреляет"),
	UnitStat = "Marksmanship",
	Cost = 2100,
	CanAppearInShop = false,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_38",
	Damage = 15,
	ObjDamageMod = 20,
	AimAccuracy = 12,
	CritChanceScaled = 35,
	MagazineSize = 5,
	WeaponRange = 14,
	OverwatchAngle = 5400,
	Noise = 22,
	Entity = "SWModel52",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_13_PISTOL_52",
				"JAZZ_MagLarge_8_PISTOL_52",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
								"JAZZ_ImprovisedSuppressor",
								"JAZZ_Suppressor",
							},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	Recoil = 15,
	AutoShots = 0,
	BulletDropRange = 5,

	CloseRange = 0,

	CloseRangeFactor = 100,
	Grouping = 88,
	BaseJamChance = -20,
	WeaponResource = 700,
}

