UndefineClass('SWModel29')
DefineClass.SWModel29 = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 4,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/SWModel29.png",
	DisplayName = T(436628869426, --[[ModItemInventoryItemCompositeDef SWModel29 DisplayName]] "SWModel29"),
	DisplayNamePlural = T(427566606201, --[[ModItemInventoryItemCompositeDef SWModel29 DisplayNamePlural]] "SWModel29"),
	Description = T(878461703337, --[[ModItemInventoryItemCompositeDef SWModel29 Description]] "Мощный револьвер Смита и Вессона под патрон .44 Magnum. Как и другие подобные револьверы повышенной мощности прежде всего применяется для охоты или спортивной стрельбы, но... как же приятно засадить Легу в жбан из сорок четвертого."),
	AdditionalHint = T(434107786112, --[[ModItemInventoryItemCompositeDef SWModel29 AdditionalHint]] "Баюн не сделал описание этому предмету :("),
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_44CAL",
	Damage = 42,
	ObjDamageMod = 40,
	AimAccuracy = 16,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 21,
	OverwatchAngle = 5100,
	Noise = 32,
	Entity = "SWModel29",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelShort_Pistol",
				"BarrelNormal",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
	},
	Color = "Black",
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	Recoil = 1,
	AutoShots = 3,
	Handling = 75,
	BulletDropRange = 7,
	Grouping = 92,
	BaseJamChance = -100,
}

