UndefineClass('TearGasGrenade')
DefineClass.TearGasGrenade = {
	__parents = { "GrenadeItem" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "GrenadeItem",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/TearGasGrenade",
	ItemType = "GrenadeGas",
	DisplayName = T(591872286262, --[[ModItemInventoryItemCompositeDef TearGasGrenade DisplayName]] "Tear Gas Grenade"),
	DisplayNamePlural = T(942175585447, --[[ModItemInventoryItemCompositeDef TearGasGrenade DisplayNamePlural]] "Tear Gas Grenades"),
	AdditionalHint = T(212902513488, --[[ModItemInventoryItemCompositeDef TearGasGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Вызывает <color EmStyle>слепоту</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Не наносит урона\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая вероятность неудачи\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Почти бесшумна"),
	UnitStat = "Explosives",
	Cost = 450,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 30,
	MaxStock = 5,
	CategoryPair = "Grenade",
	MaxStacks = 2,
	MinMishapChance = 2,
	MaxMishapChance = 50,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 5,
	AttackAP = 4000,
	BaseRange = 12,
	ThrowMaxRange = 24,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 5,
	aoeType = "teargas",
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/tear_gas_grenade",
}

