UndefineClass('TexRevolver')
DefineClass.TexRevolver = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-UNIQ",
	object_class = "Revolver",
	ScrapParts = 8,
	RepairCost = 15,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/Tex.png",
	DisplayName = T(520238058822, --[[ModItemInventoryItemCompositeDef TexRevolver DisplayName]] "Custom Six-Shooter"),
	DisplayNamePlural = T(463004632034, --[[ModItemInventoryItemCompositeDef TexRevolver DisplayNamePlural]] "Custom Six-Shooters"),
	Description = T(349928663403, --[[ModItemInventoryItemCompositeDef TexRevolver Description]] "A custom-built revolver with a 10-inch barrel and ivory handle featuring TEX engraved in a 14K gold."),
	AdditionalHint = T(916092268607, --[[ModItemInventoryItemCompositeDef TexRevolver AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Револьвер\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120>  Самый быстрый на всем Диком Западе"),
	UnitStat = "Marksmanship",
	Cost = 2000,
	locked = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_44CAL",
	Damage = 36,
	ObjDamageMod = 40,
	AimAccuracy = 8,
	CritChanceScaled = 60,
	MagazineSize = 6,
	PointBlankBonus = 1,
	OverwatchAngle = 5400,
	Noise = 40,
	Entity = "Tex_Rev",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"JAZZ_Fanning",
		"JAZZ_Bullseye",
	},
	ShootAP = 4000,
	ReloadAP = 5000,
	Recoil = 1,
	AutoShots = 3,
	Handling = 12,
	BulletDropRange = 7,
	Grouping = 70,
	BaseJamChance = -100,
	WeaponResource = 50000,
}

