UndefineClass('Thompson')
DefineClass.Thompson = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 3,
	Reliability = 30,
	Icon = "Mod/e6L4ECj/WeaponIcons/Thompson.png",
	ItemType = "SMG",
	DisplayName = T(479875631638, "Thompson"),
	DisplayNamePlural = T(527195562093, "Thompsons"),
	Description = T(526974325537, "Пистолет Пулемет Томпсона несет в себе черты автоматов периода ПМВ - большое количество фрезеровки, полусвободный затвор, большая масса и ручная подгонка движущихся деталей. На фоне куда более технологичных автоматов ВОВ он уже выглядит устаревшим. Пока не снесет голову врага в стальной каске на дистанции сто метров. Каску конечно, не пробьет, но врагу от этого не легче."),
	AdditionalHint = T(622369282107, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая эффективность на ближних дистанциях"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	CanAppearInShop = true,
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_45ACP",
	Damage = 26,
	ObjDamageMod = 25,
	AimAccuracy = 7,
	CritChance = 5,
	CritChanceScaled = 30,
	MagazineSize = 30,
	WeaponRange = 19,
	OverwatchAngle = 4320,
	Noise = 37,
	HandSlot = "TwoHanded",
	Entity = "THOMPSON_SMG",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagDrum_30-50",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	Recoil = 8,
	BurstShots = 4,
	AutoShots = 8,
	Handling = 66,
	BulletDropRange = 8,
	Grouping = 75,
	WeaponResource = 1800,
}

