UndefineClass('Thompson')
DefineClass.Thompson = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-3",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 3,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/Thompson.png",
	ItemType = "SMG",
	DisplayName = T(479875631638, --[[ModItemInventoryItemCompositeDef Thompson DisplayName]] "Thompson"),
	DisplayNamePlural = T(527195562093, --[[ModItemInventoryItemCompositeDef Thompson DisplayNamePlural]] "Thompsons"),
	Description = T(526974325537, --[[ModItemInventoryItemCompositeDef Thompson Description]] "Пистолет Пулемет Томпсона несет в себе черты автоматов периода ПМВ - большое количество фрезеровки, полусвободный затвор, большая масса и ручная подгонка движущихся деталей. На фоне куда более технологичных автоматов ВОВ он уже выглядит устаревшим. Пока не снесет голову врага в стальной каске на дистанции сто метров. Каску конечно, не пробьет, но врагу от этого не легче."),
	AdditionalHint = T(622369282107, --[[ModItemInventoryItemCompositeDef Thompson AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Убойный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Может использовать большой магазин"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	CanAppearInShop = true,
	RestockWeight = 70,
	CategoryPair = "SubmachineGuns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_45ACP",
	Damage = 23,
	ObjDamageMod = 25,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 30,
	WeaponRange = 19,
	OverwatchAngle = 4320,
	Noise = 37,
	HandSlot = "TwoHanded",
	Entity = "THOMPSON_SMG",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagDrum_30_50_THOMPSON",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	WeaponMass = 48,
	CyclicRPM = 700,
	WeaponSizeClass = "Carbine",
	BurstLimiter = 0,
	Recoil = 12,
	BurstShots = 4,
	AutoShots = 7,

	CloseRange = 2,

	CloseRangeFactor = 95,
	BulletDropRange = 8,
	Grouping = 75,
	WeaponResource = 1800,
}

