UndefineClass('TMP')
DefineClass.TMP = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-4",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 14,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/TMP2.png",
	ItemType = "SMG",
	DisplayName = T(408152361455, --[[ModItemInventoryItemCompositeDef TMP DisplayName]] "TMP"),
	DisplayNamePlural = T(432962097320, --[[ModItemInventoryItemCompositeDef TMP DisplayNamePlural]] "TMP"),
	Description = T(484204389251, --[[ModItemInventoryItemCompositeDef TMP Description]] 'Современный "маленький да удаленький" ПП австрийского производства. Изготовлен из высокопрочных полимеров, и является очень удобным оружием, хорошо контролируемым при автоматической стрельбе.'),
	AdditionalHint = T(887308010165, --[[ModItemInventoryItemCompositeDef TMP AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Больше не одноручный (по просьбе Ливси)\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Без приклада\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Скорострельный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 28000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 40,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 20,
	ObjDamageMod = 20,
	AimAccuracy = 10,
	MagazineSize = 30,
	WeaponRange = 18,
	OverwatchAngle = 4920,
	Noise = 25,
	HandSlot = "TwoHanded",
	Entity = "TMP",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagSmall30_15_TMP",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "General",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_HolsterBelt",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_PistolSuppressor",
			},
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	WeaponMass = 25,
	CyclicRPM = 900,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	MaxAimActions = 2,
	Recoil = 21,
	BurstShots = 4,
	AutoShots = 9,

	CloseRange = 3,

	CloseRangeFactor = 95,
	BulletDropRange = 10,
	Grouping = 85,
	BaseJamChance = -30,
	WeaponResource = 8500,
}

