UndefineClass('ToxicGasGrenade')
DefineClass.ToxicGasGrenade = {
	__parents = { "Grenade" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	object_class = "Grenade",
	Repairable = false,
	Reliability = 100,
	Icon = "UI/Icons/Weapons/ToxicGrenade",
	ItemType = "GrenadeGas",
	DisplayName = T(373806901180, --[[ModItemInventoryItemCompositeDef ToxicGasGrenade DisplayName]] "Граната с горч. газом"),
	DisplayNamePlural = T(118473499314, --[[ModItemInventoryItemCompositeDef ToxicGasGrenade DisplayNamePlural]] "Гранаты с горч. газом"),
	AdditionalHint = T(810838610815, --[[ModItemInventoryItemCompositeDef ToxicGasGrenade AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Вызывает <color EmStyle>удушье</color>\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Выстрелы, совершенные сквозь облака газа, дают лишь незначительные попадания\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая вероятность неудачи\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Почти бесшумна"),
	UnitStat = "Explosives",
	Tier = 3,
	CategoryPair = "Grenade",
	MaxStacks = 2,
	MinMishapChance = 2,
	MaxMishapChance = 50,
	MinMishapRange = 1,
	MaxMishapRange = 8,
	CenterUnitDamageMod = 0,
	CenterObjDamageMod = 0,
	AreaUnitDamageMod = 0,
	AreaObjDamageMod = 0,
	PenetrationClass = 1,
	BaseDamage = 0,
	Scatter = 5,
	AttackAP = 4000,
	BaseRange = 12,
	ThrowMaxRange = 18,
	InaccurateMinOffset = 3000,
	InaccurateMaxOffset = 10000,
	Noise = 0,
	aoeType = "toxicgas",
	Entity = "Weapon_MolotovCocktail",
	ActionIcon = "UI/Icons/Hud/toxic_grenade",
}

