UndefineClass('TT33')
DefineClass.TT33 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 3,
	Reliability = 50,
	Icon = "Mod/e6L4ECj/WeaponIcons/TT.png",
	DisplayName = T(879285674370, --[[ModItemInventoryItemCompositeDef TT33 DisplayName]] "Пистолет ТТ"),
	DisplayNamePlural = T(377868313170, --[[ModItemInventoryItemCompositeDef TT33 DisplayNamePlural]] "Пистолеты ТТ"),
	Description = T(492983145408, --[[ModItemInventoryItemCompositeDef TT33 Description]] 'Пистолет "Тульский-Токарева" представляет собой очередную вариацию схемы Браунинга на избитую советскую тему "у нас есть куча патронов на складах, нужно оружие для них".'),
	AdditionalHint = T(998090805654, --[[ModItemInventoryItemCompositeDef TT33 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дальнобойный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Пробивает броню\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Малый магазин\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Лучше, чем карате"),
	UnitStat = "Marksmanship",
	Cost = 350,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_762x25",
	Damage = 18,
	ObjDamageMod = 20,
	AimAccuracy = 6,
	MagazineSize = 8,
	WeaponRange = 19,
	OverwatchAngle = 5280,
	Noise = 26,
	Entity = "TT33f",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 3000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 12,
	BulletDropRange = 6,
	Grouping = 39,
	BaseJamChance = -10,
	WeaponResource = 750,
}

