UndefineClass('Type56')
DefineClass.Type56 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 3,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/Type56.png",
	DisplayName = T(890000000000206, --[[ModItemInventoryItemCompositeDef Type56 DisplayName]] "Type 56"),
	DisplayNamePlural = T(890000000000074, --[[ModItemInventoryItemCompositeDef Type56 DisplayNamePlural]] "Type 56"),
	Description = T(890000000000019, --[[ModItemInventoryItemCompositeDef Type56 Description]] "Пиратская, в смысле, китайская копия советского автомата АКС. Имеет складной вниз, либо фиксированный деревянный приклад и фрезерованную ствольную коробку. Качество разнится от нестреляющей рухляди до вполне приличного автомата. Длинный игольчатый штык призван делать канапе из лаоваев."),
	AdditionalHint = T(202927839636, --[[ModItemInventoryItemCompositeDef Type56 AdditionalHint]] '<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> "Опять китайское дерьмо" © Стив Борнелл'),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1500,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x39",
	Damage = 24,
	ObjDamageMod = 50,
	AimAccuracy = 8,
	MagazineSize = 30,
	WeaponRange = 38,
	OverwatchAngle = 1320,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "Type56",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagQuick_AK",
				"JAZZ_MagLarge_30_40",
				"JAZZ_MagDrum_30_75",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_Type56Bayo",
				"JAZZ_Type56BayoF",
			},
			'DefaultComponent', "JAZZ_Type56BayoF",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	WeaponMass = 36,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	BurstShots = 4,
	Recoil = 21,
	AutoShots = 7,

	CloseRange = 8,

	CloseRangeFactor = 85,
	BulletDropRange = 13,
	Grouping = 47,
	WeaponResource = 2500,
}

