UndefineClass('UMP45')
DefineClass.UMP45 = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "SubmachineGun",
	ScrapParts = 8,
	RepairCost = 12,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/UMP45.png",
	DisplayName = T(780815176267, "UMP45"),
	DisplayNamePlural = T(629372801982, "UMP45"),
	Description = T(606701682855, "Современный немецкий пистолет-пулемет на основе узлов винтовки G36, но со свободным затвором. Тяжеловат, но ухватист и хорошо контролируется при стрельбе очередями. "),
	AdditionalHint = T(109493312554, "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокий урон\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Режим очереди по 2 патрона"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 8000,
	CanAppearInShop = true,
	Tier = 2,
	RestockWeight = 50,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_45ACP",
	Damage = 27,
	ObjDamageMod = 25,
	AimAccuracy = 20,
	CritChance = 5,
	CritChanceScaled = 30,
	MagazineSize = 25,
	WeaponRange = 23,
	OverwatchAngle = 4200,
	Noise = 29,
	HandSlot = "TwoHanded",
	Entity = "UMP45",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Under",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"VerticalGrip",
				"TacGrip",
			},
			'DefaultComponent', "VerticalGrip",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"StockLightFolded",
				"StockLightUnFolded",
			},
			'DefaultComponent', "StockLightUnFolded",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Side",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Flashlight",
				"LaserDot",
				"FlashlightDot",
				"UVDot",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Open",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Eotech",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Compensator",
				"ImprovisedSuppressor",
				"PistolSuppressor",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 4000,
	Recoil = 7,
	BurstShots = 2,
	AutoShots = 6,
	Handling = 79,
	BulletDropRange = 8,
	Grouping = 90,
	BaseJamChance = -30,
	WeaponResource = 6000,
	CanAppearUsed = false,
}

