UndefineClass('USAS12')
DefineClass.USAS12 = {
	__parents = { "Shotgun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 3-2",
	object_class = "Shotgun",
	ScrapParts = 12,
	RepairCost = 16,
	Reliability = 60,
	Icon = "Mod/e6L4ECj/WeaponIcons/USAS12.png",
	DisplayName = T(851713933310, --[[ModItemInventoryItemCompositeDef USAS12 DisplayName]] "USAS12"),
	DisplayNamePlural = T(294591405946, --[[ModItemInventoryItemCompositeDef USAS12 DisplayNamePlural]] "USAS12"),
	Description = T(502898255631, --[[ModItemInventoryItemCompositeDef USAS12 Description]] "Гладкоствольное боевое ружье USAS-12 разработано американцем для американцев, максимально похоже внешне на любимые ими винтовки AR-15. Для продажи в США, однако, оказалось запрещено, поэтому начало скитаться по миру, отметившись в ЮАР и в Южной Корее."),
	AdditionalHint = T(317486111782, --[[ModItemInventoryItemCompositeDef USAS12 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Дробовик \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Большой магазин \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Valuable = 1,
	Cost = 60000,
	CanAppearInShop = true,
	Tier = 3,
	CategoryPair = "Shotguns",
	Caliber = "JAZZ_Caliber_12gauge",
	Damage = 4,
	ObjDamageMod = 50,
	AimAccuracy = 9,
	MagazineSize = 15,
	WeaponRange = 22,
	PointBlankBonus = 1,
	OverwatchAngle = 960,
	BuckshotConeAngle = 300,
	BuckshotFalloffDamage = 5,
	Noise = 30,
	HandSlot = "TwoHanded",
	Entity = "USAS12",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_3x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
			},
			'DefaultComponent', "JAZZ_Scope_6x",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"Suppressor",
				"Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"Buckshot",
		"JAZZ_JokerShot",
		"JAZZ_MobileShotgun",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = -20,
	BulletDropRange = 8,
	Grouping = 145,
	WeaponResource = 2500,
	CanAppearUsed = false,
}

