UndefineClass('UZI')
DefineClass.UZI = {
	__parents = { "SubmachineGun" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "SubmachineGun",
	ScrapParts = 6,
	RepairCost = 6,
	Reliability = 75,
	Icon = "Mod/e6L4ECj/WeaponIcons/UZI.png",
	DisplayName = T(919841472744, --[[ModItemInventoryItemCompositeDef UZI DisplayName]] "Узи Полноразмерный"),
	DisplayNamePlural = T(837213181188, --[[ModItemInventoryItemCompositeDef UZI DisplayNamePlural]] "Узи Полноразмерные"),
	Description = T(923965701752, --[[ModItemInventoryItemCompositeDef UZI Description]] "Designed as a personal defense weapon for rear echelon troops in the Israel Defense Forces. Intended to be used with a buttstock, but regularly wielded one-handed. Can deliver a lot of lead though accuracy may vary. "),
	AdditionalHint = T(924238872935, --[[ModItemInventoryItemCompositeDef UZI AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Надежный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сладкий бобалех"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 2400,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "SubmachineGuns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 24,
	ObjDamageMod = 20,
	AimAccuracy = 8,
	MagazineSize = 32,
	WeaponRange = 26,
	OverwatchAngle = 4080,
	Noise = 30,
	HandSlot = "TwoHanded",
	Entity = "UziFull",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagDrum_30_50_UZI",
				"JAZZ_MagLarge_20_30_UZI",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_Reflex_Open",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_PistolSuppressor",
				"JAZZ_Compensator",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
				"JAZZ_StockNormal",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	Color = "Black",
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun",
		"JAZZ_Zipper",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	WeaponMass = 80,
	CyclicRPM = 700,
	WeaponSizeClass = "Long",
	BurstLimiter = 0,
	BurstShots = 4,
	Recoil = 18,
	AutoShots = 7,

	CloseRange = 2,

	CloseRangeFactor = 95,
	BulletDropRange = 10,
	Grouping = 50,
	BaseJamChance = -20,
	WeaponResource = 3600,
}

