UndefineClass('VectorCP1')
DefineClass.VectorCP1 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "Tier 2-1",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 3,
	Reliability = 20,
	Icon = "Mod/e6L4ECj/WeaponIcons/VectorSP1.png",
	DisplayName = T(890000000001154, --[[ModItemInventoryItemCompositeDef VectorCP1 DisplayName]] "Vektor CP1"),
	DisplayNamePlural = T(890000000001294, --[[ModItemInventoryItemCompositeDef VectorCP1 DisplayNamePlural]] "Vektor CP1"),
	Description = T(890000000000012, --[[ModItemInventoryItemCompositeDef VectorCP1 Description]] "Суперкомпактный пистолет для скрытого ношения от компании Vector, базирующейся в ЮАР. Имеет автоматику с газовым торможением отката затвора. Это как с газовым двигателем, только наоборот, с торможением."),
	AdditionalHint = T(890000000000607, --[[ModItemInventoryItemCompositeDef VectorCP1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Компактный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Быстрый\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Удобный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Под пальто"),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 20,
	ObjDamageMod = 20,
	AimAccuracy = 6,
	CritChanceScaled = 35,
	MagazineSize = 15,
	WeaponRange = 18,
	OverwatchAngle = 5400,
	Entity = "VectorCP1",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_25_PISTOL_9",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
								"JAZZ_ImprovisedSuppressor",
								"JAZZ_Suppressor",
							},
		}),
		
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 2000,
	ReloadAP = 3000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 7,
	Grouping = 60,
	BaseJamChance = -20,
}

