UndefineClass('VectorCP1')
DefineClass.VectorCP1 = {
	__parents = { "Pistol" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T2 9mm",
	object_class = "Pistol",
	ScrapParts = 6,
	RepairCost = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/CZ75.png",
	DisplayName = T(848119151903, --[[ModItemInventoryItemCompositeDef VectorCP1 DisplayName]] "Vektor CP1"),
	DisplayNamePlural = T(927743133237, --[[ModItemInventoryItemCompositeDef VectorCP1 DisplayNamePlural]] "Vektor CP1"),
	Description = T(107106412369, --[[ModItemInventoryItemCompositeDef VectorCP1 Description]] 'Спортивный, боевой, полицейский, гражданский пистолет из Чехии. Практически, победитель оружейного "Евровидения", но первое место принадлежит тому, кого нельзя называть. Иначе придется его купить.'),
	AdditionalHint = T(491343014488, --[[ModItemInventoryItemCompositeDef VectorCP1 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Высокая точность"),
	UnitStat = "Marksmanship",
	Cost = 1250,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	CanAppearStandard = false,
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 21,
	ObjDamageMod = 20,
	AimAccuracy = 10,
	CritChance = 5,
	CritChanceScaled = 35,
	MagazineSize = 16,
	WeaponRange = 14,
	OverwatchAngle = 5400,
	Entity = "VectorCP1",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'Modifiable', false,
			'AvailableComponents', {
				"MagNormal",
				"MagLarge",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
				"Suppressor",
			},
			'DefaultComponent', "su",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 3000,
	ReloadAP = 3000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 98,
	BulletDropRange = 6,
	Grouping = 94,
	BaseJamChance = -20,
}

