UndefineClass('VektorR4')
DefineClass.VektorR4 = {
	__parents = { "AssaultRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "AssaultRifle",
	ScrapParts = 10,
	RepairCost = 12,
	Reliability = 85,
	Icon = "Mod/e6L4ECj/WeaponIcons/VektorR4.png",
	DisplayName = T(890000000019401, "Vektor R4"),
	DisplayNamePlural = T(890000000019402, "Vektor R4"),
	Description = T(890000000019403, "Южноафриканский армейский автомат под патрон 5,56x45 мм. Тяжёлый и надёжный, с магазином на 35 патронов. Штатная конфигурация с открытым прицелом."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5500,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 2,
	RestockWeight = 70,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_556",
	Damage = 21,
	ObjDamageMod = 50,
	AimAccuracy = 11,
	CritChanceScaled = 20,
	MagazineSize = 35,
	WeaponRange = 46,
	OverwatchAngle = 1260,
	Noise = 53,
	HandSlot = "TwoHanded",
	Entity = "JAZZ_VektorR4",
	fxClass = "Galil",
	ComponentSlots = {},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"SingleShot",
		"AutoFire",
		"JAZZ_ManeuverAR",
		"JAZZ_ControllableBurst",
		"JAZZ_LargeAutoFire",
	},
	ShootAP = 6000,
	ReloadAP = 6000,
	Recoil = 18,
	AutoShots = 6,
	WeaponMass = 43,
	CyclicRPM = 650,
	CloseRange = 7,
	CloseRangeFactor = 80,
	BulletDropRange = 15,
	Grouping = 50,
	BaseJamChance = -15,
	WeaponResource = 7000,
}

