UndefineClass('VSS')
DefineClass.VSS = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-5",
	object_class = "Carbine",
	ScrapParts = 14,
	RepairCost = 20,
	Reliability = 65,
	Icon = "Mod/e6L4ECj/WeaponIcons/VSS.png",
	DisplayName = T(851891287061, --[[ModItemInventoryItemCompositeDef VSS DisplayName]] "ВСС"),
	DisplayNamePlural = T(752413737694, --[[ModItemInventoryItemCompositeDef VSS DisplayNamePlural]] "ВСС"),
	Description = T(339208756765, --[[ModItemInventoryItemCompositeDef VSS Description]] 'Культовая среди спецназовцев и геймеров всех мастей советская и российская бесшумная снайперская винтовка. Громкость звука выстрела из нее на уровне звука пневматической винтовки. К огромному сожалению, как и "Вал", на экспорт Россией не продается.'),
	AdditionalHint = T(793881185551, --[[ModItemInventoryItemCompositeDef VSS AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Может стрелять очередями \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бесшумный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Иди своей дорогой, сталкер..."),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 100000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_9x39",
	Damage = 32,
	ObjDamageMod = 40,
	AimAccuracy = 14,
	CritChanceScaled = 40,
	MagazineSize = 20,
	WeaponRange = 38,
	OverwatchAngle = 1500,
	Noise = 5,
	HandSlot = "TwoHanded",
	Entity = "VSS",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagLarge_10_20",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Reflex_Cobra",
				"JAZZ_Reflex_PKAS",
				"JAZZ_Scope_PSO",
				"JAZZ_CombatScope_1P29",
				"JAZZ_NightScope_NSPU",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"BurstFire",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
	},
	ShootAP = 5000,
	ReloadAP = 6000,
	Recoil = 12,
	AutoShots = 9,

	CloseRange = 4,

	CloseRangeFactor = 90,
	BulletDropRange = 13,
	Grouping = 62,
	BaseJamChance = -30,
	WeaponResource = 3000,
}

