UndefineClass('VSS')
DefineClass.VSS = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T3-",
	object_class = "SniperRifle",
	ScrapParts = 14,
	Reliability = 35,
	Icon = "Mod/e6L4ECj/WeaponIcons/VSS.png",
	ItemType = "DMR",
	DisplayName = T(851891287061, --[[ModItemInventoryItemCompositeDef VSS DisplayName]] "ВСС"),
	DisplayNamePlural = T(752413737694, --[[ModItemInventoryItemCompositeDef VSS DisplayNamePlural]] "ВСС"),
	Description = T(339208756765, --[[ModItemInventoryItemCompositeDef VSS Description]] 'Культовая среди спецназовцев и геймеров всех мастей советская и российская бесшумная снайперская винтовка. Громкость звука выстрела из нее на уровне звука пневматической винтовки. К огромному сожалению, как и "Вал", на экспорт Россией не продается.'),
	AdditionalHint = T(793881185551, --[[ModItemInventoryItemCompositeDef VSS AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бесшумное\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Возможность стрельбы очередями"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 100000,
	CanAppearInShop = true,
	Tier = 2,
	MaxStock = 1,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_9x39",
	Damage = 32,
	ObjDamageMod = 40,
	AimAccuracy = 23,
	CritChance = 10,
	CritChanceScaled = 20,
	MagazineSize = 20,
	WeaponRange = 38,
	OverwatchAngle = 1800,
	Noise = 5,
	HandSlot = "TwoHanded",
	Entity = "VSS",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"MagNormal",
				"MagLarge_10_20",
			},
			'DefaultComponent', "MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Reflex_Cobra",
				"JAZZ_Reflex_PKAS",
				"JAZZ_Scope_PSO",
				"JAZZ_CombatScope_1P29",
				"JAZZ_NightScope_NSPU",
				"JAZZ_Scope_Scout",
			},
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"SingleShot",
		"BurstFire",
		"CancelShot",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	Recoil = 8,
	AutoShots = 9,
	Handling = 85,
	BulletDropRange = 12,
	Grouping = 235,
	BaseJamChance = -30,
	WeaponResource = 3000,
}

