UndefineClass('Webley')
DefineClass.Webley = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 3,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/Webley.png",
	DisplayName = T(436628869426, --[[ModItemInventoryItemCompositeDef Webley DisplayName]] "Colt M1917 .45 Service Revolver"),
	DisplayNamePlural = T(427566606201, --[[ModItemInventoryItemCompositeDef Webley DisplayNamePlural]] "Colt M1917 .45 Service Revolver"),
	Description = T(878461703337, --[[ModItemInventoryItemCompositeDef Webley Description]] "Старый, заслуженный револьвер одинарного действия, разработанный для армии США. Главное, носите c пустой каморой под курком, если не хотите лишиться ноги."),
	AdditionalHint = T(434107786112, --[[ModItemInventoryItemCompositeDef Webley AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Револьвер - точный, надежный, но большие затраты ОД на выстрел и перезарядку"),
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_38",
	Damage = 27,
	ObjDamageMod = 40,
	AimAccuracy = 16,
	CritChance = 5,
	CritChanceScaled = 30,
	MagazineSize = 6,
	WeaponRange = 16,
	OverwatchAngle = 5100,
	Noise = 28,
	Entity = "Webleyf",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelNormal",
				"BarrelLong",
			},
			'DefaultComponent', "BarrelNormal",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	Recoil = 1,
	AutoShots = 3,
	Handling = 90,
	BulletDropRange = 7,
	Grouping = 92,
	BaseJamChance = -100,
}

