UndefineClass('Welrod')
DefineClass.Welrod = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",

	comment = "T1-UNIQ",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 5,
	Reliability = 35,
	Icon = "Mod/e6L4ECj/WeaponIcons/Welrod.png",
	DisplayName = T(890000000000529, --[[ModItemInventoryItemCompositeDef Welrod DisplayName]] "Welrod"),
	DisplayNamePlural = T(890000000000505, --[[ModItemInventoryItemCompositeDef Welrod DisplayNamePlural]] "Welrod"),
	Description = T(890000000001228, --[[ModItemInventoryItemCompositeDef Welrod Description]] "Разработан во Вторую Мировую Войну сотрудниками британской Секретной Службы для диверсионных и разведывательных действий на территории противника. Пистолет имеет ручную перезарядку после каждого выстрела, а срок службы заглушающего устройства не превышает 15 выстрелов. Впрочем, для одной операции этого вполен достаточно."),
	AdditionalHint = T(519806997002, --[[ModItemInventoryItemCompositeDef Welrod AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Бесшумный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Малый магазин\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Недолговечный\n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Смертельно опасный."),
	UnitStat = "Marksmanship",
	Cost = 12000,
	CanAppearInShop = true,
	Tier = 4,
	RestockWeight = 12,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 23,
	ObjDamageMod = 40,
	AimAccuracy = 8,
	CritChance = 20,
	CritChanceScaled = 60,
	MagazineSize = 6,
	WeaponRange = 15,
	OverwatchAngle = 5100,
	Noise = 1,
	Entity = "Welrod",
	ComponentSlots = {
		
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_SuppressorIntegrated",
			},
			'DefaultComponent', "JAZZ_SuppressorIntegrated",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"MobileShot",
		"JAZZ_Mozambique",
		"JAZZ_DoubleTap",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	WeaponMass = 10,
	CyclicRPM = 0,
	WeaponSizeClass = "Compact",
	BurstLimiter = 0,
	BurstShots = 0,
	MaxAimActions = 4,
	Recoil = 18,
	AutoShots = 0,

	CloseRange = 0,

	CloseRangeFactor = 100,
	BulletDropRange = 4,
	Grouping = 82,
	BaseJamChance = -100,
}

