UndefineClass('Welrod')
DefineClass.Welrod = {
	__parents = { "Revolver" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "T1-UNIQ",
	object_class = "Revolver",
	ScrapParts = 6,
	RepairCost = 5,
	Reliability = 95,
	Icon = "Mod/e6L4ECj/WeaponIcons/Welrod.png",
	DisplayName = T(436628869426, --[[ModItemInventoryItemCompositeDef Welrod DisplayName]] "Welrod"),
	DisplayNamePlural = T(427566606201, --[[ModItemInventoryItemCompositeDef Welrod DisplayNamePlural]] "Welrod"),
	Description = T(878461703337, --[[ModItemInventoryItemCompositeDef Welrod Description]] "Разработан во Вторую Мировую Войну сотрудниками британской Секретной Службы для диверсионных и разведывательных действий на территории противника. Пистолет имеет ручную перезарядку после каждого выстрела, а срок службы заглушающего устройства не превышает 15 выстрелов. Впрочем, для одной операции этого вполен достаточно."),
	AdditionalHint = "",
	UnitStat = "Marksmanship",
	Cost = 500,
	CanAppearInShop = true,
	CategoryPair = "Handguns",
	Caliber = "JAZZ_Caliber_9x19",
	Damage = 23,
	ObjDamageMod = 40,
	AimAccuracy = 12,
	CritChance = 5,
	CritChanceScaled = 60,
	MagazineSize = 6,
	WeaponRange = 16,
	OverwatchAngle = 5100,
	Noise = 1,
	Entity = "Welrod",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Freeswap",
			'AvailableComponents', {
				"Freeswap",
			},
			'DefaultComponent', "Freeswap",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'Modifiable', false,
			'AvailableComponents', {
				"SuppressorIntegrated",
			},
			'DefaultComponent', "SuppressorIntegrated",
		}),
	},
	HolsterSlot = "Leg",
	AvailableAttacks = {
		"SingleShot",
		"DualShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 4000,
	ReloadAP = 4000,
	MaxAimActions = 2,
	Recoil = 1,
	AutoShots = 3,
	Handling = 76,
	BulletDropRange = 7,
	Grouping = 92,
	BaseJamChance = -100,
}

