UndefineClass('Winchester1894')
DefineClass.Winchester1894 = {
	__parents = { "SniperRifle" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 1-1",
	object_class = "SniperRifle",
	ScrapParts = 8,
	RepairCost = 3,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/Winchester.png",
	ItemType = "DMR",
	DisplayName = T(142435704728, --[[ModItemInventoryItemCompositeDef Winchester1894 DisplayName]] "Winchester 1894"),
	DisplayNamePlural = T(875798522299, --[[ModItemInventoryItemCompositeDef Winchester1894 DisplayNamePlural]] "Winchester 1894"),
	Description = T(534013565696, --[[ModItemInventoryItemCompositeDef Winchester1894 Description]] "Классическая винтовка прямиком из фильмов про ковбоев и индейцев. Подствольный трубчатый магазин вмещает больше патронов, чем в обычной винтовке с продольно-скользящим затвором. Как она очутилась в здешних краях - тайна, покрытая мраком."),
	AdditionalHint = T(697050056619, --[[ModItemInventoryItemCompositeDef Winchester1894 AdditionalHint]] "<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сорок четвертый \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Может стрелять в движении \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Точный \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Неудобный"),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 1750,
	CanAppearInShop = true,
	CategoryPair = "Rifles",
	Caliber = "JAZZ_Caliber_44CAL",
	Damage = 37,
	ObjDamageMod = 50,
	AimAccuracy = 12,
	CritChanceScaled = 30,
	MagazineSize = 7,
	WeaponRange = 29,
	OverwatchAngle = 1080,
	Noise = 30,
	HandSlot = "TwoHanded",
	Entity = "Weapon_Winchester",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Barrel",
			'AvailableComponents', {
				"BarrelLong",
				"BarrelNormal",
				"BarrelShort_Winchester",
			},
			'DefaultComponent', "BarrelNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"ImprovisedSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Scope",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_Reflex_Aimpoint5000",
				"JAZZ_Reflex_Closed",
				"JAZZ_Reflex_Eotech",
				"JAZZ_Reflex_M68",
				"JAZZ_CombatScope_2x",
				"JAZZ_CombatScope_ACOG",
				"JAZZ_NightScope",
				"JAZZ_Scope_6x",
				"JAZZ_Scope_12x",
				"JAZZ_Scope_Scout",
				"ImprovedIronsight",
			},
			'DefaultComponent', "ImprovedIronsight",
		}),
	},
	HolsterSlot = "Shoulder",
	ModifyRightHandGrip = true,
	AvailableAttacks = {
		"SingleShot",
		"CancelShot",
		"MobileShot",
	},
	ShootAP = 6000,
	ReloadAP = 8000,
	BurstShots = 1,
	AutoShots = 1,
	Handling = -15,
	BulletDropRange = 10,
	Grouping = 83,
	BaseJamChance = -100,
	WeaponResource = 3000,
}

