UndefineClass('ZastavaM92')
DefineClass.ZastavaM92 = {
	__parents = { "Carbine" },
	__generated_by_class = "ModItemInventoryItemCompositeDef",


	comment = "Tier 2-1",
	object_class = "Carbine",
	ScrapParts = 10,
	RepairCost = 10,
	Reliability = 70,
	Icon = "Mod/e6L4ECj/WeaponIcons/ZastavaM92.png",
	DisplayName = T(998078359086, --[[ModItemInventoryItemCompositeDef ZastavaM92 DisplayName]] "Zastava M92"),
	DisplayNamePlural = T(395524774639, --[[ModItemInventoryItemCompositeDef ZastavaM92 DisplayNamePlural]] "Zastava M92"),
	Description = T(970341728549, --[[ModItemInventoryItemCompositeDef ZastavaM92 Description]] "Коротыш под 7.62х39мм патрон. В отличие от мифического советско-российского варианта АКМСУ (который никогда не выпускался), этот реально существует и готов доказать это, проделав пару десятков дырок в телах ваших врагов."),
	AdditionalHint = T(646099169815, --[[ModItemInventoryItemCompositeDef ZastavaM92 AdditionalHint]] '<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Короткий автомат под "семерку" \n<image UI/Conversation/T_Dialogue_IconBackgroundCircle.tga 400 130 128 120> Сильная отдача'),
	LargeItem = 1,
	UnitStat = "Marksmanship",
	Cost = 5500,
	CanAppearInShop = true,
	MaxStock = 5,
	RestockWeight = 150,
	CategoryPair = "AssaultRifles",
	Caliber = "JAZZ_Caliber_762x39",
	Damage = 26,
	ObjDamageMod = 50,
	AimAccuracy = 14,
	MagazineSize = 30,
	WeaponRange = 37,
	OverwatchAngle = 1500,
	Noise = 55,
	HandSlot = "TwoHanded",
	Entity = "M92",
	ComponentSlots = {
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Muzzle",
			'CanBeEmpty', true,
			'AvailableComponents', {
				"JAZZ_ImprovisedSuppressor",
			},
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Magazine",
			'AvailableComponents', {
				"JAZZ_MagNormal",
				"JAZZ_MagQuick_AK",
				"JAZZ_MagLarge_30_40",
				"JAZZ_MagDrum_30_75",
			},
			'DefaultComponent', "JAZZ_MagNormal",
		}),
		PlaceObj('WeaponComponentSlot', {
			'SlotType', "Stock",
			'Modifiable', false,
			'AvailableComponents', {
				"JAZZ_StockLightUnFolded",
				"JAZZ_StockLightFolded",
			},
			'DefaultComponent', "JAZZ_StockLightUnFolded",
		}),
	},
	HolsterSlot = "Shoulder",
	AvailableAttacks = {
		"BurstFire",
		"AutoFire",
		"SingleShot",
		"RunAndGun_Carbine",
		"JAZZ_TargetSweep",
	},
	ShootAP = 5000,
	ReloadAP = 5000,
	WeaponMass = 35,
	CyclicRPM = 700,
	WeaponSizeClass = "Rifle",
	BurstLimiter = 0,
	BurstShots = 4,
	Recoil = 20,
	AutoShots = 7,

	CloseRange = 5,

	CloseRangeFactor = 90,
	BulletDropRange = 12,
	Grouping = 53,
	BaseJamChance = -20,
	WeaponResource = 5000,
}

