#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit Lua snippet to live-patch AME AppearancePresets from jazz-units/items.lua.

Preferred path when game is closed: just reload the mod / restart JA3 — items.lua
already has the correct Body/Head/Hat. Use this only for mid-session refresh via DAP.

Hardens ApplyAppearance: sets preset fields, mirrors onto unit appearance object if
present, then ApplyAppearance(id) and ApplyAppearance(id, true) when supported.
"""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
ITEMS = ROOT.parent / "jazz-units" / "items.lua"
OUT = ROOT / "docs" / "tools" / "_tmp_ame_live_patch.lua"


def main() -> None:
    text = ITEMS.read_text(encoding="utf-8")
    parts = text.split("PlaceObj('ModItemAppearancePreset', {")
    rows: list[tuple[str, str, str, str]] = []
    for chunk in parts[1:]:
        id_m = re.search(r'\bid = "(JAZZ_AME_\d+)"', chunk)
        if not id_m:
            continue
        aid = id_m.group(1)
        hp = chunk[: id_m.start()]

        def g(k: str) -> str:
            m = re.search(rf'\b{k} = "([^"]*)"', hp)
            return m.group(1) if m else ""

        rows.append((aid, g("Head"), g("Hat"), g("Body")))

    lines = [
        "-- Auto-generated by _emit_ame_live_patch.py — dofile via DAP if mid-session.",
        "-- Prefer full mod reload / game restart when possible.",
        "local P = {",
    ]
    for aid, h, hat, b in rows:
        lines.append(f'\t["{aid}"] = {{ Head = "{h}", Hat = "{hat}", Body = "{b}" }},')
    lines.append("}")
    lines.extend(
        [
            "local function apply_fix(a, fix)",
            "\tif not a then return end",
            '\tif fix.Head and fix.Head ~= "" then a.Head = fix.Head end',
            '\ta.Hat = (fix.Hat ~= "" and fix.Hat) or nil',
            '\tif fix.Body and fix.Body ~= "" then a.Body = fix.Body end',
            "end",
            "local function refresh_unit(u, id)",
            "\tif not u or not u.ApplyAppearance then return end",
            "\t-- Mirror onto attached appearance table if engine keeps a copy.",
            "\tlocal app = rawget(u, 'appearance') or rawget(u, 'AppearancePreset')",
            "\tif type(app) == 'table' and P[id] then apply_fix(app, P[id]) end",
            "\tlocal ok = pcall(function() u:ApplyAppearance(id, true) end)",
            "\tif not ok then u:ApplyAppearance(id) end",
            "end",
            "local n = 0",
            "local pc = 0",
            "local sample = {}",
            "for id, fix in pairs(P) do",
            "\tpc = pc + 1",
            "\tlocal a = AppearancePresets[id]",
            "\tapply_fix(a, fix)",
            "\tfor _, u in pairs(g_Units or {}) do",
            "\t\tif u.Appearance == id then",
            "\t\t\trefresh_unit(u, id)",
            "\t\t\tn = n + 1",
            "\t\tend",
            "\tend",
            "end",
            "do",
            '\tlocal a = AppearancePresets["JAZZ_AME_38"]',
            '\tsample.body = a and a.Body or "?"',
            '\tsample.head = a and a.Head or "?"',
            "end",
            'return string.format("presets=%d units_refreshed=%d noah_body=%s noah_head=%s", pc, n, tostring(sample.body), tostring(sample.head))',
        ]
    )
    OUT.write_text("\n".join(lines), encoding="utf-8")
    # Spot-check Noah in emitted table
    noah = next((r for r in rows if r[0] == "JAZZ_AME_38"), None)
    print(f"wrote {OUT} rows={len(rows)}")
    if noah:
        print(f"JAZZ_AME_38 Head={noah[1]} Hat={noah[2] or '-'} Body={noah[3]}")


if __name__ == "__main__":
    main()
