#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Emit combat-bark runtime bank + loc rows from _aibark_bank_data.py.

  python docs/tools/_emit_aibark_runtime.py

Writes the Lua table between JAZZ-AI-BARK-BANK markers in
Code/System_AI_CombatBarks.lua and appends RU/EN CSV + catalog rows
for IDs 890000000020157..890000000020596. Idempotent: skips existing IDs.
"""
from __future__ import annotations

import csv
import re
import sys
from pathlib import Path

TOOLS = Path(__file__).resolve().parent
ROOT = TOOLS.parents[1]
sys.path.insert(0, str(TOOLS))
from _aibark_bank_data import ID0, iter_rows, row_count  # noqa: E402

LUA = ROOT / "Code" / "System_AI_CombatBarks.lua"
MARK_A = "-- JAZZ-AI-BARK-BANK-BEGIN"
MARK_B = "-- JAZZ-AI-BARK-BANK-END"
CTX = "jazz:Code/System_AI_CombatBarks.lua"
ID_PREFIX = 890000000000000
FIRST = ID_PREFIX + ID0
LAST = FIRST + row_count() - 1


def loc_id(short: int) -> str:
    return str(ID_PREFIX + short)


def lua_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def emit_lua_bank() -> str:
    lines = [
        MARK_A,
        "-- Generated by docs/tools/_emit_aibark_runtime.py. Do not edit by hand.",
        "JazzAI_CombatBarkBank = {",
    ]
    current_event = None
    current_band = None
    for event, band, ru, en, tags, sid in iter_rows():
        if event != current_event:
            if current_band is not None:
                lines.append("\t\t},")
                current_band = None
            if current_event is not None:
                lines.append("\t},")
            lines.append(f'\t["{event}"] = {{')
            current_event = event
        if band != current_band:
            if current_band is not None:
                lines.append("\t\t},")
            lines.append(f'\t\t["{band}"] = {{')
            current_band = band
        tag_lit = ", ".join(f'"{t}"' for t in sorted(tags))
        lid = loc_id(sid)
        lines.append(
            f'\t\t\t{{ id = {lid}, en = "{lua_escape(en)}", '
            f'tags = {{ {tag_lit} }} }},'
        )
        _ = ru  # Russian lives in CSV; Lua T() fallback is English
    if current_band is not None:
        lines.append("\t\t},")
    if current_event is not None:
        lines.append("\t},")
    lines.append("}")
    lines.append(MARK_B)
    return "\n".join(lines) + "\n"


def patch_lua() -> None:
    text = LUA.read_text(encoding="utf-8")
    if MARK_A not in text or MARK_B not in text:
        raise SystemExit(f"missing bank markers in {LUA}")
    pre, rest = text.split(MARK_A, 1)
    _, post = rest.split(MARK_B, 1)
    LUA.write_text(pre + emit_lua_bank() + post.lstrip("\n"), encoding="utf-8")
    print("patched", LUA.relative_to(ROOT))


def csv_has_id(path: Path, needle: str) -> bool:
    return needle in path.read_text(encoding="utf-8")


def append_text(path: Path, block: str) -> None:
    data = path.read_text(encoding="utf-8")
    if not data.endswith("\n"):
        data += "\n"
    path.write_text(data + block, encoding="utf-8")


def quote_csv_field(s: str) -> str:
    if any(c in s for c in ',"\n\r'):
        return '"' + s.replace('"', '""') + '"'
    return s


def apply_runtime_csv() -> None:
    ru_path = ROOT / "Russian.csv"
    en_path = ROOT / "English.csv"
    first = loc_id(ID0)
    if csv_has_id(ru_path, first):
        print("skip runtime CSV, already has", first)
        return
    ru_rows = []
    en_rows = []
    for _event, _band, ru, en, _tags, sid in iter_rows():
        lid = loc_id(sid)
        ru_rows.append(
            f"{lid},{quote_csv_field(en)},{quote_csv_field(ru)},,{CTX}\n"
        )
        en_rows.append(
            f"{lid},{quote_csv_field(en)},{quote_csv_field(en)},,{CTX}\n"
        )
    append_text(ru_path, "".join(ru_rows))
    append_text(en_path, "".join(en_rows))
    print(f"appended {len(ru_rows)} rows to Russian.csv + English.csv")


def apply_catalog() -> None:
    cat = ROOT / "Localization" / "Strings.csv"
    first = loc_id(ID0)
    if csv_has_id(cat, first):
        print("skip Strings.csv, already has", first)
        return
    rows = []
    for _event, _band, ru, en, _tags, sid in iter_rows():
        lid = loc_id(sid)
        rows.append(
            [
                lid,
                en,
                "",
                ru,
                en,
                "russian-override;new-id",
                CTX,
                "jazz",
                CTX,
                "JAZZ-AI-BARK-001",
            ]
        )
    with cat.open("a", encoding="utf-8", newline="") as fh:
        w = csv.writer(fh, lineterminator="\n")
        w.writerows(rows)
    print(f"appended {len(rows)} rows to Localization/Strings.csv")


def apply_manuals() -> None:
    en_m = ROOT / "Localization" / "EnglishManual.csv"
    ru_m = ROOT / "Localization" / "RussianManual.csv"
    first = loc_id(ID0)
    if csv_has_id(en_m, first):
        print("skip manuals, already has", first)
        return

    def last_n(path: Path) -> int:
        n = 0
        for line in path.read_text(encoding="utf-8").splitlines()[1:]:
            if line[:1].isdigit():
                n = max(n, int(line.split(",", 1)[0]))
        return n

    en_n = last_n(en_m)
    ru_n = last_n(ru_m)
    en_block = []
    ru_block = []
    for _event, _band, ru, en, _tags, sid in iter_rows():
        lid = loc_id(sid)
        en_n += 1
        ru_n += 1
        en_block.append(
            f"{en_n},{lid},{quote_csv_field(en)},{quote_csv_field(en)},JAZZ-AI-BARK-001\n"
        )
        ru_block.append(
            f"{ru_n},{lid},{quote_csv_field(en)},{quote_csv_field(ru)},JAZZ-AI-BARK-001\n"
        )
    append_text(en_m, "".join(en_block))
    append_text(ru_m, "".join(ru_block))
    print(f"appended {len(en_block)} rows to English/Russian manuals")


def main() -> int:
    n = row_count()
    print(f"rows={n} loc={FIRST}..{LAST}")
    patch_lua()
    apply_runtime_csv()
    apply_catalog()
    apply_manuals()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
